      SUBROUTINE MG5_1_SMATRIX(P, FLAV_IDX, ANS_SUMMED)
C     
C     Simple routine wrapper to provide the same interface for
C     backward compatibility for usage without split orders.
C     
C     
C     CONSTANTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=4)
      INTEGER NSQAMPSO
      PARAMETER (NSQAMPSO=1)
C     
C     ARGUMENTS
C     
      REAL*8 P(0:3,NEXTERNAL), ANS_SUMMED
C     FLAV_IDX selects one column of the flavor table, i.e. one of the
C     flavor combinations this (possibly merged) matrix element covers.
C     The canonical flavor is column 1.
      INTEGER FLAV_IDX
C     
C     VARIABLES
C     
      INTEGER I
      REAL*8 ANS(0:NSQAMPSO)
C     
C     BEGIN CODE
C     
      CALL MG5_1_SMATRIX_SPLITORDERS(P, FLAV_IDX, ANS)
      ANS_SUMMED=ANS(0)

      END

      SUBROUTINE MG5_1_SMATRIXHEL(P,HEL, FLAV_IDX, ANS)
      IMPLICIT NONE
C     
C     CONSTANT
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=4)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=16)
C     
C     ARGUMENTS
C     
      REAL*8 P(0:3,NEXTERNAL),ANS
      INTEGER HEL
      INTEGER FLAV_IDX
C     
C     GLOBAL VARIABLES
C     
      INTEGER USERHEL
      COMMON/MG5_1_HELUSERCHOICE/USERHEL
C     ----------
C     BEGIN CODE
C     ----------
      USERHEL=HEL
      CALL MG5_1_SMATRIX(P, FLAV_IDX, ANS)
      USERHEL=-1

      END

      SUBROUTINE MG5_1_SMATRIX_SPLITORDERS(P, FLAV_IDX, ANS)
C     
C     Generated by MadGraph5_aMC@NLO v. %(version)s, %(date)s
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     MadGraph StandAlone Version
C     
C     Returns amplitude squared summed/avg over colors
C     and helicities
C     for the point in phase space P(0:3,NEXTERNAL)
C     
C     Process: u u~ > u u~ [ virt = QCD ] @1
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=4)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=16)
      INTEGER NSQAMPSO
      PARAMETER (NSQAMPSO=1)
      INTEGER HELAVGFACTOR
      PARAMETER (HELAVGFACTOR=4)
      LOGICAL CHOSEN_SO_CONFIGS(NSQAMPSO)
      DATA CHOSEN_SO_CONFIGS/.TRUE./
      COMMON/MG5_1_CHOSEN_BORN_SQSO/CHOSEN_SO_CONFIGS
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS(0:NSQAMPSO)
C     FLAV_IDX (the dummy argument) is declared with NFLAV below.
C     
C     LOCAL VARIABLES
C     
      INTEGER NHEL(NEXTERNAL,NCOMB)
      REAL*8 T(NSQAMPSO), BUFF
      INTEGER IHEL,IDEN, I
      INTEGER JC(NEXTERNAL)
C     One good-helicity table and one warm-up counter per flavor: the
C     helicity configurations that vanish depend on the flavor (masses
C      and
C     the diagrams the flavor mask keeps), so they cannot be shared.
      INTEGER FLAVOR(NEXTERNAL)
      INTEGER NFLAV
      PARAMETER (NFLAV=1)
      INTEGER NNTRY_FLAV, NGOODHEL_FLAV
      PARAMETER (NNTRY_FLAV=NFLAV)
      PARAMETER (NGOODHEL_FLAV=NCOMB*NFLAV)
      INTEGER FLAV_IDX
      INTEGER NTRY(NFLAV)
      LOGICAL GOODHEL(NCOMB,NFLAV)
      DATA NTRY/NNTRY_FLAV*0/
      DATA GOODHEL/NGOODHEL_FLAV*.FALSE./
      DATA (NHEL(I,   1),I=1,4) / 1,-1,-1, 1/
      DATA (NHEL(I,   2),I=1,4) / 1,-1,-1,-1/
      DATA (NHEL(I,   3),I=1,4) / 1,-1, 1, 1/
      DATA (NHEL(I,   4),I=1,4) / 1,-1, 1,-1/
      DATA (NHEL(I,   5),I=1,4) / 1, 1,-1, 1/
      DATA (NHEL(I,   6),I=1,4) / 1, 1,-1,-1/
      DATA (NHEL(I,   7),I=1,4) / 1, 1, 1, 1/
      DATA (NHEL(I,   8),I=1,4) / 1, 1, 1,-1/
      DATA (NHEL(I,   9),I=1,4) /-1,-1,-1, 1/
      DATA (NHEL(I,  10),I=1,4) /-1,-1,-1,-1/
      DATA (NHEL(I,  11),I=1,4) /-1,-1, 1, 1/
      DATA (NHEL(I,  12),I=1,4) /-1,-1, 1,-1/
      DATA (NHEL(I,  13),I=1,4) /-1, 1,-1, 1/
      DATA (NHEL(I,  14),I=1,4) /-1, 1,-1,-1/
      DATA (NHEL(I,  15),I=1,4) /-1, 1, 1, 1/
      DATA (NHEL(I,  16),I=1,4) /-1, 1, 1,-1/
      DATA IDEN/36/
C     
C     FUNCTIONS
C     
      INTEGER MG5_1_BROKEN_SYM
C     
C     GLOBAL VARIABLES
C     
      INTEGER USERHEL
      DATA USERHEL/-1/
      COMMON/MG5_1_HELUSERCHOICE/USERHEL

C     ----------
C     BEGIN CODE
C     ----------
C     FLAV_IDX=0 (or out of range): GET_FLAVOR_INDEX could not resolve
C      the
C     requested flavor -- it is not an allowed combination, so its
C      matrix
C     element is identically zero. Short-circuit before touching the
C     1..NFLAV GOODHEL/NTRY arrays.
      IF (FLAV_IDX.LT.1 .OR. FLAV_IDX.GT.NFLAV) THEN
        DO I=0,NSQAMPSO
          ANS(I) = 0D0
        ENDDO
        RETURN
      ENDIF
      CALL MG5_1_GET_FLAVOR(FLAV_IDX, FLAVOR)
      NTRY(FLAV_IDX)=NTRY(FLAV_IDX)+1
      DO IHEL=1,NEXTERNAL
        JC(IHEL) = +1
      ENDDO
      DO I=1,NSQAMPSO
        ANS(I) = 0D0
      ENDDO
      DO IHEL=1,NCOMB
        IF (USERHEL.EQ.-1.OR.USERHEL.EQ.IHEL) THEN
          IF (GOODHEL(IHEL,FLAV_IDX) .OR. NTRY(FLAV_IDX) .LT. 2) THEN
            CALL MG5_1_MATRIX(P ,NHEL(1,IHEL),JC(1), FLAV_IDX, T)
            BUFF=0D0
            DO I=1,NSQAMPSO
              ANS(I)=ANS(I)+T(I)
              BUFF=BUFF+T(I)
            ENDDO
            IF (BUFF .NE. 0D0 .AND. .NOT.    GOODHEL(IHEL,FLAV_IDX))
     $        THEN
              GOODHEL(IHEL,FLAV_IDX)=.TRUE.
            ENDIF
          ENDIF
        ENDIF
      ENDDO
      ANS(0)=0.0D0
      DO I=1,NSQAMPSO
C       IDEN averages the canonical flavor; BROKEN_SYM undoes the
C        identical
C       -particle part of it for the flavors that are not actually
C        identical.
        ANS(I)=ANS(I)/DBLE(IDEN)*MG5_1_BROKEN_SYM(FLAVOR)
        IF (CHOSEN_SO_CONFIGS(I)) THEN
          ANS(0)=ANS(0)+ANS(I)
        ENDIF
      ENDDO
      IF(USERHEL.NE.-1) THEN
        ANS(0)=ANS(0)*HELAVGFACTOR
        DO I=1,NSQAMPSO
          ANS(I)=ANS(I)*HELAVGFACTOR
        ENDDO
      ENDIF
      END

      SUBROUTINE MG5_1_SMATRIXHEL_SPLITORDERS(P,HEL, FLAV_IDX, ANS)
      IMPLICIT NONE
C     
C     CONSTANT
C     
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=4)
      INTEGER                 NCOMB
      PARAMETER (             NCOMB=16)
      INTEGER NSQAMPSO
      PARAMETER (NSQAMPSO=1)
C     
C     ARGUMENTS
C     
      REAL*8 P(0:3,NEXTERNAL),ANS(0:NSQAMPSO)
      INTEGER HEL
      INTEGER FLAV_IDX
C     
C     GLOBAL VARIABLES
C     
      INTEGER USERHEL
      COMMON/MG5_1_HELUSERCHOICE/USERHEL
C     ----------
C     BEGIN CODE
C     ----------
      USERHEL=HEL
      CALL MG5_1_SMATRIX_SPLITORDERS(P, FLAV_IDX, ANS)
      USERHEL=-1

      END

      SUBROUTINE MG5_1_MATRIX(P,NHEL,IC,FLAV_IDX,RES)
      USE MODEL_OBJECT
C     
C     Generated by MadGraph5_aMC@NLO v. %(version)s, %(date)s
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     Returns amplitude squared summed/avg over colors
C     for the point with external lines W(0:6,NEXTERNAL)
C     
C     Process: u u~ > u u~ [ virt = QCD ] @1
C     
      USE ALOHA_OBJECT
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=2)
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=4)
      INTEGER    NWAVEFUNCS, NCOLOR
      PARAMETER (NWAVEFUNCS=5, NCOLOR=2)
      INTEGER NAMPSO, NSQAMPSO
      PARAMETER (NAMPSO=1, NSQAMPSO=1)
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
      COMPLEX*16 IMAG1
      PARAMETER (IMAG1=(0D0,1D0))
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL), IC(NEXTERNAL)
C     The HELAS calls below take FLAVOR, which the block that follows
C     rebuilds from FLAV_IDX -- one column of the flavor table, i.e.
C      one of
C     the flavor combinations this (possibly merged) matrix element
C      covers.
      INTEGER FLAV_IDX
      REAL*8 RES(NSQAMPSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I,J,M,N
      COMPLEX*16 ZTEMP
      INTEGER CF(NCOLOR*(NCOLOR+1))
      INTEGER CF_INDEX, DENOM
      COMPLEX*16 AMP(NGRAPHS)
      COMPLEX*16 JAMP(NCOLOR,NAMPSO), LNJAMP(NCOLOR,NAMPSO)
      COMPLEX*16 TMP_JAMP(0)
      COMMON/MG5_1_JAMP/JAMP,LNJAMP
      TYPE(ALOHA) W(NWAVEFUNCS)
      COMPLEX*16 DUM0,DUM1
      DATA DUM0, DUM1/(0D0, 0D0), (1D0, 0D0)/
      INTEGER FLAVOR(NEXTERNAL)
C     Flavor table for the FLAV_IDX -> FLAVOR rebuild.
      INTEGER NMASK_FLAV
      PARAMETER (NMASK_FLAV=1)
      INTEGER MASK_J
      INTEGER FLAV_TABLE(NEXTERNAL, NMASK_FLAV)
      DATA FLAV_TABLE / 1, 1, 1, 1 /
C     
C     FUNCTION
C     
      INTEGER MG5_1_SQSOINDEX
C     
C     GLOBAL VARIABLES
C     
      INCLUDE 'coupl.inc'
C     
C     COLOR DATA
C     
      DATA DENOM/1/
      DATA (CF(I),I=  1,  2) /9,6/
C     1 T(2,1) T(3,4)
      DATA (CF(I),I=  3,  3) /9/
C     1 T(2,4) T(3,1)
C     ----------
C     BEGIN CODE
C     ----------
C     Rebuild FLAVOR(NEXTERNAL) from the resolved flavor index.
      IF (FLAV_IDX .GE. 1 .AND. FLAV_IDX .LE. NMASK_FLAV) THEN
        DO MASK_J = 1, NEXTERNAL
          FLAVOR(MASK_J) = FLAV_TABLE(MASK_J, FLAV_IDX)
        ENDDO
      ELSE
        DO MASK_J = 1, NEXTERNAL
          FLAVOR(MASK_J) = FLAV_TABLE(MASK_J, 1)
        ENDDO
      ENDIF
      CALL IXXXXX(P(0,1),ZERO,NHEL(1),+1, FLAVOR(1),W(1))
      CALL OXXXXX(P(0,2),ZERO,NHEL(2),-1, FLAVOR(2),W(2))
      CALL OXXXXX(P(0,3),ZERO,NHEL(3),+1, FLAVOR(3),W(3))
      CALL IXXXXX(P(0,4),ZERO,NHEL(4),-1, FLAVOR(4),W(4))
      CALL FFV1P0_3(W(1),W(2),GC_5,ZERO,ZERO,W(5))
C     Amplitude(s) for diagram number 1
      CALL FFV1_0(W(4),W(3),W(5),GC_5,AMP(1))
      CALL FFV1P0_3(W(1),W(3),GC_5,ZERO,ZERO,W(5))
C     Amplitude(s) for diagram number 2
      CALL FFV1_0(W(4),W(2),W(5),GC_5,AMP(2))
C     JAMPs contributing to orders QCD=2
      JAMP(1,1) = (1.666666666666667D-01)*AMP(1)+(5.000000000000000D
     $ -01)*AMP(2)
      JAMP(2,1) = (-5.000000000000000D-01)*AMP(1)+(-1.666666666666667D
     $ -01)*AMP(2)
      LNJAMP(1,1) = (5.000000000000000D-01)*AMP(2)
      LNJAMP(2,1) = (-5.000000000000000D-01)*AMP(1)

      RES(:) = 0.D0
      DO M = 1, NAMPSO
        CF_INDEX = 0
        DO I = 1, NCOLOR
          ZTEMP = (0.D0,0.D0)
          DO J = I, NCOLOR
            CF_INDEX = CF_INDEX +1
            ZTEMP = ZTEMP + CF(CF_INDEX)*JAMP(J,M)
          ENDDO
          DO N = 1, NAMPSO
            RES(MG5_1_SQSOINDEX(M,N)) = RES(MG5_1_SQSOINDEX(M,N)) +
     $        ZTEMP*DCONJG(JAMP(I,N))
          ENDDO
        ENDDO
      ENDDO
      RES(:) = RES(:)/DENOM
      END
































      SUBROUTINE MG5_1_BORN(P,NHEL,FLAVOR)
      USE MODEL_OBJECT
C     
C     Generated by MadGraph5_aMC@NLO v. %(version)s, %(date)s
C     By the MadGraph5_aMC@NLO Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     Returns amplitude squared summed/avg over colors
C     for the point with external lines W(0:6,NEXTERNAL)
C     
C     Process: u u~ > u u~ [ virt = QCD ] @1
C     
      USE ALOHA_OBJECT
      IMPLICIT NONE
C     
C     CONSTANTS
C     

      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=2)
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=4)
      INTEGER    NWAVEFUNCS, NCOLOR
      PARAMETER (NWAVEFUNCS=5, NCOLOR=2)
      INTEGER NAMPSO, NSQAMPSO
      PARAMETER (NAMPSO=1, NSQAMPSO=1)
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
      COMPLEX*16 IMAG1
      PARAMETER (IMAG1=(0D0,1D0))

C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL)
C     FLAVOR carries the per-leg flavor of the requested combination,
C      in the
C     same convention as the non-split BORN of
C      matrix_standalone_matchbox.inc.
C     It is resolved to a flavor-table column below.
      INTEGER FLAVOR(NEXTERNAL)
C     
C     LOCAL VARIABLES
C     
      INTEGER IC(NEXTERNAL)
      INTEGER I,J,M,N
      COMPLEX*16 ZTEMP
      INTEGER CF(NCOLOR*(NCOLOR+1)/2)
      INTEGER CF_INDEX, DENOM
      COMPLEX*16 AMP(NGRAPHS)
      COMPLEX*16 JAMP(NCOLOR,NAMPSO), LNJAMP(NCOLOR,NAMPSO)
      COMPLEX*16 TMP_JAMP(0)
      COMMON/MG5_1_JAMP/JAMP,LNJAMP
      TYPE(ALOHA) W(NWAVEFUNCS)
      COMPLEX*16 DUM0,DUM1
      DATA DUM0, DUM1/(0D0, 0D0), (1D0, 0D0)/
      INTEGER FLAV_IDX
      INTEGER MG5_1_GET_FLAVOR_INDEX
C     Flavor table for the FLAV_IDX -> FLAVOR rebuild.
      INTEGER NMASK_FLAV
      PARAMETER (NMASK_FLAV=1)
      INTEGER MASK_J
      INTEGER FLAV_TABLE(NEXTERNAL, NMASK_FLAV)
      DATA FLAV_TABLE / 1, 1, 1, 1 /

C     
C     GLOBAL VARIABLES
C     
      INCLUDE 'coupl.inc'
C     
C     COLOR DATA
C     
      DATA DENOM/1/
      DATA (CF(I),I=  1,  2) /9,6/
C     1 T(2,1) T(3,4)
      DATA (CF(I),I=  3,  3) /9/
C     1 T(2,4) T(3,1)
C     ----------
C     BEGIN CODE
C     ----------
      DO I=1,NEXTERNAL
        IC(I) = 1
      ENDDO


      FLAV_IDX = MG5_1_GET_FLAVOR_INDEX(FLAVOR)
C     Unresolved flavor (not an allowed combination): all color
C      amplitudes
C     are zero.
      IF (FLAV_IDX.EQ.0) THEN
        DO M = 1, NAMPSO
          DO I = 1, NCOLOR
            JAMP(I,M) = (0D0, 0D0)
            LNJAMP(I,M) = (0D0, 0D0)
          ENDDO
        ENDDO
        RETURN
      ENDIF
C     Rebuild FLAVOR(NEXTERNAL) from the resolved flavor index.
      IF (FLAV_IDX .GE. 1 .AND. FLAV_IDX .LE. NMASK_FLAV) THEN
        DO MASK_J = 1, NEXTERNAL
          FLAVOR(MASK_J) = FLAV_TABLE(MASK_J, FLAV_IDX)
        ENDDO
      ELSE
        DO MASK_J = 1, NEXTERNAL
          FLAVOR(MASK_J) = FLAV_TABLE(MASK_J, 1)
        ENDDO
      ENDIF
      CALL IXXXXX(P(0,1),ZERO,NHEL(1),+1, FLAVOR(1),W(1))
      CALL OXXXXX(P(0,2),ZERO,NHEL(2),-1, FLAVOR(2),W(2))
      CALL OXXXXX(P(0,3),ZERO,NHEL(3),+1, FLAVOR(3),W(3))
      CALL IXXXXX(P(0,4),ZERO,NHEL(4),-1, FLAVOR(4),W(4))
      CALL FFV1P0_3(W(1),W(2),GC_5,ZERO,ZERO,W(5))
C     Amplitude(s) for diagram number 1
      CALL FFV1_0(W(4),W(3),W(5),GC_5,AMP(1))
      CALL FFV1P0_3(W(1),W(3),GC_5,ZERO,ZERO,W(5))
C     Amplitude(s) for diagram number 2
      CALL FFV1_0(W(4),W(2),W(5),GC_5,AMP(2))
C     JAMPs contributing to orders QCD=2
      JAMP(1,1) = (1.666666666666667D-01)*AMP(1)+(5.000000000000000D
     $ -01)*AMP(2)
      JAMP(2,1) = (-5.000000000000000D-01)*AMP(1)+(-1.666666666666667D
     $ -01)*AMP(2)
      LNJAMP(1,1) = (5.000000000000000D-01)*AMP(2)
      LNJAMP(2,1) = (-5.000000000000000D-01)*AMP(1)

      END

      SUBROUTINE MG5_1_GET_JAMP(NJAMP, SOINDEX, ONEJAMP)

      INTEGER     NCOLOR, NJAMP, SOINDEX
      PARAMETER (NCOLOR=2)
      INTEGER NAMPSO
      PARAMETER (NAMPSO=1)
      COMPLEX*16  JAMP(NCOLOR,NAMPSO), LNJAMP(NCOLOR,NAMPSO), ONEJAMP
      COMMON/MG5_1_JAMP/JAMP,LNJAMP

      ONEJAMP = JAMP(NJAMP+1, SOINDEX)  ! +1 since njamp start at zero (c convention)
      END

      SUBROUTINE MG5_1_GET_LNJAMP(NJAMP, SOINDEX, ONEJAMP)

      INTEGER     NCOLOR, NJAMP, SOINDEX
      PARAMETER (NCOLOR=2)
      INTEGER NAMPSO
      PARAMETER (NAMPSO=1)
      COMPLEX*16  JAMP(NCOLOR,NAMPSO), LNJAMP(NCOLOR,NAMPSO), ONEJAMP
      COMMON/MG5_1_JAMP/JAMP,LNJAMP

      ONEJAMP = LNJAMP(NJAMP+1,SOINDEX)  ! +1 since njamp start at zero (c convention)
      END


      SUBROUTINE MG5_1_GET_NCOLOR(IN1, IN2, OUT)

      INTEGER IN1, IN2, OUT

      IF (IN1.EQ.0.AND.IN2.EQ.0)THEN
        OUT = 2


      ELSEIF (IN1.EQ.0.AND.IN2.EQ.1)THEN
        OUT = 1


      ELSEIF (IN1.EQ.0.AND.IN2.EQ.2)THEN
        OUT = 0


      ELSEIF (IN1.EQ.0.AND.IN2.EQ.3)THEN
        OUT = 3


      ELSEIF (IN1.EQ.0.AND.IN2.EQ.4)THEN
        OUT = 4


      ELSEIF (IN1.EQ.0.AND.IN2.EQ.5)THEN
        OUT = 0


      ELSEIF (IN1.EQ.1.AND.IN2.EQ.0)THEN
        OUT = 2


      ELSEIF (IN1.EQ.1.AND.IN2.EQ.1)THEN
        OUT = 4


      ELSEIF (IN1.EQ.1.AND.IN2.EQ.2)THEN
        OUT = 0


      ELSEIF (IN1.EQ.1.AND.IN2.EQ.3)THEN
        OUT = 3


      ELSEIF (IN1.EQ.1.AND.IN2.EQ.4)THEN
        OUT = 1


      ELSEIF (IN1.EQ.1.AND.IN2.EQ.5)THEN
        OUT = 0

      ELSE
        OUT = - 1
      ENDIF
      END

      SUBROUTINE MG5_1_GET_NCOL(NCOL)
      INTEGER NCOL
      NCOL = 2
      RETURN
      END

      SUBROUTINE MG5_1_GET_MAXSOINDEX(OUT)

      INTEGER OUT
      OUT  = 1
      RETURN
      END

      SUBROUTINE MG5_1__GET_CHOSEN_SO_CONFIG(M,N, OUT)

      INTEGER M, N
      LOGICAL OUT
      PARAMETER (NSQAMPSO=1)
      LOGICAL CHOSEN_SO_CONFIGS(NSQAMPSO)
      DATA CHOSEN_SO_CONFIGS/.TRUE./
      COMMON/MG5_1_CHOSEN_BORN_SQSO/CHOSEN_SO_CONFIGS

      OUT  = CHOSEN_SO_CONFIGS(MG5_1_SQSOINDEX(M,N))
      RETURN
      END


      INTEGER FUNCTION MG5_1_BROKEN_SYM(FLAV)
      INCLUDE 'nexternal.inc'
      INTEGER FLAV(NEXTERNAL)
      INTEGER I,J,K,ICOMP
      INTEGER N_TOT, OLD_FACTOR, TOTAL_FACTOR
      INTEGER NCOMP, NENTRIES
      PARAMETER (NCOMP=1)
      PARAMETER (NENTRIES=2)
      INTEGER COMP_BEG(NCOMP), COMP_END(NCOMP), COMP_OLD(NCOMP)
      INTEGER PID_LIST(NENTRIES), PID_WORK(NENTRIES)
      INTEGER BLOCK_START(NENTRIES), BLOCK_LEN(NENTRIES)
      LOGICAL SAME_BLOCK
      DATA COMP_BEG /1/
      DATA COMP_END /2/
      DATA COMP_OLD /1/
      DATA PID_LIST /2,-2/
      DATA BLOCK_START /3,4/
      DATA BLOCK_LEN /1,1/

      PID_WORK = PID_LIST
      TOTAL_FACTOR = 1
      DO ICOMP=1,NCOMP
        OLD_FACTOR = COMP_OLD(ICOMP)
        IF (COMP_OLD(ICOMP).GT.1) THEN
          DO I=COMP_BEG(ICOMP),COMP_END(ICOMP)
            IF (PID_WORK(I).EQ.0) CYCLE
            N_TOT = 1
            DO J=I+1,COMP_END(ICOMP)
              IF (PID_WORK(I).EQ.PID_WORK(J)) THEN
                SAME_BLOCK = .TRUE.
                IF (BLOCK_LEN(I).NE.BLOCK_LEN(J)) SAME_BLOCK = .FALSE.
                DO K=1,BLOCK_LEN(I)
                  IF (FLAV(BLOCK_START(I)+K-1).NE.FLAV(BLOCK_START(J)
     $             +K-1)) THEN
                    SAME_BLOCK = .FALSE.
                  ENDIF
                ENDDO
                IF (SAME_BLOCK) THEN
                  PID_WORK(J) = 0
                  N_TOT = N_TOT + 1
                  OLD_FACTOR = OLD_FACTOR/N_TOT
                ENDIF
              ENDIF
            ENDDO
          ENDDO
        ENDIF
        TOTAL_FACTOR = TOTAL_FACTOR*OLD_FACTOR
      ENDDO
      MG5_1_BROKEN_SYM = TOTAL_FACTOR
      RETURN
      END



      INTEGER FUNCTION MG5_1_GET_FLAVOR_INDEX(FLAVOR)
C     Resolve an external FLAVOR(NEXTERNAL) group-position vector to
C      its
C     1-based index in the allowed-flavor table (the same ordering
C      used by
C     compute_flavor_masks / the FLAV_TABLE mask columns). A resolved
C      flavor
C     returns an index in [1,NFLAV]; a flavor that is NOT in the table
C      (i.e.
C     not a physical/allowed combination, so its matrix element is
C      zero)
C     returns 0. Callers MUST treat the 0 sentinel as "not a valid
C      flavor"
C     and short-circuit to a zero result before indexing the 1..NFLAV
C     GOODHEL/NTRY arrays or FLAV_TABLE (there is no reserved 0 slot).
C     Computed once per phase-space point and then threaded down to
C     MATRIX/GET_AMP and the good-helicity filter.
      INCLUDE 'nexternal.inc'
      INTEGER NFLAV
      PARAMETER (NFLAV=1)
      INTEGER FLAVOR(NEXTERNAL)
CF2PY INTENT(IN) :: FLAVOR(NEXTERNAL)
CF2PY INTENT(OUT) :: MG5_1_GET_FLAVOR_INDEX
      INTEGER FI_I, FI_J
      LOGICAL FI_MATCH
      INTEGER FI_TABLE(NEXTERNAL, NFLAV)
      DATA FI_TABLE /1, 1, 1, 1/
C     0 sentinel for an unresolved (not-in-table) flavor (see above).
      MG5_1_GET_FLAVOR_INDEX = 0
      DO FI_I = 1, NFLAV
        FI_MATCH = .TRUE.
        DO FI_J = 1, NEXTERNAL
          IF (FLAVOR(FI_J) .NE. FI_TABLE(FI_J, FI_I)) THEN
            FI_MATCH = .FALSE.
            EXIT
          ENDIF
        ENDDO
        IF (FI_MATCH) THEN
          MG5_1_GET_FLAVOR_INDEX = FI_I
          RETURN
        ENDIF
      ENDDO
      RETURN
      END



      SUBROUTINE MG5_1_GET_FLAVOR(FLAV_IDX, FLAVOR)
C     Reverse of GET_FLAVOR_INDEX: fill FLAVOR(NEXTERNAL) with the
C      per-leg
C     group-position vector of the FLAV_IDX-th allowed flavor (same
C      table /
C     ordering). FLAV_IDX is expected in [1,NFLAV] (GET_FLAVOR_INDEX
C      never
C     returns 0); the bounds guard below is purely defensive and maps
C      any
C     out-of-range value to the first flavor. Used by the outer entry
C      points
C     (SMATRIX, ...) which receive FLAV_IDX but still need the FLAVOR
C      array
C     (e.g. for BROKEN_SYM).
      INCLUDE 'nexternal.inc'
      INTEGER NFLAV
      PARAMETER (NFLAV=1)
      INTEGER FLAV_IDX
      INTEGER FLAVOR(NEXTERNAL)
CF2PY INTENT(IN) :: FLAV_IDX
CF2PY INTENT(OUT) :: FLAVOR(NEXTERNAL)
      INTEGER FA_I, FA_USE
      INTEGER FA_TABLE(NEXTERNAL, NFLAV)
      DATA FA_TABLE /1, 1, 1, 1/
      FA_USE = FLAV_IDX
      IF (FA_USE .LT. 1 .OR. FA_USE .GT. NFLAV) FA_USE = 1
      DO FA_I = 1, NEXTERNAL
        FLAVOR(FA_I) = FA_TABLE(FA_I, FA_USE)
      ENDDO
      RETURN
      END




C     Set of functions to handle the array indices of the split orders


      INTEGER FUNCTION MG5_1_SQSOINDEX(ORDERINDEXA, ORDERINDEXB)
C     
C     This functions plays the role of the interference matrix. It can
C      be hardcoded or 
C     made more elegant using hashtables if its execution speed ever
C      becomes a relevant
C     factor. From two split order indices, it return the
C      corresponding index in the squared 
C     order canonical ordering.
C     
C     CONSTANTS
C     

      INTEGER    NSO, NSQUAREDSO, NAMPSO
      PARAMETER (NSO=1, NSQUAREDSO=1, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER ORDERINDEXA, ORDERINDEXB
C     
C     LOCAL VARIABLES
C     
      INTEGER I, SQORDERS(NSO)
      INTEGER AMPSPLITORDERS(NAMPSO,NSO)
      DATA (AMPSPLITORDERS(  1,I),I=  1,  1) /    2/
      COMMON/MG5_1_AMPSPLITORDERS/AMPSPLITORDERS
C     
C     FUNCTION
C     
      INTEGER MG5_1_SOINDEX_FOR_SQUARED_ORDERS
C     
C     BEGIN CODE
C     
      DO I=1,NSO
        SQORDERS(I)=AMPSPLITORDERS(ORDERINDEXA,I)
     $   +AMPSPLITORDERS(ORDERINDEXB,I)
      ENDDO
      MG5_1_SQSOINDEX=MG5_1_SOINDEX_FOR_SQUARED_ORDERS(SQORDERS)
      END

      INTEGER FUNCTION MG5_1_SOINDEX_FOR_SQUARED_ORDERS(ORDERS)
C     
C     This functions returns the integer index identifying the squared
C      split orders list passed in argument which corresponds to the
C      values of the following list of couplings (and in this order).
C     ['QCD']
C     
C     CONSTANTS
C     
      INTEGER    NSO, NSQSO, NAMPSO
      PARAMETER (NSO=1, NSQSO=1, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I,J
      INTEGER SQSPLITORDERS(NSQSO,NSO)
      DATA (SQSPLITORDERS(  1,I),I=  1,  1) /    4/
      COMMON/MG5_1_SQPLITORDERS/SQPLITORDERS
C     
C     BEGIN CODE
C     
      DO I=1,NSQSO
        DO J=1,NSO
          IF (ORDERS(J).NE.SQSPLITORDERS(I,J)) GOTO 1009
        ENDDO
        MG5_1_SOINDEX_FOR_SQUARED_ORDERS = I
        RETURN
 1009   CONTINUE
      ENDDO

      WRITE(*,*) 'ERROR:: Stopping in function'
      WRITE(*,*) 'MG5_1_SOINDEX_FOR_SQUARED_ORDERS'
      WRITE(*,*) 'Could not find squared orders ',(ORDERS(I),I=1,NSO)
      STOP

      END

      SUBROUTINE MG5_1_GET_NSQSO_BORN(NSQSO)
C     
C     Simple subroutine returning the number of squared split order
C     contributions returned when calling smatrix_split_orders 
C     

      INTEGER    NSQUAREDSO
      PARAMETER  (NSQUAREDSO=1)

      INTEGER NSQSO

      NSQSO=NSQUAREDSO

      END

C     This is the inverse subroutine of SOINDEX_FOR_SQUARED_ORDERS.
C      Not directly useful, but provided nonetheless.
      SUBROUTINE MG5_1_GET_SQUARED_ORDERS_FOR_SOINDEX(SOINDEX,ORDERS)
C     
C     This functions returns the orders identified by the squared
C      split order index in argument. Order values correspond to
C      following list of couplings (and in this order):
C     ['QCD']
C     
C     CONSTANTS
C     
      INTEGER    NSO, NSQSO
      PARAMETER (NSO=1, NSQSO=1)
C     
C     ARGUMENTS
C     
      INTEGER SOINDEX, ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I
      INTEGER SQPLITORDERS(NSQSO,NSO)
      COMMON/MG5_1_SQPLITORDERS/SQPLITORDERS
C     
C     BEGIN CODE
C     
      IF (SOINDEX.GT.0.AND.SOINDEX.LE.NSQSO) THEN
        DO I=1,NSO
          ORDERS(I) =  SQPLITORDERS(SOINDEX,I)
        ENDDO
        RETURN
      ENDIF

      WRITE(*,*) 'ERROR:: Stopping function'
     $ //' MG5_1_GET_SQUARED_ORDERS_FOR_SOINDEX'
      WRITE(*,*) 'Could not find squared orders index ',SOINDEX
      STOP

      END SUBROUTINE

C     This is the inverse subroutine of getting amplitude SO orders.
C      Not directly useful, but provided nonetheless.
      SUBROUTINE MG5_1_GET_ORDERS_FOR_AMPSOINDEX(SOINDEX,ORDERS)
C     
C     This functions returns the orders identified by the split order
C      index in argument. Order values correspond to following list of
C      couplings (and in this order):
C     ['QCD']
C     
C     CONSTANTS
C     
      INTEGER    NSO, NAMPSO
      PARAMETER (NSO=1, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER SOINDEX, ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I
      INTEGER AMPSPLITORDERS(NAMPSO,NSO)
      COMMON/MG5_1_AMPSPLITORDERS/AMPSPLITORDERS
C     
C     BEGIN CODE
C     
      IF (SOINDEX.GT.0.AND.SOINDEX.LE.NAMPSO) THEN
        DO I=1,NSO
          ORDERS(I) =  AMPSPLITORDERS(SOINDEX,I)
        ENDDO
        RETURN
      ENDIF

      WRITE(*,*) 'ERROR:: Stopping function'
     $ //' MG5_1_GET_ORDERS_FOR_AMPSOINDEX'
      WRITE(*,*) 'Could not find amplitude split orders index ',SOINDEX
      STOP

      END SUBROUTINE

C     This function is not directly useful, but included for
C      completeness
      INTEGER FUNCTION MG5_1_SOINDEX_FOR_AMPORDERS(ORDERS)
C     
C     This functions returns the integer index identifying the
C      amplitude split orders passed in argument which correspond to
C      the values of the following list of couplings (and in this
C      order):
C     ['QCD']
C     
C     CONSTANTS
C     
      INTEGER    NSO, NAMPSO
      PARAMETER (NSO=1, NAMPSO=1)
C     
C     ARGUMENTS
C     
      INTEGER ORDERS(NSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I,J
      INTEGER AMPSPLITORDERS(NAMPSO,NSO)
      COMMON/MG5_1_AMPSPLITORDERS/AMPSPLITORDERS
C     
C     BEGIN CODE
C     
      DO I=1,NAMPSO
        DO J=1,NSO
          IF (ORDERS(J).NE.AMPSPLITORDERS(I,J)) GOTO 1009
        ENDDO
        MG5_1_SOINDEX_FOR_AMPORDERS = I
        RETURN
 1009   CONTINUE
      ENDDO

      WRITE(*,*) 'ERROR:: Stopping function'
     $ //' MG5_1_SOINDEX_FOR_AMPORDERS'
      WRITE(*,*) 'Could not find squared orders ',(ORDERS(I),I=1,NSO)
      STOP

      END

