#pragma once

#include "device.hpp"
#include "gpu_abstraction.cuh"
#include "madspace/driver/random.hpp"
#include "tensor.cuh" // MAX_THREADS_PER_BLOCK, THREADS_MULTIPLE

#include <algorithm>
#include <array>
#include <cstdint>
#include <stdexcept>
#include <utility>

namespace madspace {
namespace gpu {

// One MIXMAX substream per DerivedSeed stream index; the bank covers all of them so
// every RNG-consuming instruction draws from its own non-overlapping substream.
constexpr std::size_t RNG_ENGINE_COUNT = 1 << 12;

// The low SEED_STREAM_BITS of the effective 128-bit seed are the per-engine stream index
// (engine i uses shared_seed | i); the rest is shared across the whole bank. DerivedSeed
// reserves exactly these bits (max_stream_count == 1 << 16).
constexpr int SEED_STREAM_BITS = 16;
constexpr std::size_t Q_TABLE_SIZE = std::size_t(1) << SEED_STREAM_BITS;
static_assert(
    RNG_ENGINE_COUNT <= Q_TABLE_SIZE, "engine bank exceeds the stream index space"
);

constexpr int MIXMAX_D = mixmax_engine::state_size; // 17
constexpr std::size_t RNG_SEED_BLOCK = 128;

// State vector = MIXMAX vielbein with every set bit of the *shared* seed part
// (bits [SEED_STREAM_BITS, 128)) applied. Identical for all engines, so it is computed
// once on the host; the per-engine bits are finished on the GPU (see Q table below).
struct MixmaxSeedPrefix {
    std::uint64_t state[MIXMAX_D];
};

// bits [64,128) (the global run seed) come from `run_skip` (cached by the caller); apply
// the rest of the shared bits, [SEED_STREAM_BITS, 64), on top
inline MixmaxSeedPrefix
mixmax_seed_prefix(const std::array<std::uint32_t, 4>& seed_parts, const RunSeedSkip& run_skip) {
    MixmaxSeedPrefix prefix;
    for (int i = 0; i < MIXMAX_D; ++i) {
        prefix.state[i] = run_skip.state[i];
    }
    // effective seed word order matches apply_bigskip's IDvec:
    // bits [SEED_STREAM_BITS,32) -> seed_parts[3], bits [32,64) -> seed_parts[2]
    const std::uint32_t words[2] = {seed_parts[3], seed_parts[2]};
    for (int r = SEED_STREAM_BITS; r < 64; ++r) {
        if ((words[r >> 5] >> (r & 31)) & 1u) {
            mixmax_engine::apply_skip_bit(prefix.state, r);
        }
    }
    return prefix;
}

// --- Q table ------------------------------------------------------------------------
//
// Q_i is the product of the skip operators T_r over the set bits r of i (r <
// SEED_STREAM_BITS). Every operator in the algebra generated by the MIXMAX iteration
// matrix A is a degree-<D polynomial in A (Cayley-Hamilton) and that algebra is closed
// under products, so Q_i has a D-coefficient representation just like each T_r, and
//     V_i = Q_i(A) . prefix
// is a single apply_poly per engine. The 2^16 Q_i are seed-independent -> built once.
//
// Build: a subset-product butterfly. Slot i is grown as the *state vector* Q_i(A) e_0
// (reusing apply_skip_bit), then converted to coefficients via the Krylov change of
// basis kr_inv (columns A^j e_0; invertible because e_0 is cyclic for A).

struct MixmaxKrInv {
    std::uint64_t m[MIXMAX_D][MIXMAX_D];
};

inline MixmaxKrInv mixmax_kr_inv() {
    const std::uint64_t P = mixmax_engine::mod_prime;
    auto mul = [&](std::uint64_t a, std::uint64_t b) {
        return mixmax_engine::mod_mul_add(0, a % P, b % P) % P;
    };
    auto sub = [&](std::uint64_t a, std::uint64_t b) {
        return (a % P + (P - b % P)) % P;
    };
    auto inv = [&](std::uint64_t a) {
        std::uint64_t r = 1, base = a % P, e = P - 2;
        while (e) {
            if (e & 1) {
                r = mul(r, base);
            }
            base = mul(base, base);
            e >>= 1;
        }
        return r;
    };

    // kr[.][j] = A^j e_0
    std::uint64_t kr[MIXMAX_D][MIXMAX_D];
    std::uint64_t y[MIXMAX_D] = {0};
    y[0] = 1;
    std::uint64_t sum = 1;
    for (int j = 0; j < MIXMAX_D; ++j) {
        for (int i = 0; i < MIXMAX_D; ++i) {
            kr[i][j] = y[i] % P;
        }
        sum = mixmax_engine::advance_state(y, sum);
    }

    // Gauss-Jordan invert kr mod P
    MixmaxKrInv out;
    std::uint64_t a[MIXMAX_D][MIXMAX_D];
    for (int i = 0; i < MIXMAX_D; ++i) {
        for (int j = 0; j < MIXMAX_D; ++j) {
            a[i][j] = kr[i][j];
            out.m[i][j] = (i == j) ? 1u : 0u;
        }
    }
    for (int c = 0; c < MIXMAX_D; ++c) {
        int piv = -1;
        for (int row = c; row < MIXMAX_D; ++row) {
            if (a[row][c] % P != 0) {
                piv = row;
                break;
            }
        }
        if (piv < 0) {
            throw std::runtime_error("mixmax_kr_inv: singular Krylov matrix");
        }
        if (piv != c) {
            for (int j = 0; j < MIXMAX_D; ++j) {
                std::swap(a[c][j], a[piv][j]);
                std::swap(out.m[c][j], out.m[piv][j]);
            }
        }
        std::uint64_t pinv = inv(a[c][c]);
        for (int j = 0; j < MIXMAX_D; ++j) {
            a[c][j] = mul(a[c][j], pinv);
            out.m[c][j] = mul(out.m[c][j], pinv);
        }
        for (int row = 0; row < MIXMAX_D; ++row) {
            if (row == c) {
                continue;
            }
            std::uint64_t f = a[row][c] % P;
            if (!f) {
                continue;
            }
            for (int j = 0; j < MIXMAX_D; ++j) {
                a[row][j] = sub(a[row][j], mul(f, a[c][j]));
                out.m[row][j] = sub(out.m[row][j], mul(f, out.m[c][j]));
            }
        }
    }
    return out;
}

// butterfly level 0: even slot i -> e_0, odd slot -> T_0(A) e_0
__global__ void kernel_q_seed(std::uint64_t* q) {
    std::size_t n = std::size_t(blockIdx.x) * blockDim.x + threadIdx.x;
    if (n >= Q_TABLE_SIZE / 2) {
        return;
    }
    std::uint64_t y[MIXMAX_D];
    for (int k = 0; k < MIXMAX_D; ++k) {
        y[k] = (k == 0);
    }
    for (int k = 0; k < MIXMAX_D; ++k) {
        q[2 * n * MIXMAX_D + k] = y[k];
    }
    mixmax_engine::apply_skip_bit(y, 0);
    for (int k = 0; k < MIXMAX_D; ++k) {
        q[(2 * n + 1) * MIXMAX_D + k] = y[k];
    }
}

// butterfly level r: slot with bit r set <- T_r(A) applied to its bit-r-clear sibling
__global__ void kernel_q_level(std::uint64_t* q, int r) {
    std::size_t node = std::size_t(blockIdx.x) * blockDim.x + threadIdx.x;
    if (node >= Q_TABLE_SIZE / 2) {
        return;
    }
    const std::size_t bit = std::size_t(1) << r;
    const std::size_t dst = ((node >> r) << (r + 1)) | bit | (node & (bit - 1));
    const std::size_t src = dst ^ bit;
    std::uint64_t y[MIXMAX_D];
    for (int k = 0; k < MIXMAX_D; ++k) {
        y[k] = q[src * MIXMAX_D + k];
    }
    mixmax_engine::apply_skip_bit(y, r);
    for (int k = 0; k < MIXMAX_D; ++k) {
        q[dst * MIXMAX_D + k] = y[k];
    }
}

// Q_i(A) e_0 (state vector) -> coefficients of Q_i in the A-power basis
__global__ void kernel_q_to_coeff(std::uint64_t* q, MixmaxKrInv kr_inv) {
    std::size_t i = std::size_t(blockIdx.x) * blockDim.x + threadIdx.x;
    if (i >= Q_TABLE_SIZE) {
        return;
    }
    std::uint64_t v[MIXMAX_D], out[MIXMAX_D];
    for (int k = 0; k < MIXMAX_D; ++k) {
        v[k] = q[i * MIXMAX_D + k];
    }
    for (int row = 0; row < MIXMAX_D; ++row) {
        std::uint64_t acc = 0;
        for (int col = 0; col < MIXMAX_D; ++col) {
            acc = mixmax_engine::mod_mul_add(acc, kr_inv.m[row][col], v[col]);
        }
        out[row] = acc;
    }
    for (int k = 0; k < MIXMAX_D; ++k) {
        q[i * MIXMAX_D + k] = out[k];
    }
}

// per-(re)seed: V_i = Q_i(A) . prefix, one apply_poly per engine, single launch
__global__ void kernel_rng_seed_apply(
    mixmax_engine* engines,
    std::size_t count,
    const std::uint64_t* q,
    MixmaxSeedPrefix prefix
) {
    std::size_t i = std::size_t(blockIdx.x) * blockDim.x + threadIdx.x;
    if (i >= count) {
        return;
    }
    std::uint64_t y[MIXMAX_D];
    for (int k = 0; k < MIXMAX_D; ++k) {
        y[k] = prefix.state[k];
    }
    mixmax_engine::apply_poly(y, &q[i * MIXMAX_D]);
    std::uint64_t* dst = engines[i].state_data();
    for (int k = 0; k < MIXMAX_D; ++k) {
        dst[k] = y[k];
    }
    engines[i].finalize_skipped_state();
}

inline std::size_t rng_grid_1d(std::size_t n) {
    return (n + RNG_SEED_BLOCK - 1) / RNG_SEED_BLOCK;
}

// Grid geometry for a draw of `count` numbers from the engine bank: split evenly over
// as few threads as cover `count` in ceil(count / RNG_ENGINE_COUNT) draws per thread,
// so the grid never has a large idle remainder.
inline std::pair<std::size_t, std::size_t> rng_grid(std::size_t count) {
    std::size_t draws = (count + RNG_ENGINE_COUNT - 1) / RNG_ENGINE_COUNT;
    std::size_t needed = (count + draws - 1) / draws;
    std::size_t threads = std::min<std::size_t>(
        MAX_THREADS_PER_BLOCK,
        ((needed + THREADS_MULTIPLE - 1) / THREADS_MULTIPLE) * THREADS_MULTIPLE
    );
    std::size_t blocks = (needed + threads - 1) / threads;
    return {blocks, threads};
}

// Bank of RNG_ENGINE_COUNT MIXMAX engines in device memory, seeded from a DerivedSeed.
// Re-seeding only records the seed (and the shared-bit prefix); the actual (re-)seed
// runs lazily on the next run() call, on the main (RNG) stream. The 2^16 composed skip
// operators are built once on first use.
class GpuRandom {
public:
    GpuRandom() {
        void* ptr;
        check_error(gpuMalloc(&ptr, sizeof(mixmax_engine) * RNG_ENGINE_COUNT));
        _engines = static_cast<mixmax_engine*>(ptr);
        check_error(
            gpuMalloc(&ptr, sizeof(std::uint64_t) * Q_TABLE_SIZE * MIXMAX_D)
        );
        _q_table = static_cast<std::uint64_t*>(ptr);
        _run_skip.update(_seed.seed_parts[0], _seed.seed_parts[1]);
        _prefix = mixmax_seed_prefix(_seed.seed_parts, _run_skip);
    }
    ~GpuRandom() {
        if (_engines) {
            gpuFree(_engines);
        }
        if (_q_table) {
            gpuFree(_q_table);
        }
    }
    GpuRandom(const GpuRandom&) = delete;
    GpuRandom& operator=(const GpuRandom&) = delete;
    GpuRandom(GpuRandom&& other) noexcept :
        _engines(other._engines),
        _q_table(other._q_table),
        _seed(other._seed),
        _run_skip(other._run_skip),
        _prefix(other._prefix),
        _pending(other._pending),
        _q_built(other._q_built) {
        other._engines = nullptr;
        other._q_table = nullptr;
    }
    GpuRandom& operator=(GpuRandom&& other) noexcept {
        if (_engines) {
            gpuFree(_engines);
        }
        if (_q_table) {
            gpuFree(_q_table);
        }
        _engines = other._engines;
        _q_table = other._q_table;
        _seed = other._seed;
        _run_skip = other._run_skip;
        _prefix = other._prefix;
        _pending = other._pending;
        _q_built = other._q_built;
        other._engines = nullptr;
        other._q_table = nullptr;
        return *this;
    }

    void set_seed(DerivedSeed seed) {
        // the engine index is folded into the low SEED_STREAM_BITS of the stream field,
        // so callers must leave the whole reserved stream index unset
        if (seed.seed_parts[3] & (Q_TABLE_SIZE - 1)) {
            throw std::invalid_argument(
                "GpuRandom::set_seed: stream index is reserved for the GPU engine bank"
            );
        }
        _seed = seed;
        _run_skip.update(seed.seed_parts[0], seed.seed_parts[1]);
        _prefix = mixmax_seed_prefix(seed.seed_parts, _run_skip);
        _pending = true;
    }

    void reseed_if_needed(gpuStream_t stream) {
        if (!_q_built) {
            build_q_table(stream);
            _q_built = true;
        }
        if (!_pending) {
            return;
        }
        MixmaxSeedPrefix prefix = _prefix;
        kernel_rng_seed_apply<<<
            rng_grid_1d(RNG_ENGINE_COUNT), RNG_SEED_BLOCK, 0, stream>>>(
            _engines, RNG_ENGINE_COUNT, _q_table, prefix
        );
        check_error();
        _pending = false;
    }

    mixmax_engine* engines() { return _engines; }

private:
    void build_q_table(gpuStream_t stream) {
        MixmaxKrInv kr_inv = mixmax_kr_inv();
        std::size_t blocks = rng_grid_1d(Q_TABLE_SIZE / 2);
        kernel_q_seed<<<blocks, RNG_SEED_BLOCK, 0, stream>>>(_q_table);
        for (int r = 1; r < SEED_STREAM_BITS; ++r) {
            kernel_q_level<<<blocks, RNG_SEED_BLOCK, 0, stream>>>(_q_table, r);
        }
        kernel_q_to_coeff<<<
            rng_grid_1d(Q_TABLE_SIZE), RNG_SEED_BLOCK, 0, stream>>>(_q_table, kr_inv);
        check_error();
    }

    mixmax_engine* _engines = nullptr;
    std::uint64_t* _q_table = nullptr;
    DerivedSeed _seed;
    RunSeedSkip _run_skip;
    MixmaxSeedPrefix _prefix;
    bool _pending = true;
    bool _q_built = false;
};

template <typename F, typename... Args>
void launch_rng_kernel(
    F kernel, std::size_t count, GpuRandom& rng, gpuStream_t stream, Args... args
) {
    if (count == 0) {
        return;
    }
    auto [blocks, threads] = rng_grid(count);
    kernel<<<blocks, threads, 0, stream>>>(count, rng.engines(), args...);
    check_error();
}

} // namespace gpu
} // namespace madspace
