C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(3,2,1)
C     
      SUBROUTINE FFV1LP0_3(F1, F2, COUP, M3, W3,V3)
      USE ALOHA_OBJECT
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      TYPE(ALOHA) F1
      INTEGER FLV_INDEX1
      TYPE(ALOHA) F2
      INTEGER FLV_INDEX2
      REAL*8 M3
      TYPE(ALOHA) V3
      REAL*8 W3
      V3%P(:) = +F1%P(:)+F2%P(:)
      V3%W(1)= COUP*(-CI)*(F2 % W(3)*F1 % W(1)+F2 % W(4)*F1 % W(2)+F2
     $  % W(1)*F1 % W(3)+F2 % W(2)*F1 % W(4))
      V3%W(2)= COUP*(-CI)*(-F2 % W(4)*F1 % W(1)-F2 % W(3)*F1 % W(2)+F2
     $  % W(2)*F1 % W(3)+F2 % W(1)*F1 % W(4))
      V3%W(3)= COUP*(-CI)*(-CI*(F2 % W(4)*F1 % W(1)+F2 % W(1)*F1 % W(4)
     $ )+CI*(F2 % W(3)*F1 % W(2)+F2 % W(2)*F1 % W(3)))
      V3%W(4)= COUP*(-CI)*(-F2 % W(3)*F1 % W(1)-F2 % W(2)*F1 % W(4)+F2
     $  % W(4)*F1 % W(2)+F2 % W(1)*F1 % W(3))
      END


