C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(3,2)
C     
      SUBROUTINE GHGHGL_1(S2, V3, COUP, M1, W1,S1)
      USE ALOHA_OBJECT
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      REAL*8 M1
      COMPLEX*16 P2(0:3)
      TYPE(ALOHA) S1
      TYPE(ALOHA) S2
      COMPLEX*16 TMP1
      TYPE(ALOHA) V3
      REAL*8 W1
      P2(:) = S2 % P (:)
      S1%P(:) = +S2%P(:)+V3%P(:)
      TMP1 = (V3 % W(1)*P2(0)-V3 % W(2)*P2(1)-V3 % W(3)*P2(2)-V3 % W(4)
     $ *P2(3))
      S1%W(1)= COUP*CI * TMP1*S2 % W(1)
      END


