C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Metric(1,4)*Metric(2,3) - Metric(1,2)*Metric(3,4)
C     
      SUBROUTINE MP_VVVV3LP0_1(V2, V3, V4, COUP, M1, W1,V1)
      USE ALOHA_OBJECT
      IMPLICIT NONE
      COMPLEX*32 CI
      PARAMETER (CI=(0Q0,1Q0))
      COMPLEX*32 COUP
      REAL*16 M1
      COMPLEX*32 TMP2
      COMPLEX*32 TMP8
      TYPE(MP_ALOHA) V1
      TYPE(MP_ALOHA) V2
      TYPE(MP_ALOHA) V3
      TYPE(MP_ALOHA) V4
      REAL*16 W1
      V1%P(:) = +V2%P(:)+V3%P(:)+V4%P(:)
      TMP2 = (V3 % W(1)*V4 % W(1)-V3 % W(2)*V4 % W(2)-V3 % W(3)*V4 %
     $  W(3)-V3 % W(4)*V4 % W(4))
      TMP8 = (V2 % W(1)*V3 % W(1)-V2 % W(2)*V3 % W(2)-V2 % W(3)*V3 %
     $  W(3)-V2 % W(4)*V3 % W(4))
      V1%W(1)= COUP*(-CI*(V4 % W(1)*TMP8)+CI*(V2 % W(1)*TMP2))
      V1%W(2)= COUP*(-CI*(V4 % W(2)*TMP8)+CI*(V2 % W(2)*TMP2))
      V1%W(3)= COUP*(-CI*(V4 % W(3)*TMP8)+CI*(V2 % W(3)*TMP2))
      V1%W(4)= COUP*(-CI*(V4 % W(4)*TMP8)+CI*(V2 % W(4)*TMP2))
      END


