C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Metric(1,3)*Metric(2,4) - Metric(1,2)*Metric(3,4)
C     
      SUBROUTINE VVVV4LP0_1(V2, V3, V4, COUP, M1, W1,V1)
      USE ALOHA_OBJECT
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 COUP
      REAL*8 M1
      COMPLEX*16 TMP11
      COMPLEX*16 TMP2
      TYPE(ALOHA) V1
      TYPE(ALOHA) V2
      TYPE(ALOHA) V3
      TYPE(ALOHA) V4
      REAL*8 W1
      V1%P(:) = +V2%P(:)+V3%P(:)+V4%P(:)
      TMP11 = (V2 % W(1)*V4 % W(1)-V2 % W(2)*V4 % W(2)-V2 % W(3)*V4 %
     $  W(3)-V2 % W(4)*V4 % W(4))
      TMP2 = (V3 % W(1)*V4 % W(1)-V3 % W(2)*V4 % W(2)-V3 % W(3)*V4 %
     $  W(3)-V3 % W(4)*V4 % W(4))
      V1%W(1)= COUP*(-CI*(V3 % W(1)*TMP11)+CI*(V2 % W(1)*TMP2))
      V1%W(2)= COUP*(-CI*(V3 % W(2)*TMP11)+CI*(V2 % W(2)*TMP2))
      V1%W(3)= COUP*(-CI*(V3 % W(3)*TMP11)+CI*(V2 % W(3)*TMP2))
      V1%W(4)= COUP*(-CI*(V3 % W(4)*TMP11)+CI*(V2 % W(4)*TMP2))
      END


