      RECURSIVE SUBROUTINE SBORN(P,ANS_SUMMED)
C     
C     Generated by MadGraph7 v. %(version)s, %(date)s
C     By the MadGraph7 Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     
C     Wrapper for SBORN_AMP that does not return amp2 or jamp2,
C      instead storing them as local dummies
C     Return the sum of the split orders which are required in
C      orders.inc (BORN_ORDERS)
C     Also the values needed for the counterterms are stored in the
C      C_BORN_CNT common block
C     
C     
C     Process: _anti_quark _quark > t t~ [ real = QCD QED ] QCD^2<=4
C      QED^2<=2
C     
C     
C     CONSTANTS
C     
      IMPLICIT NONE
      INCLUDE 'nexternal.inc'
      INCLUDE 'orders.inc'
      INCLUDE 'born_nhel.inc'
      INTEGER NAMPSO, NSQAMPSO
      PARAMETER (NAMPSO=2, NSQAMPSO=3)
      INTEGER NGRAPHS
      PARAMETER (NGRAPHS=   3)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL-1)
      DOUBLE PRECISION ANS_SUMMED
C     
C     VARIABLES
C     
      DOUBLE PRECISION AMP2(3), JAMP2(0:2)
      COMPLEX*16 ANS_CNT(2, NSPLITORDERS)
      DOUBLE PRECISION DUMMY_AMP_SPLIT(AMP_SPLIT_SIZE)
      DOUBLE COMPLEX DUMMY_AMP_SPLIT_CNT(AMP_SPLIT_SIZE,2,NSPLITORDERS)
      DOUBLE COMPLEX DUMMY_SAVEAMP(NGRAPHS,MAX_BHEL)
      DOUBLE COMPLEX GLOBAL_ANS_CNT(2,NSPLITORDERS)
      DOUBLE COMPLEX GLOBAL_SAVEAMP(NGRAPHS,MAX_BHEL)
      DOUBLE PRECISION WGT_ME_BORN,WGT_ME_REAL
      COMMON/TO_AMPS/AMP2,JAMP2
      COMMON/C_BORN_CNT/GLOBAL_ANS_CNT
      COMMON/TO_SAVEAMP/GLOBAL_SAVEAMP
      COMMON/C_WGT_ME_TREE/WGT_ME_BORN,WGT_ME_REAL

C     
C     BEGIN CODE
C     
      AMP2(:) = 0D0
      JAMP2(:) = 0D0
      ANS_CNT(:,:) = 0D0

      CALL SBORN_AMP(P,AMP2,JAMP2,DUMMY_AMP_SPLIT,DUMMY_AMP_SPLIT_CNT
     $ ,ANS_SUMMED,ANS_CNT,DUMMY_SAVEAMP)
      AMP_SPLIT(:)=DUMMY_AMP_SPLIT(:)
      AMP_SPLIT_CNT(:,:,:)=DUMMY_AMP_SPLIT_CNT(:,:,:)
      GLOBAL_ANS_CNT(:,:)=ANS_CNT(:,:)
      GLOBAL_SAVEAMP(:,:)=DUMMY_SAVEAMP(:,:)
      WGT_ME_BORN=ANS_SUMMED

      RETURN
      END



      RECURSIVE SUBROUTINE SBORN_AMP(P,AMP2,JAMP2,RET_AMP_SPLIT
     $ ,RET_AMP_SPLIT_CNT,ANS_SUMMED,ANS_CNT,RET_SAVEAMP)
C     
C     Generated by MadGraph7 v. %(version)s, %(date)s
C     By the MadGraph7 Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     
C     Return the sum of the split orders which are required in
C      orders.inc (BORN_ORDERS)
C     Also the values needed for the counterterms are stored in the
C      C_BORN_CNT common block
C     
C     
C     Process: _anti_quark _quark > t t~ [ real = QCD QED ] QCD^2<=4
C      QED^2<=2
C     
C     
C     CONSTANTS
C     
      IMPLICIT NONE
      INCLUDE 'nexternal.inc'
      INCLUDE 'has_ewsudakov.inc'
      INCLUDE 'orders.inc'
      INCLUDE 'born_nhel.inc'
      INTEGER NAMPSO, NSQAMPSO
      PARAMETER (NAMPSO=2, NSQAMPSO=3)
      INTEGER NGRAPHS
      PARAMETER (NGRAPHS=   3)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL-1)
      DOUBLE PRECISION ANS_SUMMED
      DOUBLE PRECISION AMP2B(3), JAMP2B(0:2,0:NAMPSO)
      DOUBLE PRECISION AMP2(3), JAMP2(0:2)
      COMPLEX*16 ANS_CNT(2, NSPLITORDERS)
      DOUBLE PRECISION RET_AMP_SPLIT(AMP_SPLIT_SIZE)
      DOUBLE COMPLEX RET_AMP_SPLIT_CNT(AMP_SPLIT_SIZE,2,NSPLITORDERS)
      DOUBLE COMPLEX RET_SAVEAMP(NGRAPHS,MAX_BHEL)

C     
C     VARIABLES
C     
      INTEGER I,J,K
      INTEGER NORD_INTEGRATED_BORN
      COMPLEX*16 ANS(2,0:NSQAMPSO)
      LOGICAL KEEP_ORDER(NSQAMPSO), KEEP_ORDER_CNT(NSPLITORDERS,
     $  NSQAMPSO), FIRSTTIME
      DATA KEEP_ORDER / NSQAMPSO * .TRUE. /
      LOGICAL KEEP_ORDER_BORN(NSQAMPSO)
      COMMON /C_KEEP_ORDER_B/ KEEP_ORDER_BORN
      COMMON /C_KEEP_ORDER_CNT/ KEEP_ORDER_CNT
      INTEGER ORD_SUBTRACT
      DATA FIRSTTIME / .TRUE. /
      INTEGER AMP_ORDERS(NSPLITORDERS)
      DOUBLE PRECISION TINY
      PARAMETER (TINY = 1D-12)
      DOUBLE PRECISION MAX_VAL

      LOGICAL SPLIT_TYPE_USED(NSPLITORDERS)
      COMMON/TO_SPLIT_TYPE_USED/SPLIT_TYPE_USED
C     
C     FUNCTIONS
C     
      INTEGER GETORDPOWFROMINDEX_B
      INTEGER ORDERS_TO_AMP_SPLIT_POS
C     
C     BEGIN CODE
C     
C     look for orders which match the born order constraint 

      AMP2B(:) = 0.0
      JAMP2B(:,:) = 0.0
      JAMP2B(0,0) = 2

      IF (FIRSTTIME) THEN
        CALL FIRSTTIME_SETUP(FIRSTTIME)
      ENDIF

      CALL SBORN_SPLITORDERS(P,AMP2B,JAMP2B,ANS,RET_SAVEAMP)

C     the born to be integrated
      ANS_SUMMED = 0D0
      MAX_VAL = 0D0

C     reset the amp_split array
      RET_AMP_SPLIT(1:AMP_SPLIT_SIZE) = 0D0
      RET_AMP_SPLIT_CNT(1:AMP_SPLIT_SIZE,1:2,1:NSPLITORDERS) =
     $  DCMPLX(0D0,0D0)

      DO I = 1, NSQAMPSO
        MAX_VAL = MAX(MAX_VAL, ABS(ANS(1,I)))
      ENDDO
      DO I = 1, NSQAMPSO
        IF (KEEP_ORDER(I)) THEN
          ANS_SUMMED = ANS_SUMMED + ANS(1,I)
C         keep track of the separate pieces correspoinding to
C          different coupling combinations
          DO J = 1, NSPLITORDERS
            AMP_ORDERS(J) = GETORDPOWFROMINDEX_B(J, I)
          ENDDO
          IF(ABS(ANS(1,I)).GT.MAX_VAL*TINY)
     $      RET_AMP_SPLIT(ORDERS_TO_AMP_SPLIT_POS(AMP_ORDERS)) = ANS(1
     $     ,I)
        ENDIF
      ENDDO
C     this is to avoid fake non-zero contributions 
      IF (ABS(ANS_SUMMED).LT.MAX_VAL*TINY) ANS_SUMMED=0D0

C     fill the amp2 and jamp2 arrays
      AMP2(1:NGRAPHS)=AMP2B(1:NGRAPHS)  ! amp2 just needs to be copyed

      DO I = 0, INT(JAMP2B(0,0))
        JAMP2(I)=0D0
        DO J = 1, NAMPSO
C         here sum all, this may be refined later
          JAMP2(I)=JAMP2(I)+JAMP2B(I,J)
        ENDDO
      ENDDO


C     quantities for the counterterms
      DO J = 1, NSPLITORDERS
        ANS_CNT(1:2,J) = (0D0, 0D0)
        IF (.NOT.SPLIT_TYPE_USED(J)) CYCLE
        DO I = 1, NSQAMPSO
          IF (KEEP_ORDER_CNT(J,I)) THEN
            ANS_CNT(1,J) = ANS_CNT(1,J) + ANS(1,I)
            ANS_CNT(2,J) = ANS_CNT(2,J) + ANS(2,I)
C           keep track of the separate pieces also for counterterms
            DO K = 1, NSPLITORDERS
              AMP_ORDERS(K) = GETORDPOWFROMINDEX_B(K, I)
C             take into account the fact that the counterterm for a
C              given split order
C             will be multiplied by the corresponding squared coupling
              IF (K.EQ.J) AMP_ORDERS(K) = AMP_ORDERS(K) + 2
            ENDDO
C           this is to avoid fake non-zero contributions 
            IF (ABS(ANS(1,I)).GT.MAX_VAL*TINY)
     $        RET_AMP_SPLIT_CNT(ORDERS_TO_AMP_SPLIT_POS(AMP_ORDERS),1
     $       ,J) = ANS(1,I)
            IF (ABS(ANS(2,I)).GT.MAX_VAL*TINY)
     $        RET_AMP_SPLIT_CNT(ORDERS_TO_AMP_SPLIT_POS(AMP_ORDERS),2
     $       ,J) = ANS(2,I)
          ENDIF
        ENDDO
C       this is to avoid fake non-zero contributions 
        IF (ABS(ANS_CNT(1,J)).LT.MAX_VAL*TINY) ANS_CNT(1,J)=(0D0,0D0)
        IF (ABS(ANS_CNT(2,J)).LT.MAX_VAL*TINY) ANS_CNT(2,J)=(0D0,0D0)
      ENDDO

C     AMP_SPLIT(:) = RET_AMP_SPLIT(:)
C     AMP_SPLIT_CNT(:,:,:) = RET_AMP_SPLIT_CNT(:,:,:)

 999  RETURN
      END


      RECURSIVE SUBROUTINE SBORN_AMP_VEC(P,AMP2,JAMP2,RET_AMP_SPLIT
     $ ,RET_AMP_SPLIT_CNT,ANS_SUMMED,ANS_CNT,RET_SAVEAMP,IVEC,IIND
     $ ,IFKS,FLAV_IDX)
C     
C     Generated by MadGraph7 v. %(version)s, %(date)s
C     By the MadGraph7 Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     
C     Return the sum of the split orders which are required in
C      orders.inc (BORN_ORDERS)
C     Also the values needed for the counterterms are stored in the
C      C_BORN_CNT common block
C     
C     
C     Process: _anti_quark _quark > t t~ [ real = QCD QED ] QCD^2<=4
C      QED^2<=2
C     
C     
C     CONSTANTS
C     
      IMPLICIT NONE
      INCLUDE 'nexternal.inc'
      INCLUDE 'has_ewsudakov.inc'
      INCLUDE 'orders.inc'
      INCLUDE 'born_nhel.inc'
      INTEGER NAMPSO, NSQAMPSO
      PARAMETER (NAMPSO=2, NSQAMPSO=3)
      INTEGER NGRAPHS
      PARAMETER (NGRAPHS=   3)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL-1)
      DOUBLE PRECISION ANS_SUMMED
      DOUBLE PRECISION AMP2B(3), JAMP2B(0:2,0:NAMPSO)
      DOUBLE PRECISION AMP2(3), JAMP2(0:2)
      COMPLEX*16 ANS_CNT(2, NSPLITORDERS)
      DOUBLE PRECISION RET_AMP_SPLIT(AMP_SPLIT_SIZE)
      DOUBLE COMPLEX RET_AMP_SPLIT_CNT(AMP_SPLIT_SIZE,2,NSPLITORDERS)
      DOUBLE COMPLEX RET_SAVEAMP(NGRAPHS,MAX_BHEL)
      INTEGER IVEC, IFKS, IIND, FLAV_IDX

C     
C     VARIABLES
C     
      INTEGER I,J,K
      INTEGER NORD_INTEGRATED_BORN
      COMPLEX*16 ANS(2,0:NSQAMPSO)
      LOGICAL KEEP_ORDER(NSQAMPSO), KEEP_ORDER_CNT(NSPLITORDERS,
     $  NSQAMPSO), FIRSTTIME
      DATA KEEP_ORDER / NSQAMPSO * .TRUE. /
      LOGICAL KEEP_ORDER_BORN(NSQAMPSO)
      COMMON /C_KEEP_ORDER_B/ KEEP_ORDER_BORN
      COMMON /C_KEEP_ORDER_CNT/ KEEP_ORDER_CNT
      INTEGER ORD_SUBTRACT
      DATA FIRSTTIME / .TRUE. /
      INTEGER AMP_ORDERS(NSPLITORDERS)
      DOUBLE PRECISION TINY
      PARAMETER (TINY = 1D-12)
      DOUBLE PRECISION MAX_VAL

      LOGICAL SPLIT_TYPE_USED(NSPLITORDERS)
      COMMON/TO_SPLIT_TYPE_USED/SPLIT_TYPE_USED
C     
C     FUNCTIONS
C     
      INTEGER GETORDPOWFROMINDEX_B
      INTEGER ORDERS_TO_AMP_SPLIT_POS
C     
C     BEGIN CODE
C     
C     look for orders which match the born order constraint 

      AMP2B(:) = 0.0
      JAMP2B(:,:) = 0.0
      JAMP2B(0,0) = 2

C     if (firsttime) then
C     call FIRSTTIME_SETUP(firsttime)
C     endif

      CALL SBORN_SPLITORDERS_VEC(P,AMP2B,JAMP2B,ANS,RET_SAVEAMP,IVEC
     $ ,IIND,IFKS,FLAV_IDX)

C     the born to be integrated
      ANS_SUMMED = 0D0
      MAX_VAL = 0D0

C     reset the amp_split array
      RET_AMP_SPLIT(1:AMP_SPLIT_SIZE) = 0D0
      RET_AMP_SPLIT_CNT(1:AMP_SPLIT_SIZE,1:2,1:NSPLITORDERS) =
     $  DCMPLX(0D0,0D0)

      DO I = 1, NSQAMPSO
        MAX_VAL = MAX(MAX_VAL, ABS(ANS(1,I)))
      ENDDO
      DO I = 1, NSQAMPSO
        IF (KEEP_ORDER(I)) THEN
          ANS_SUMMED = ANS_SUMMED + ANS(1,I)
C         keep track of the separate pieces correspoinding to
C          different coupling combinations
          DO J = 1, NSPLITORDERS
            AMP_ORDERS(J) = GETORDPOWFROMINDEX_B(J, I)
          ENDDO
          IF(ABS(ANS(1,I)).GT.MAX_VAL*TINY)
     $      RET_AMP_SPLIT(ORDERS_TO_AMP_SPLIT_POS(AMP_ORDERS)) = ANS(1
     $     ,I)
        ENDIF
      ENDDO
C     this is to avoid fake non-zero contributions 
      IF (ABS(ANS_SUMMED).LT.MAX_VAL*TINY) ANS_SUMMED=0D0

C     fill the amp2 and jamp2 arrays
      AMP2(1:NGRAPHS)=AMP2B(1:NGRAPHS)  ! amp2 just needs to be copyed

      DO I = 0, INT(JAMP2B(0,0))
        JAMP2(I)=0D0
        DO J = 1, NAMPSO
C         here sum all, this may be refined later
          JAMP2(I)=JAMP2(I)+JAMP2B(I,J)
        ENDDO
      ENDDO


C     quantities for the counterterms
      DO J = 1, NSPLITORDERS
        ANS_CNT(1:2,J) = (0D0, 0D0)
        IF (.NOT.SPLIT_TYPE_USED(J)) CYCLE
        DO I = 1, NSQAMPSO
          IF (KEEP_ORDER_CNT(J,I)) THEN
            ANS_CNT(1,J) = ANS_CNT(1,J) + ANS(1,I)
            ANS_CNT(2,J) = ANS_CNT(2,J) + ANS(2,I)
C           keep track of the separate pieces also for counterterms
            DO K = 1, NSPLITORDERS
              AMP_ORDERS(K) = GETORDPOWFROMINDEX_B(K, I)
C             take into account the fact that the counterterm for a
C              given split order
C             will be multiplied by the corresponding squared coupling
              IF (K.EQ.J) AMP_ORDERS(K) = AMP_ORDERS(K) + 2
            ENDDO
C           this is to avoid fake non-zero contributions 
            IF (ABS(ANS(1,I)).GT.MAX_VAL*TINY)
     $        RET_AMP_SPLIT_CNT(ORDERS_TO_AMP_SPLIT_POS(AMP_ORDERS),1
     $       ,J) = ANS(1,I)
            IF (ABS(ANS(2,I)).GT.MAX_VAL*TINY)
     $        RET_AMP_SPLIT_CNT(ORDERS_TO_AMP_SPLIT_POS(AMP_ORDERS),2
     $       ,J) = ANS(2,I)
          ENDIF
        ENDDO
C       this is to avoid fake non-zero contributions 
        IF (ABS(ANS_CNT(1,J)).LT.MAX_VAL*TINY) ANS_CNT(1,J)=(0D0,0D0)
        IF (ABS(ANS_CNT(2,J)).LT.MAX_VAL*TINY) ANS_CNT(2,J)=(0D0,0D0)
      ENDDO

C     AMP_SPLIT(:) = RET_AMP_SPLIT(:)
C     AMP_SPLIT_CNT(:,:,:) = RET_AMP_SPLIT_CNT(:,:,:)

 999  RETURN
      END



      RECURSIVE SUBROUTINE FIRSTTIME_SETUP(FIRSTTIME)
C     
C     CONSTANTS
C     
      IMPLICIT NONE
      INCLUDE 'nexternal.inc'
      INCLUDE 'has_ewsudakov.inc'
      INCLUDE 'orders.inc'
      INCLUDE 'born_nhel.inc'
      INTEGER NAMPSO, NSQAMPSO
      PARAMETER (NAMPSO=2, NSQAMPSO=3)
C     
C     ARGUMENTS 
C     

C     
C     VARIABLES
C     
      INTEGER I,J,K
      INTEGER NORD_INTEGRATED_BORN
      LOGICAL KEEP_ORDER(NSQAMPSO), KEEP_ORDER_CNT(NSPLITORDERS,
     $  NSQAMPSO), FIRSTTIME
      DATA KEEP_ORDER / NSQAMPSO * .TRUE. /
      LOGICAL KEEP_ORDER_BORN(NSQAMPSO)
      COMMON /C_KEEP_ORDER_B/ KEEP_ORDER_BORN
      COMMON /C_KEEP_ORDER_CNT/ KEEP_ORDER_CNT
      INTEGER ORD_SUBTRACT

C     
C     FUNCTIONS
C     
      INTEGER GETORDPOWFROMINDEX_B
C     
C     BEGIN CODE
C     


      DO I = 1, NSQAMPSO
C       this is for the orders of the born to integrate
        DO J = 1, NSPLITORDERS
          IF(GETORDPOWFROMINDEX_B(J, I) .GT. BORN_ORDERS(J)) THEN
            KEEP_ORDER(I) = .FALSE.
            EXIT
          ENDIF
        ENDDO
C       keep_order_born = keep_order

C       this is for the orders of the counterterms
        DO J = 1, NSPLITORDERS
          KEEP_ORDER_CNT(J,I) = .TRUE.
          DO K = 1, NSPLITORDERS
            IF (J.EQ.K) THEN
              ORD_SUBTRACT=2
            ELSE
              ORD_SUBTRACT=0
            ENDIF
            IF(GETORDPOWFROMINDEX_B(K, I) .GT. NLO_ORDERS(K)
     $       -ORD_SUBTRACT) THEN
              KEEP_ORDER_CNT(J,I) = .FALSE.
              EXIT
            ENDIF
          ENDDO
        ENDDO

        NORD_INTEGRATED_BORN = 0
        IF (KEEP_ORDER(I)) THEN
          NORD_INTEGRATED_BORN = NORD_INTEGRATED_BORN + 1
C         write(*,*) 'BORN: keeping split order ', i
C         else
C         write(*,*) 'BORN: not keeping split order ', i
        ENDIF
      ENDDO
      KEEP_ORDER_BORN = KEEP_ORDER

C     check that, if one include the sudakov corrections, there is at
C      most one contribution to be integrated at LO
      IF (HAS_EWSUDAKOV.AND.NORD_INTEGRATED_BORN.GT.1) THEN
        WRITE(*,*) 'ERROR in born.f, cannot compute Sudakov EW'
     $   //' corrections with more than one Born coupling combination'
     $   //' to be integrated.Found', NORD_INTEGRATED_BORN
        STOP 1
      ENDIF

      DO J = 1, NSPLITORDERS
        WRITE(*,*) 'counterterm S.O', J, ORDERNAMES(J)
        DO I = 1, NSQAMPSO
          IF (KEEP_ORDER_CNT(J,I)) THEN
            WRITE(*,*) 'BORN: keeping split order', I
          ELSE
            WRITE(*,*) 'BORN: not keeping split order', I
          ENDIF
        ENDDO
      ENDDO

      FIRSTTIME = .FALSE.

      END



      RECURSIVE SUBROUTINE SBORN_ONEHEL(P,NHEL,HELL,ANS_SUMMED
     $ ,RET_SAVEAMP)
C     
C     Generated by MadGraph7 v. %(version)s, %(date)s
C     By the MadGraph7 Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     
C     Return the sum of the split orders which are required in
C      orders.inc (BORN_ORDERS)
C     It works for a single set of helicities, passed by NHEL
C     Also the values needed for the counterterms are stored in the
C      C_BORN_CNT common block
C     
C     
C     Process: _anti_quark _quark > t t~ [ real = QCD QED ] QCD^2<=4
C      QED^2<=2
C     
C     
C     CONSTANTS
C     
      IMPLICIT NONE
      INCLUDE 'nexternal.inc'
      INTEGER NAMPSO, NSQAMPSO
      PARAMETER (NAMPSO=2, NSQAMPSO=3)
      INTEGER NGRAPHS
      PARAMETER (NGRAPHS=   3)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL-1)
      INTEGER NHEL(NEXTERNAL-1)
      INTEGER HELL
      DOUBLE PRECISION ANS_SUMMED
C     
C     VARIABLES
C     
      INTEGER I,J,K,FLAV_IDX
      INCLUDE 'fks_info.inc'
      INCLUDE 'orders.inc'
      INCLUDE 'born_nhel.inc'
      COMPLEX*16 ANS(2,NSQAMPSO)
      REAL*8 BORNS(2,0:NSQAMPSO)
      LOGICAL KEEP_ORDER(NSQAMPSO)
      COMMON /C_KEEP_ORDER_B/ KEEP_ORDER

C     
C     DUMMY AMPS FOR LOCALITY
C     
      DOUBLE PRECISION AMP2(3), JAMP2(0:2,0:NAMPSO)
      DOUBLE COMPLEX RET_SAVEAMP(3,MAX_BHEL)

      LOGICAL KEEP_ORDER_CNT(NSPLITORDERS, NSQAMPSO)
      COMMON /C_KEEP_ORDER_CNT/ KEEP_ORDER_CNT

      INTEGER AMP_ORDERS(NSPLITORDERS)
      DOUBLE PRECISION TINY
      PARAMETER (TINY = 1D-12)
      DOUBLE PRECISION MAX_VAL
      INCLUDE 'ewsudakov_haslo.inc'
      DOUBLE COMPLEX AMP_SPLIT_EWSUD(AMP_SPLIT_SIZE)
      COMMON /TO_AMP_SPLIT_EWSUD/ AMP_SPLIT_EWSUD
      DOUBLE COMPLEX AMP_SPLIT_EWSUD_LO2(AMP_SPLIT_SIZE)
      COMMON /TO_AMP_SPLIT_EWSUD_LO2/ AMP_SPLIT_EWSUD_LO2
      INTEGER IDEN
      INTEGER IDEN_VALUES(48)
      DATA IDEN_VALUES /36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36
     $ , 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36,
     $  36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36
     $ , 36, 36, 36, 36, 36/
      INTEGER NFKSPROCESS
      COMMON/C_NFKSPROCESS/NFKSPROCESS
C     
C     FUNCTIONS
C     
      INTEGER GETORDPOWFROMINDEX_B
      INTEGER ORDERS_TO_AMP_SPLIT_POS
C     
C     stuff for the LO2
      INTEGER LO2_ORDERS(NSPLITORDERS)
      LOGICAL ORDERS_EQUAL
      EXTERNAL ORDERS_EQUAL
C     
C     BEGIN CODE
C     
C     look for orders which match the born order constraint 

      AMP2(:) = 0.0
      JAMP2(:,:) = 0.0
      JAMP2(0,0) = 2

      IDEN=IDEN_VALUES(NFKSPROCESS)
      FLAV_IDX=BORN_FLAVOR_INDEX_D(NFKSPROCESS)
      CALL BORN(P,NHEL,HELL,FLAV_IDX,.TRUE.,AMP2,JAMP2,ANS,BORNS,
     $     ret_saveamp)

      ANS_SUMMED = 0D0
      MAX_VAL = 0D0

C     reset the amp_split array
      AMP_SPLIT_EWSUD(1:AMP_SPLIT_SIZE) = DCMPLX(0D0,0D0)
      AMP_SPLIT_EWSUD_LO2(1:AMP_SPLIT_SIZE) = DCMPLX(0D0,0D0)

      DO I = 1, NSQAMPSO
        MAX_VAL = MAX(MAX_VAL, ABS(ANS(1,I)))
      ENDDO

      CALL GET_LO2_ORDERS(LO2_ORDERS)

      DO I = 1, NSQAMPSO
        IF (KEEP_ORDER(I)) THEN
          ANS_SUMMED = ANS_SUMMED + ANS(1,I) / IDEN
          DO J = 1, NSPLITORDERS
            AMP_ORDERS(J) = GETORDPOWFROMINDEX_B(J, I)
          ENDDO
C         amp_split_ewsud(orders_to_amp_split_pos(amp_orders)) =
C          ans(1,I)
          IF(ABS(ANS(1,I)).GT.MAX_VAL*TINY)
     $      AMP_SPLIT_EWSUD(ORDERS_TO_AMP_SPLIT_POS(AMP_ORDERS)) =
     $      ANS(1,I) / IDEN
        ENDIF
C       the following is for the LO2
        IF (HAS_LO2) THEN
          DO J = 1, NSPLITORDERS
            AMP_ORDERS(J) = GETORDPOWFROMINDEX_B(J, I)
          ENDDO
          IF (ORDERS_EQUAL(AMP_ORDERS, LO2_ORDERS)) THEN
            IF(ABS(ANS(1,I)).GT.MAX_VAL*TINY)
     $        AMP_SPLIT_EWSUD_LO2(ORDERS_TO_AMP_SPLIT_POS(AMP_ORDERS))
     $        = ANS(1,I) / IDEN
          ENDIF
        ENDIF
      ENDDO

C     this is to avoid fake non-zero contributions 
      IF (ABS(ANS_SUMMED).LT.MAX_VAL*TINY) ANS_SUMMED=0D0

      RETURN
      END



      RECURSIVE SUBROUTINE SBORN_SPLITORDERS(P1,AMP2,JAMP2,ANS
     $ ,RET_SAVEAMP)
C     
C     Generated by MadGraph7 v. %(version)s, %(date)s
C     By the MadGraph7 Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     RETURNS AMPLITUDE SQUARED SUMMED/AVG OVER COLORS
C     AND HELICITIES
C     FOR THE POINT IN PHASE SPACE P1(0:3,NEXTERNAL-1)
C     
C     Process: _anti_quark _quark > t t~ [ real = QCD QED ] QCD^2<=4
C      QED^2<=2
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INCLUDE 'nexternal.inc'
      INCLUDE 'born_nhel.inc'
      INTEGER     NCOMB
      PARAMETER ( NCOMB=  16 )
      INTEGER NAMPSO, NSQAMPSO
      PARAMETER (NAMPSO=2, NSQAMPSO=3)
      INTEGER    THEL
      PARAMETER (THEL=NCOMB*48)
      INTEGER NGRAPHS
      PARAMETER (NGRAPHS=   3)
C     
C     ARGUMENTS 
C     
      REAL*8 P1(0:3,NEXTERNAL-1)
      DOUBLE PRECISION AMP2(NGRAPHS), JAMP2(0:2,0:NAMPSO)
      COMPLEX*16 ANS(2,0:NSQAMPSO)
C     
C     LOCAL VARIABLES 
C     
      INTEGER IHEL,IDEN,I,J,JJ,GLU_IJ,FLAV_IDX
      INCLUDE 'fks_info.inc'
      REAL*8 BORNS(2,0:NSQAMPSO)
      COMPLEX*16 BORNTILDE
      LOGICAL DO_TRY(48)
      DATA DO_TRY /48*.TRUE./
      COMPLEX*16 T(2,NSQAMPSO)
      INTEGER NHEL(NEXTERNAL-1,NCOMB)
      DATA (NHEL(I,   1),I=1,4) /-1, 1,-1, 1/
      DATA (NHEL(I,   2),I=1,4) /-1, 1,-1,-1/
      DATA (NHEL(I,   3),I=1,4) /-1, 1, 1, 1/
      DATA (NHEL(I,   4),I=1,4) /-1, 1, 1,-1/
      DATA (NHEL(I,   5),I=1,4) /-1,-1,-1, 1/
      DATA (NHEL(I,   6),I=1,4) /-1,-1,-1,-1/
      DATA (NHEL(I,   7),I=1,4) /-1,-1, 1, 1/
      DATA (NHEL(I,   8),I=1,4) /-1,-1, 1,-1/
      DATA (NHEL(I,   9),I=1,4) / 1, 1,-1, 1/
      DATA (NHEL(I,  10),I=1,4) / 1, 1,-1,-1/
      DATA (NHEL(I,  11),I=1,4) / 1, 1, 1, 1/
      DATA (NHEL(I,  12),I=1,4) / 1, 1, 1,-1/
      DATA (NHEL(I,  13),I=1,4) / 1,-1,-1, 1/
      DATA (NHEL(I,  14),I=1,4) / 1,-1,-1,-1/
      DATA (NHEL(I,  15),I=1,4) / 1,-1, 1, 1/
      DATA (NHEL(I,  16),I=1,4) / 1,-1, 1,-1/
      INTEGER IDEN_VALUES(48)
      DATA IDEN_VALUES /36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36
     $ , 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36,
     $  36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36
     $ , 36, 36, 36, 36, 36/
      INTEGER IJ_VALUES(48)
      DATA IJ_VALUES /1, 1, 1, 1, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0,
     $  1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1,
     $  1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2/
C     
C     GLOBAL VARIABLES
C     
      LOGICAL GOODHEL(NCOMB,48)
      COMMON /C_GOODHEL/GOODHEL
      DOUBLE COMPLEX RET_SAVEAMP(NGRAPHS,MAX_BHEL)
      DOUBLE PRECISION SAVEMOM(NEXTERNAL-1,2)
      COMMON/TO_SAVEMOM/SAVEMOM
      INTEGER SKIP(48)
      COMMON/CBORN/SKIP
      LOGICAL CALCULATEDBORN
      COMMON/CCALCULATEDBORN/CALCULATEDBORN
      INTEGER CALCULATED_BORN_FLAVOR
      COMMON/CCALCULATEDBORNFLAVOR/CALCULATED_BORN_FLAVOR
      INTEGER NFKSPROCESS
      COMMON/C_NFKSPROCESS/NFKSPROCESS
      LOGICAL COND_IJ
C     ----------
C     BEGIN CODE
C     ----------
      IDEN=IDEN_VALUES(NFKSPROCESS)
      FLAV_IDX=BORN_FLAVOR_INDEX_D(NFKSPROCESS)
      IF (CALCULATEDBORN .AND.
     $    CALCULATED_BORN_FLAVOR.NE.FLAV_IDX) CALCULATEDBORN=.FALSE.
      GLU_IJ = IJ_VALUES(NFKSPROCESS)
      IF(DO_TRY(NFKSPROCESS)) THEN
        CALL SBORN_SPLITORDERS_NTRY(P1,AMP2,JAMP2,ANS,RET_SAVEAMP
     $   ,DO_TRY(NFKSPROCESS))
      ELSE
        DO JJ=1,NGRAPHS
          AMP2(JJ)=0D0
        ENDDO
        DO I=0,NAMPSO
          DO JJ=1,INT(JAMP2(0,0))
            JAMP2(JJ,I)=0D0
          ENDDO
        ENDDO
        IF (CALCULATEDBORN) THEN
          DO J=1,NEXTERNAL-1
            IF (SAVEMOM(J,1).NE.P1(0,J) .OR. SAVEMOM(J,2).NE.P1(3,J))
     $        THEN
              CALCULATEDBORN=.FALSE.
              WRITE (*,*) 'momenta not the same in Born'
              STOP
            ENDIF
          ENDDO
        ENDIF
        IF (.NOT.CALCULATEDBORN) THEN
          DO J=1,NEXTERNAL-1
            SAVEMOM(J,1)=P1(0,J)
            SAVEMOM(J,2)=P1(3,J)
          ENDDO
          RET_SAVEAMP(:,:) = (0D0,0D0)
        ENDIF
        DO I=0,NSQAMPSO
          ANS(1,I) = 0D0
          ANS(2,I) = 0D0
        ENDDO
        DO IHEL=1,NCOMB
C         the following lines are to avoid segfaults when glu_ij=0
          COND_IJ=SKIP(NFKSPROCESS).EQ.0
          IF (.NOT.COND_IJ) COND_IJ=COND_IJ.OR.NHEL(GLU_IJ,IHEL)
     $     .EQ.NHEL(GLU_IJ,1)
C         if (nhel(glu_ij,ihel).EQ.NHEL(GLU_IJ,1).or.skip(nfksprocess).
C         eq.0) then
          IF (COND_IJ) THEN
            IF ((GOODHEL(IHEL,NFKSPROCESS) .OR. GOODHEL(IHEL
     $       +SKIP(NFKSPROCESS),NFKSPROCESS)) ) THEN
              CALL BORN(P1,NHEL(1,IHEL),IHEL,FLAV_IDX,.FALSE.,AMP2,
     $           JAMP2,T,borns,ret_saveamp)
              DO I=1,NSQAMPSO
                ANS(1,I)=ANS(1,I)+T(1,I)
                ANS(2,I)=ANS(2,I)+T(2,I)
              ENDDO
            ENDIF
          ENDIF
        ENDDO
        DO I=1,NSQAMPSO
          ANS(1,I)=ANS(1,I)/DBLE(IDEN)
          ANS(2,I)=ANS(2,I)/DBLE(IDEN)
          ANS(1,0)=ANS(1,0)+ANS(1,I)
          ANS(2,0)=ANS(2,0)+ANS(2,I)
        ENDDO
        CALCULATEDBORN=.TRUE.
        CALCULATED_BORN_FLAVOR=FLAV_IDX
      ENDIF
      END



      RECURSIVE SUBROUTINE SBORN_SPLITORDERS_VEC(P1,AMP2,JAMP2,ANS
     $ ,RET_SAVEAMP,IVEC,IIND,IFKS,FLAV_IDX)
C     
C     Generated by MadGraph7 v. %(version)s, %(date)s
C     By the MadGraph7 Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     RETURNS AMPLITUDE SQUARED SUMMED/AVG OVER COLORS
C     AND HELICITIES
C     FOR THE POINT IN PHASE SPACE P1(0:3,NEXTERNAL-1)
C     
C     Process: _anti_quark _quark > t t~ [ real = QCD QED ] QCD^2<=4
C      QED^2<=2
C     
      USE DRIVER_VEC
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INCLUDE 'nexternal.inc'
      INCLUDE 'born_nhel.inc'
      INTEGER     NCOMB
      PARAMETER ( NCOMB=  16 )
      INTEGER NAMPSO, NSQAMPSO
      PARAMETER (NAMPSO=2, NSQAMPSO=3)
      INTEGER    THEL
      PARAMETER (THEL=NCOMB*48)
      INTEGER NGRAPHS
      PARAMETER (NGRAPHS=   3)
C     
C     ARGUMENTS 
C     
      REAL*8 P1(0:3,NEXTERNAL-1)
      DOUBLE PRECISION AMP2(NGRAPHS), JAMP2(0:2,0:NAMPSO)
      COMPLEX*16 ANS(2,0:NSQAMPSO)
      INTEGER IVEC,IFKS,IIND,FLAV_IDX
C     
C     LOCAL VARIABLES 
C     
      INTEGER IHEL,IDEN,I,J,JJ,GLU_IJ
      INCLUDE 'fks_info.inc'
      REAL*8 BORNS(2,0:NSQAMPSO)
      COMPLEX*16 BORNTILDE
      LOGICAL DO_TRY(48)
      DATA DO_TRY /48*.TRUE./
      COMPLEX*16 T(2,NSQAMPSO)
      INTEGER NHEL(NEXTERNAL-1,NCOMB)
      DATA (NHEL(I,   1),I=1,4) /-1, 1,-1, 1/
      DATA (NHEL(I,   2),I=1,4) /-1, 1,-1,-1/
      DATA (NHEL(I,   3),I=1,4) /-1, 1, 1, 1/
      DATA (NHEL(I,   4),I=1,4) /-1, 1, 1,-1/
      DATA (NHEL(I,   5),I=1,4) /-1,-1,-1, 1/
      DATA (NHEL(I,   6),I=1,4) /-1,-1,-1,-1/
      DATA (NHEL(I,   7),I=1,4) /-1,-1, 1, 1/
      DATA (NHEL(I,   8),I=1,4) /-1,-1, 1,-1/
      DATA (NHEL(I,   9),I=1,4) / 1, 1,-1, 1/
      DATA (NHEL(I,  10),I=1,4) / 1, 1,-1,-1/
      DATA (NHEL(I,  11),I=1,4) / 1, 1, 1, 1/
      DATA (NHEL(I,  12),I=1,4) / 1, 1, 1,-1/
      DATA (NHEL(I,  13),I=1,4) / 1,-1,-1, 1/
      DATA (NHEL(I,  14),I=1,4) / 1,-1,-1,-1/
      DATA (NHEL(I,  15),I=1,4) / 1,-1, 1, 1/
      DATA (NHEL(I,  16),I=1,4) / 1,-1, 1,-1/
      INTEGER IDEN_VALUES(48)
      DATA IDEN_VALUES /36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36
     $ , 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36,
     $  36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36
     $ , 36, 36, 36, 36, 36/
      INTEGER IJ_VALUES(48)
      DATA IJ_VALUES /1, 1, 1, 1, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0,
     $  1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1,
     $  1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2/
C     
C     GLOBAL VARIABLES
C     
      LOGICAL GOODHEL(NCOMB,48)
      COMMON /C_GOODHEL/GOODHEL
      DOUBLE COMPLEX RET_SAVEAMP(NGRAPHS,MAX_BHEL)
      INTEGER SKIP(48)
      COMMON/CBORN/SKIP
      LOGICAL COND_IJ
C     ----------
C     BEGIN CODE
C     ----------
      IDEN=IDEN_VALUES(IFKS)
      GLU_IJ = IJ_VALUES(IFKS)
C     if(DO_TRY(ifks)) then
C     call SBORN_SPLITORDERS_NTRY_VEC(P1,AMP2,JAMP2,ANS,RET_SAVEAMP,DO_
C     TRY(ifks),IVEC,IFKS,FLAV_IDX)
C     else
      DO JJ=1,NGRAPHS
        AMP2(JJ)=0D0
      ENDDO
      DO I=0,NAMPSO
        DO JJ=1,INT(JAMP2(0,0))
          JAMP2(JJ,I)=0D0
        ENDDO
      ENDDO
      NHEL_VEC(1:NEXTERNAL-1,1:NCOMB,IIND) = NHEL(:,:)
C     if (calculatedBorn) then
C     do j=1,nexternal-1
C     if (savemom(j,1).ne.p1(0,j) .or. savemom(j,2).ne.p1(3,j)) then
C     calculatedBorn=.false.
C     write (*,*) "momenta not the same in Born"
C     stop
C     endif
C     enddo
C     endif
C     if (.not.calculatedBorn) then
C     do j=1,nexternal-1
C     savemom(j,1)=p1(0,j)
C     savemom(j,2)=p1(3,j)
C     enddo
      RET_SAVEAMP(:,:) = (0D0,0D0)
C     endif
      DO I=0,NSQAMPSO
        ANS(1,I) = 0D0
        ANS(2,I) = 0D0
      ENDDO
      DO IHEL=1,NCOMB
C       the following lines are to avoid segfaults when glu_ij=0
        COND_IJ=SKIP(IFKS).EQ.0
        IF (.NOT.COND_IJ) COND_IJ=COND_IJ.OR.NHEL(GLU_IJ,IHEL)
     $   .EQ.NHEL(GLU_IJ,1)
C       if (nhel(glu_ij,ihel).EQ.NHEL(GLU_IJ,1).or.skip(ifks).eq.0)
C        then
        IF (COND_IJ) THEN
          IF ((GOODHEL(IHEL,IFKS) .OR. GOODHEL(IHEL+SKIP(IFKS),IFKS)) )
     $      THEN
            CALL BORN_VEC(P1,NHEL_VEC(1,IHEL,IIND),IHEL,FLAV_IDX,
     $           .false.,AMP2,JAMP2,T,borns,ret_saveamp,ivec,ifks)
            DO I=1,NSQAMPSO
              ANS(1,I)=ANS(1,I)+T(1,I)
              ANS(2,I)=ANS(2,I)+T(2,I)
            ENDDO
          ENDIF
        ENDIF
      ENDDO
      DO I=1,NSQAMPSO
        ANS(1,I)=ANS(1,I)/DBLE(IDEN)
        ANS(2,I)=ANS(2,I)/DBLE(IDEN)
        ANS(1,0)=ANS(1,0)+ANS(1,I)
        ANS(2,0)=ANS(2,0)+ANS(2,I)
      ENDDO
C     calculatedBorn=.true.
C     endif
      END


      RECURSIVE SUBROUTINE SBORN_SPLITORDERS_NTRY(P1,AMP2,JAMP2,ANS
     $ ,RET_SAVEAMP,DO_TRY)
C     
C     Generated by MadGraph7 v. %(version)s, %(date)s
C     By the MadGraph7 Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     RETURNS AMPLITUDE SQUARED SUMMED/AVG OVER COLORS
C     AND HELICITIES
C     FOR THE POINT IN PHASE SPACE P1(0:3,NEXTERNAL-1)
C     
C     Process: _anti_quark _quark > t t~ [ real = QCD QED ] QCD^2<=4
C      QED^2<=2
C     
      USE DRIVER_VEC
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INCLUDE 'nexternal.inc'
      INCLUDE 'born_nhel.inc'
      INTEGER     NCOMB
      PARAMETER ( NCOMB=  16 )
      INTEGER NAMPSO, NSQAMPSO
      PARAMETER (NAMPSO=2, NSQAMPSO=3)
      INTEGER    THEL
      PARAMETER (THEL=NCOMB*48)
      INTEGER NGRAPHS
      PARAMETER (NGRAPHS=   3)
C     
C     ARGUMENTS 
C     
      REAL*8 P1(0:3,NEXTERNAL-1)
      DOUBLE PRECISION AMP2(NGRAPHS), JAMP2(0:2,0:NAMPSO)
      COMPLEX*16 ANS(2,0:NSQAMPSO)
C     
C     LOCAL VARIABLES 
C     
      INTEGER IHEL,IDEN,I,J,JJ,GLU_IJ,FLAV_IDX
      INCLUDE 'fks_info.inc'
      LOGICAL DO_TRY
      REAL*8 BORNS(2,0:NSQAMPSO)
      COMPLEX*16 BORNTILDE
      INTEGER MAX_TRY
      DATA MAX_TRY /20/
      INTEGER NTRY(48)
      DATA NTRY /48*0/
      COMPLEX*16 T(2,NSQAMPSO)
      INTEGER NHEL(NEXTERNAL-1,NCOMB)
      DATA (NHEL(I,   1),I=1,4) /-1, 1,-1, 1/
      DATA (NHEL(I,   2),I=1,4) /-1, 1,-1,-1/
      DATA (NHEL(I,   3),I=1,4) /-1, 1, 1, 1/
      DATA (NHEL(I,   4),I=1,4) /-1, 1, 1,-1/
      DATA (NHEL(I,   5),I=1,4) /-1,-1,-1, 1/
      DATA (NHEL(I,   6),I=1,4) /-1,-1,-1,-1/
      DATA (NHEL(I,   7),I=1,4) /-1,-1, 1, 1/
      DATA (NHEL(I,   8),I=1,4) /-1,-1, 1,-1/
      DATA (NHEL(I,   9),I=1,4) / 1, 1,-1, 1/
      DATA (NHEL(I,  10),I=1,4) / 1, 1,-1,-1/
      DATA (NHEL(I,  11),I=1,4) / 1, 1, 1, 1/
      DATA (NHEL(I,  12),I=1,4) / 1, 1, 1,-1/
      DATA (NHEL(I,  13),I=1,4) / 1,-1,-1, 1/
      DATA (NHEL(I,  14),I=1,4) / 1,-1,-1,-1/
      DATA (NHEL(I,  15),I=1,4) / 1,-1, 1, 1/
      DATA (NHEL(I,  16),I=1,4) / 1,-1, 1,-1/
      INTEGER IDEN_VALUES(48)
      DATA IDEN_VALUES /36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36
     $ , 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36,
     $  36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36
     $ , 36, 36, 36, 36, 36/
      INTEGER IJ_VALUES(48)
      DATA IJ_VALUES /1, 1, 1, 1, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0,
     $  1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1,
     $  1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2/
C     
C     GLOBAL VARIABLES
C     
      LOGICAL GOODHEL(NCOMB,48)
      COMMON /C_GOODHEL/GOODHEL
      DOUBLE COMPLEX RET_SAVEAMP(NGRAPHS,MAX_BHEL)
      DOUBLE PRECISION SAVEMOM(NEXTERNAL-1,2)
      COMMON/TO_SAVEMOM/SAVEMOM
      INTEGER SKIP(48)
      COMMON/CBORN/SKIP
      LOGICAL CALCULATEDBORN
      COMMON/CCALCULATEDBORN/CALCULATEDBORN
      INTEGER NFKSPROCESS
      COMMON/C_NFKSPROCESS/NFKSPROCESS
      LOGICAL COND_IJ
C     ----------
C     BEGIN CODE
C     ----------
      IDEN=IDEN_VALUES(NFKSPROCESS)
      FLAV_IDX=BORN_FLAVOR_INDEX_D(NFKSPROCESS)
      GLU_IJ = IJ_VALUES(NFKSPROCESS)
      DO I=1, DRIVER_VECTOR_SIZE
        NHEL_VEC(:,1:NCOMB,I)=NHEL(:,:)
      ENDDO
      NTRY(NFKSPROCESS)=NTRY(NFKSPROCESS)+1
      IF (GLU_IJ.EQ.0) THEN
        SKIP(NFKSPROCESS)=0
      ELSE
        SKIP(NFKSPROCESS)=1
        DO WHILE(NHEL(GLU_IJ ,SKIP(NFKSPROCESS)).NE.-NHEL(GLU_IJ ,1))
          SKIP(NFKSPROCESS)=SKIP(NFKSPROCESS)+1
        ENDDO
        SKIP(NFKSPROCESS)=SKIP(NFKSPROCESS)-1
      ENDIF
      DO JJ=1,NGRAPHS
        AMP2(JJ)=0D0
      ENDDO
      DO I=0,NAMPSO
        DO JJ=1,INT(JAMP2(0,0))
          JAMP2(JJ,I)=0D0
        ENDDO
      ENDDO
      IF (CALCULATEDBORN) THEN
        DO J=1,NEXTERNAL-1
          IF (SAVEMOM(J,1).NE.P1(0,J) .OR. SAVEMOM(J,2).NE.P1(3,J))
     $      THEN
            CALCULATEDBORN=.FALSE.
            WRITE (*,*) 'momenta not the same in Born'
            STOP
          ENDIF
        ENDDO
      ENDIF
      IF (.NOT.CALCULATEDBORN) THEN
        DO J=1,NEXTERNAL-1
          SAVEMOM(J,1)=P1(0,J)
          SAVEMOM(J,2)=P1(3,J)
        ENDDO
        RET_SAVEAMP(:,:) = (0D0,0D0)
      ENDIF
      DO I=0,NSQAMPSO
        ANS(1,I) = 0D0
        ANS(2,I) = 0D0
      ENDDO
      DO IHEL=1,NCOMB
C       the following lines are to avoid segfaults when glu_ij=0
        COND_IJ=SKIP(NFKSPROCESS).EQ.0
        IF (.NOT.COND_IJ) COND_IJ=COND_IJ.OR.NHEL(GLU_IJ,IHEL)
     $   .EQ.NHEL(GLU_IJ,1)
C       if (nhel(glu_ij,ihel).EQ.NHEL(GLU_IJ,1).or.skip(nfksprocess).eq
C       .0) then
        IF (COND_IJ) THEN
          IF ((GOODHEL(IHEL,NFKSPROCESS) .OR. GOODHEL(IHEL
     $     +SKIP(NFKSPROCESS),NFKSPROCESS) .OR. NTRY(NFKSPROCESS) .LT.
     $      2) ) THEN
            CALL BORN(P1,NHEL(1,IHEL),IHEL,FLAV_IDX,.FALSE.,AMP2,
     $           JAMP2,T,borns,ret_saveamp)
            DO I=1,NSQAMPSO
              ANS(1,I)=ANS(1,I)+T(1,I)
              ANS(2,I)=ANS(2,I)+T(2,I)
            ENDDO
            IF ( BORNS(1,0).NE.0D0 .AND. .NOT. GOODHEL(IHEL
     $       ,NFKSPROCESS) ) THEN
              GOODHEL(IHEL,NFKSPROCESS)=.TRUE.
            ENDIF
            IF ( BORNS(2,0).NE.0D0 .AND. .NOT. GOODHEL(IHEL
     $       +SKIP(NFKSPROCESS),NFKSPROCESS) ) THEN
              GOODHEL(IHEL+SKIP(NFKSPROCESS),NFKSPROCESS)=.TRUE.
            ENDIF
          ENDIF
        ENDIF
      ENDDO
      DO I=1,NSQAMPSO
        ANS(1,I)=ANS(1,I)/DBLE(IDEN)
        ANS(2,I)=ANS(2,I)/DBLE(IDEN)
        ANS(1,0)=ANS(1,0)+ANS(1,I)
        ANS(2,0)=ANS(2,0)+ANS(2,I)
      ENDDO
      CALCULATEDBORN=.TRUE.
      IF(NTRY(NFKSPROCESS).GE.MAX_TRY) THEN
        DO_TRY=.FALSE.
      ENDIF
      END


      RECURSIVE SUBROUTINE SBORN_SPLITORDERS_NTRY_VEC(P1,AMP2,JAMP2
     $ ,ANS,RET_SAVEAMP,DO_TRY,IVEC,IFKS,FLAV_IDX)
C     
C     Generated by MadGraph7 v. %(version)s, %(date)s
C     By the MadGraph7 Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     RETURNS AMPLITUDE SQUARED SUMMED/AVG OVER COLORS
C     AND HELICITIES
C     FOR THE POINT IN PHASE SPACE P1(0:3,NEXTERNAL-1)
C     
C     Process: _anti_quark _quark > t t~ [ real = QCD QED ] QCD^2<=4
C      QED^2<=2
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INCLUDE 'nexternal.inc'
      INCLUDE 'born_nhel.inc'
      INTEGER     NCOMB
      PARAMETER ( NCOMB=  16 )
      INTEGER NAMPSO, NSQAMPSO
      PARAMETER (NAMPSO=2, NSQAMPSO=3)
      INTEGER    THEL
      PARAMETER (THEL=NCOMB*48)
      INTEGER NGRAPHS
      PARAMETER (NGRAPHS=   3)
C     
C     ARGUMENTS 
C     
      REAL*8 P1(0:3,NEXTERNAL-1)
      DOUBLE PRECISION AMP2(NGRAPHS), JAMP2(0:2,0:NAMPSO)
      COMPLEX*16 ANS(2,0:NSQAMPSO)
      INTEGER IVEC,IFKS,FLAV_IDX
C     
C     LOCAL VARIABLES 
C     
      INTEGER IHEL,IDEN,I,J,JJ,GLU_IJ
      INCLUDE 'fks_info.inc'
      LOGICAL DO_TRY
      REAL*8 BORNS(2,0:NSQAMPSO)
      COMPLEX*16 BORNTILDE
      INTEGER MAX_TRY
      DATA MAX_TRY /20/
      INTEGER NTRY(48)
      DATA NTRY /48*0/
      COMPLEX*16 T(2,NSQAMPSO)
      INTEGER NHEL(NEXTERNAL-1,NCOMB)
      DATA (NHEL(I,   1),I=1,4) /-1, 1,-1, 1/
      DATA (NHEL(I,   2),I=1,4) /-1, 1,-1,-1/
      DATA (NHEL(I,   3),I=1,4) /-1, 1, 1, 1/
      DATA (NHEL(I,   4),I=1,4) /-1, 1, 1,-1/
      DATA (NHEL(I,   5),I=1,4) /-1,-1,-1, 1/
      DATA (NHEL(I,   6),I=1,4) /-1,-1,-1,-1/
      DATA (NHEL(I,   7),I=1,4) /-1,-1, 1, 1/
      DATA (NHEL(I,   8),I=1,4) /-1,-1, 1,-1/
      DATA (NHEL(I,   9),I=1,4) / 1, 1,-1, 1/
      DATA (NHEL(I,  10),I=1,4) / 1, 1,-1,-1/
      DATA (NHEL(I,  11),I=1,4) / 1, 1, 1, 1/
      DATA (NHEL(I,  12),I=1,4) / 1, 1, 1,-1/
      DATA (NHEL(I,  13),I=1,4) / 1,-1,-1, 1/
      DATA (NHEL(I,  14),I=1,4) / 1,-1,-1,-1/
      DATA (NHEL(I,  15),I=1,4) / 1,-1, 1, 1/
      DATA (NHEL(I,  16),I=1,4) / 1,-1, 1,-1/
      INTEGER IDEN_VALUES(48)
      DATA IDEN_VALUES /36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36
     $ , 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36,
     $  36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36
     $ , 36, 36, 36, 36, 36/
      INTEGER IJ_VALUES(48)
      DATA IJ_VALUES /1, 1, 1, 1, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0,
     $  1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1,
     $  1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2/
C     
C     GLOBAL VARIABLES
C     
      LOGICAL GOODHEL(NCOMB,48)
      COMMON /C_GOODHEL/GOODHEL
      DOUBLE COMPLEX RET_SAVEAMP(NGRAPHS,MAX_BHEL)
      DOUBLE PRECISION SAVEMOM(NEXTERNAL-1,2)
      COMMON/TO_SAVEMOM/SAVEMOM
      INTEGER SKIP(48)
      COMMON/CBORN/SKIP
      LOGICAL CALCULATEDBORN
      COMMON/CCALCULATEDBORN/CALCULATEDBORN
      INTEGER NFKSPROCESS
      COMMON/C_NFKSPROCESS/NFKSPROCESS
      LOGICAL COND_IJ
C     ----------
C     BEGIN CODE
C     ----------
      IDEN=IDEN_VALUES(IFKS)
      GLU_IJ = IJ_VALUES(IFKS)
      NTRY(IFKS)=NTRY(IFKS)+1
      IF (GLU_IJ.EQ.0) THEN
        SKIP(IFKS)=0
      ELSE
        SKIP(IFKS)=1
        DO WHILE(NHEL(GLU_IJ ,SKIP(IFKS)).NE.-NHEL(GLU_IJ ,1))
          SKIP(IFKS)=SKIP(IFKS)+1
        ENDDO
        SKIP(IFKS)=SKIP(IFKS)-1
      ENDIF
      DO JJ=1,NGRAPHS
        AMP2(JJ)=0D0
      ENDDO
      DO I=0,NAMPSO
        DO JJ=1,INT(JAMP2(0,0))
          JAMP2(JJ,I)=0D0
        ENDDO
      ENDDO
C     if (calculatedBorn) then
C     do j=1,nexternal-1
C     if (savemom(j,1).ne.p1(0,j) .or. savemom(j,2).ne.p1(3,j)) then
C     calculatedBorn=.false.
C     write (*,*) "momenta not the same in Born"
C     stop
C     endif
C     enddo
C     endif
C     if (.not.calculatedBorn) then
C     do j=1,nexternal-1
C     savemom(j,1)=p1(0,j)
C     savemom(j,2)=p1(3,j)
C     enddo
      RET_SAVEAMP(:,:) = (0D0,0D0)
C     endif
      DO I=0,NSQAMPSO
        ANS(1,I) = 0D0
        ANS(2,I) = 0D0
      ENDDO
      DO IHEL=1,NCOMB
C       the following lines are to avoid segfaults when glu_ij=0
        COND_IJ=SKIP(IFKS).EQ.0
        IF (.NOT.COND_IJ) COND_IJ=COND_IJ.OR.NHEL(GLU_IJ,IHEL)
     $   .EQ.NHEL(GLU_IJ,1)
C       if (nhel(glu_ij,ihel).EQ.NHEL(GLU_IJ,1).or.skip(ifks).eq.0)
C        then
        IF (COND_IJ) THEN
          IF ((GOODHEL(IHEL,IFKS) .OR. GOODHEL(IHEL+SKIP(IFKS),IFKS)
     $      .OR. NTRY(IFKS) .LT. 2) ) THEN
            CALL BORN_VEC(P1,NHEL(1,IHEL),IHEL,FLAV_IDX,.FALSE.,
     $           AMP2,JAMP2,T,borns,ret_saveamp,ivec,ifks)
            DO I=1,NSQAMPSO
              ANS(1,I)=ANS(1,I)+T(1,I)
              ANS(2,I)=ANS(2,I)+T(2,I)
            ENDDO
            IF ( BORNS(1,0).NE.0D0 .AND. .NOT. GOODHEL(IHEL,IFKS) )
     $        THEN
              GOODHEL(IHEL,IFKS)=.TRUE.
            ENDIF
            IF ( BORNS(2,0).NE.0D0 .AND. .NOT. GOODHEL(IHEL+SKIP(IFKS)
     $       ,IFKS) ) THEN
              GOODHEL(IHEL+SKIP(IFKS),IFKS)=.TRUE.
            ENDIF
          ENDIF
        ENDIF
      ENDDO
      DO I=1,NSQAMPSO
        ANS(1,I)=ANS(1,I)/DBLE(IDEN)
        ANS(2,I)=ANS(2,I)/DBLE(IDEN)
        ANS(1,0)=ANS(1,0)+ANS(1,I)
        ANS(2,0)=ANS(2,0)+ANS(2,I)
      ENDDO
C     calculatedBorn=.true.
      IF(NTRY(IFKS).GE.MAX_TRY) THEN
        DO_TRY=.FALSE.
      ENDIF
      END


      RECURSIVE SUBROUTINE BORN(P,NHEL,HELL,FLAV_IDX,
     $     force_ijglu_zero,amp2,jamp2,ANS,borns,ret_saveamp)
C     
C     Generated by MadGraph7 v. %(version)s, %(date)s
C     By the MadGraph7 Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     RETURNS AMPLITUDE SQUARED SUMMED/AVG OVER COLORS
C     FOR THE POINT WITH EXTERNAL LINES W(0:6,NEXTERNAL-1)

C     Process: _anti_quark _quark > t t~ [ real = QCD QED ] QCD^2<=4
C      QED^2<=2
C     
      USE ALOHA_OBJECT
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER NAMPSO, NSQAMPSO
      PARAMETER (NAMPSO=2, NSQAMPSO=3)
      INTEGER    NGRAPHS,    NEIGEN
      PARAMETER (NGRAPHS=   3,NEIGEN=  1)
      INTEGER    NWAVEFUNCS, NCOLOR
      PARAMETER (NWAVEFUNCS=5, NCOLOR=2)
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
      COMPLEX*16 IMAG1
      PARAMETER (IMAG1 = (0D0,1D0))
      INCLUDE 'nexternal.inc'
      INCLUDE 'born_nhel.inc'
      INCLUDE 'coupl.inc'
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL-1),BORNS(2,0:NSQAMPSO)
      INTEGER NHEL(NEXTERNAL-1), HELL, FLAV_IDX
      LOGICAL FORCE_IJGLU_ZERO
      DOUBLE PRECISION AMP2(3), JAMP2(0:2,0:NAMPSO)
      COMPLEX*16 ANS(2,NSQAMPSO)
C     
C     LOCAL VARIABLES 
C     
      INTEGER I,J,M,N,IHEL,BACK_HEL,GLU_IJ
      INTEGER IC(NEXTERNAL-1),NMO
      PARAMETER (NMO=NEXTERNAL-1)
      DATA IC /NMO*1/
      INTEGER FLAVOR(NEXTERNAL-1)
      INTEGER CF(NCOLOR*(NCOLOR+1)/2)
      INTEGER CF_INDEX, DENOM
      COMPLEX*16 ZTEMP, AMP(NGRAPHS), JAMP(NCOLOR,NAMPSO), JAMPH(2,
     $  NCOLOR,NAMPSO)
      TYPE(ALOHA) W(NWAVEFUNCS)
      COMPLEX*16 TMP_JAMP(0)
C     Flavor table for the FLAV_IDX -> FLAVOR rebuild.
      INTEGER NMASK_FLAV
      PARAMETER (NMASK_FLAV=4)
      INTEGER MASK_J
      INTEGER FLAV_TABLE(NEXTERNAL-1, NMASK_FLAV)
      DATA FLAV_TABLE / 1, 1, 1, 1, 2, 2, 1, 1, 3, 3, 1, 1, 4, 4, 1, 1
     $  /
C     
C     GLOBAL VARIABLES
C     
C     common/to_amps_born/  amp2,       jamp2
      DOUBLE COMPLEX SAVEAMP(NGRAPHS,MAX_BHEL)
      COMMON/TO_SAVEAMP/SAVEAMP
      DOUBLE COMPLEX RET_SAVEAMP(NGRAPHS,MAX_BHEL)
      INTEGER SKIP(48)
      COMMON/CBORN/SKIP
      LOGICAL CALCULATEDBORN
      COMMON/CCALCULATEDBORN/CALCULATEDBORN
      INTEGER CALCULATED_BORN_FLAVOR
      COMMON/CCALCULATEDBORNFLAVOR/CALCULATED_BORN_FLAVOR
      INTEGER NFKSPROCESS
      COMMON/C_NFKSPROCESS/NFKSPROCESS
      INTEGER STEP_HEL
      LOGICAL COND_IJ

C     
C     FUNCTION
C     
      INTEGER SQSOINDEXB

      INTEGER IJ_VALUES(48)
      DATA IJ_VALUES /1, 1, 1, 1, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0,
     $  1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1,
     $  1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2/
C     
C     COLOR DATA
C     
      DATA DENOM/1/
      DATA (CF(I),I=  1,  2) /9,6/
C     1 T(1,2) T(3,4)
      DATA (CF(I),I=  3,  3) /9/
C     1 T(1,4) T(3,2)
C     ----------
C     BEGIN CODE
C     ----------
      JAMP(:,:) = (0D0,0D0)
      BORNS(:,:) =0D0
      ANS(:,:) = (0D0, 0D0)
      FLAVOR(:) = 1

C     A saved Born amplitude is valid only for the selected physical
C      row.
      IF (CALCULATEDBORN .AND.
     $    CALCULATED_BORN_FLAVOR.NE.FLAV_IDX) CALCULATEDBORN=.FALSE.

      GLU_IJ = IJ_VALUES(NFKSPROCESS)
      IF (FORCE_IJGLU_ZERO) GLU_IJ = 0
      IF (GLU_IJ.NE.0) THEN
        BACK_HEL = NHEL(GLU_IJ)
        IF (BACK_HEL.NE.0) THEN
          STEP_HEL=-2*BACK_HEL
        ELSE
          STEP_HEL=1
        ENDIF
      ELSE
        BACK_HEL=0
        STEP_HEL=1
      ENDIF
      DO IHEL=BACK_HEL,-BACK_HEL,STEP_HEL
        IF (GLU_IJ.NE.0) THEN
          COND_IJ=IHEL.EQ.BACK_HEL.OR.NHEL(GLU_IJ).NE.0
        ELSE
          COND_IJ=IHEL.EQ.BACK_HEL
        ENDIF
        IF (COND_IJ) THEN
          IF (GLU_IJ.NE.0) THEN
            IF (NHEL(GLU_IJ).NE.0) NHEL(GLU_IJ) = IHEL
          ENDIF
          IF (.NOT. CALCULATEDBORN) THEN
C           Rebuild FLAVOR(NEXTERNAL-1) from the resolved flavor index.
            IF (FLAV_IDX .GE. 1 .AND. FLAV_IDX .LE. NMASK_FLAV) THEN
              DO MASK_J = 1, NEXTERNAL-1
                FLAVOR(MASK_J) = FLAV_TABLE(MASK_J, FLAV_IDX)
              ENDDO
            ELSE
              DO MASK_J = 1, NEXTERNAL-1
                FLAVOR(MASK_J) = FLAV_TABLE(MASK_J, 1)
              ENDDO
            ENDIF
            IF(IHEL.EQ.BACK_HEL)THEN
              SAVEAMP(:,HELL) = 0D0
            ELSEIF(IHEL.EQ.-BACK_HEL)THEN
              SAVEAMP(:,HELL+SKIP(NFKSPROCESS)) = 0D0
            ELSE
              WRITE(*,*) 'ERROR #1 in born.f'
              STOP
            ENDIF
            CALL OXXXXX(P(0,1),ZERO,NHEL(1),-1, FLAVOR(1),W(1))
            CALL IXXXXX(P(0,2),ZERO,NHEL(2),+1, FLAVOR(2),W(2))
            CALL OXXXXX(P(0,3),MDL_MT,NHEL(3),+1, FLAVOR(3),W(3))
            CALL IXXXXX(P(0,4),MDL_MT,NHEL(4),-1, FLAVOR(4),W(4))
            CALL FFV1MP0_3(W(2),W(1),FLV_94,ZERO,ZERO,W(5))
C           Amplitude(s) for diagram number 1
            CALL FFV1_0(W(4),W(3),W(5),GC_2,AMP(1))
            CALL FFV1P0_3(W(2),W(1),GC_11,ZERO,ZERO,W(5))
C           Amplitude(s) for diagram number 2
            CALL FFV1_0(W(4),W(3),W(5),GC_11,AMP(2))
            CALL FFV6_2M_3(W(2),W(1),FLV_96,FLV_97,MDL_MZ,MDL_WZ,W(5))
C           Amplitude(s) for diagram number 3
            CALL FFV6_2_0(W(4),W(3),W(5),GC_FFV_4,GC_FFV_5,AMP(3))
            DO I=1,NGRAPHS
              IF(IHEL.EQ.BACK_HEL)THEN
                SAVEAMP(I,HELL)=AMP(I)
                RET_SAVEAMP(I,HELL) = AMP(I)
              ELSEIF(IHEL.EQ.-BACK_HEL)THEN
                SAVEAMP(I,HELL+SKIP(NFKSPROCESS))=AMP(I)
                RET_SAVEAMP(I,HELL+SKIP(NFKSPROCESS)) = AMP(I)
              ELSE
                WRITE(*,*) 'ERROR #1 in born.f'
                STOP
              ENDIF
            ENDDO
          ELSEIF (CALCULATEDBORN) THEN
            DO I=1,NGRAPHS
              IF(IHEL.EQ.BACK_HEL)THEN
                AMP(I)=SAVEAMP(I,HELL)
                RET_SAVEAMP(I,HELL) = SAVEAMP(I,HELL)
              ELSEIF(IHEL.EQ.-BACK_HEL)THEN
                AMP(I)=SAVEAMP(I,HELL+SKIP(NFKSPROCESS))
                RET_SAVEAMP(I,HELL+SKIP(NFKSPROCESS)) = SAVEAMP(I,HELL
     $           +SKIP(NFKSPROCESS))
              ELSE
                WRITE(*,*) 'ERROR #1 in born.f'
                STOP
              ENDIF
            ENDDO
C           ret_saveamp(:,:) = saveamp(:,:)
          ENDIF
C         JAMPs contributing to orders QCD=2 QED=0
          JAMP(1,1) = (-1.666666666666667D-01)*AMP(2)
          JAMP(2,1) = (5.000000000000000D-01)*AMP(2)
C         JAMPs contributing to orders QCD=0 QED=2
          JAMP(1,2) = AMP(1)+AMP(3)
          DO M = 1, NAMPSO
            CF_INDEX = 0
            DO I = 1, NCOLOR
              ZTEMP = (0.D0,0.D0)
              DO J = I, NCOLOR
                CF_INDEX = CF_INDEX + 1
                ZTEMP = ZTEMP + CF(CF_INDEX)*JAMP(J,M)
              ENDDO
              DO N = 1, NAMPSO
                BORNS(2-(1+BACK_HEL*IHEL)/2,SQSOINDEXB(M,N))=BORNS(2
     $           -(1+BACK_HEL*IHEL)/2,SQSOINDEXB(M,N))+ZTEMP
     $           *DCONJG(JAMP(I,N))
              ENDDO
            ENDDO
          ENDDO
          DO I = 1, NGRAPHS
            AMP2(I)=AMP2(I)+AMP(I)*DCONJG(AMP(I))
          ENDDO
          DO J = 1,NAMPSO
            DO I = 1, NCOLOR
              JAMP2(I,J)=JAMP2(I,J)+JAMP(I,J)*DCONJG(JAMP(I,J))
              JAMPH(2-(1+BACK_HEL*IHEL)/2,I,J)=JAMP(I,J)
            ENDDO
          ENDDO
        ENDIF
      ENDDO
      BORNS(:,:) = BORNS(:,:)/DENOM
      DO I = 1, NSQAMPSO
        BORNS(1,0)=BORNS(1,0)+BORNS(1,I)
        BORNS(2,0)=BORNS(2,0)+BORNS(2,I)
        ANS(1,I) = BORNS(1,I) + BORNS(2,I)
      ENDDO
      DO M = 1, NAMPSO
        CF_INDEX = 0
        DO I = 1, NCOLOR
          ZTEMP = (0.D0,0.D0)
          DO J = I, NCOLOR
            CF_INDEX = CF_INDEX +1
            DO  N = 1, NAMPSO
              ANS(2,SQSOINDEXB(M,N))= ANS(2,SQSOINDEXB(M,N)) +
     $          CF(CF_INDEX)*(JAMPH(2,J,M)*DCONJG(JAMPH(1,I,N))
     $         +JAMPH(2,I,M)*DCONJG(JAMPH(1,J,N)))
            ENDDO
          ENDDO
        ENDDO

      ENDDO
      ANS(2,:) = ANS(2,:)/(2D0*DENOM)
      IF (GLU_IJ.NE.0) NHEL(GLU_IJ) = BACK_HEL
      CALCULATED_BORN_FLAVOR=FLAV_IDX
      END



      RECURSIVE SUBROUTINE BORN_VEC(P,NHEL,HELL,FLAV_IDX,
     $     force_ijglu_zero,amp2,jamp2,ANS,borns,ret_saveamp,ivec,ifks)
C     
C     Generated by MadGraph7 v. %(version)s, %(date)s
C     By the MadGraph7 Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     RETURNS AMPLITUDE SQUARED SUMMED/AVG OVER COLORS
C     FOR THE POINT WITH EXTERNAL LINES W(0:6,NEXTERNAL-1)

C     Process: _anti_quark _quark > t t~ [ real = QCD QED ] QCD^2<=4
C      QED^2<=2
C     
      USE COUPLINGS
      USE ALOHA_OBJECT
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER NAMPSO, NSQAMPSO
      PARAMETER (NAMPSO=2, NSQAMPSO=3)
      INTEGER    NGRAPHS,    NEIGEN
      PARAMETER (NGRAPHS=   3,NEIGEN=  1)
      INTEGER    NWAVEFUNCS, NCOLOR
      PARAMETER (NWAVEFUNCS=5, NCOLOR=2)
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
      COMPLEX*16 IMAG1
      PARAMETER (IMAG1 = (0D0,1D0))
      INCLUDE 'nexternal.inc'
      INCLUDE 'born_nhel.inc'
      INCLUDE 'coupl.inc'
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL-1),BORNS(2,0:NSQAMPSO)
      INTEGER NHEL(NEXTERNAL-1), HELL, FLAV_IDX
      LOGICAL FORCE_IJGLU_ZERO
      DOUBLE PRECISION AMP2(3), JAMP2(0:2,0:NAMPSO)
      COMPLEX*16 ANS(2,NSQAMPSO)
      INTEGER IVEC,IFKS
C     
C     LOCAL VARIABLES 
C     
      INTEGER I,J,M,N,IHEL,BACK_HEL,GLU_IJ
      INTEGER IC(NEXTERNAL-1),NMO
      PARAMETER (NMO=NEXTERNAL-1)
      DATA IC /NMO*1/
      INTEGER FLAVOR(NEXTERNAL-1)
      INTEGER CF(NCOLOR*(NCOLOR+1)/2)
      INTEGER CF_INDEX, DENOM
      COMPLEX*16 ZTEMP, AMP(NGRAPHS), JAMP(NCOLOR,NAMPSO),
     $     jamph(2,ncolor,nampso)
      TYPE(ALOHA) W(NWAVEFUNCS)
      COMPLEX*16 TMP_JAMP(0)
C     Flavor table for the FLAV_IDX -> FLAVOR rebuild.
      INTEGER NMASK_FLAV
      PARAMETER (NMASK_FLAV=4)
      INTEGER MASK_J
      INTEGER FLAV_TABLE(NEXTERNAL-1, NMASK_FLAV)
      DATA FLAV_TABLE / 1, 1, 1, 1, 2, 2, 1, 1, 3, 3, 1, 1, 4, 4, 1, 1
     $  /
C     
C     GLOBAL VARIABLES
C     
      DOUBLE COMPLEX RET_SAVEAMP(NGRAPHS,MAX_BHEL)
      INTEGER SKIP(48)
      COMMON/CBORN/SKIP
      INTEGER STEP_HEL
      LOGICAL COND_IJ

C     
C     FUNCTION
C     
      INTEGER SQSOINDEXB

      INTEGER IJ_VALUES(48)
      DATA IJ_VALUES /1, 1, 1, 1, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0,
     $  1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1,
     $  1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2/
C     
C     COLOR DATA
C     
      DATA DENOM/1/
      DATA (CF(I),I=  1,  2) /9,6/
C     1 T(1,2) T(3,4)
      DATA (CF(I),I=  3,  3) /9/
C     1 T(1,4) T(3,2)
C     ----------
C     BEGIN CODE
C     ----------
      JAMP(:,:) = (0D0,0D0)
      BORNS(:,:) =0D0
      ANS(:,:) = (0D0, 0D0)
      FLAVOR(:) = 1

      GLU_IJ = IJ_VALUES(IFKS)
      IF (FORCE_IJGLU_ZERO) GLU_IJ = 0
      IF (GLU_IJ.NE.0) THEN
        BACK_HEL = NHEL(GLU_IJ)
        IF (BACK_HEL.NE.0) THEN
          STEP_HEL=-2*BACK_HEL
        ELSE
          STEP_HEL=1
        ENDIF
      ELSE
        BACK_HEL=0
        STEP_HEL=1
      ENDIF
      DO IHEL=BACK_HEL,-BACK_HEL,STEP_HEL
        IF (GLU_IJ.NE.0) THEN
          COND_IJ=IHEL.EQ.BACK_HEL.OR.NHEL(GLU_IJ).NE.0
        ELSE
          COND_IJ=IHEL.EQ.BACK_HEL
        ENDIF
        IF (COND_IJ) THEN
          IF (GLU_IJ.NE.0) THEN
            IF (NHEL(GLU_IJ).NE.0) NHEL(GLU_IJ) = IHEL
          ENDIF
C         if (.not. calculatedBorn) then
C         if(ihel.eq.back_hel)then
C         saveamp(:,hell) = 0d0
C         elseif(ihel.eq.-back_hel)then
C         saveamp(:,hell+skip(ifks)) = 0d0
C         else
C         write(*,*) "ERROR #1 in born.f"
C         stop
C         endif
C         Rebuild FLAVOR(NEXTERNAL-1) from the resolved flavor index.
          IF (FLAV_IDX .GE. 1 .AND. FLAV_IDX .LE. NMASK_FLAV) THEN
            DO MASK_J = 1, NEXTERNAL-1
              FLAVOR(MASK_J) = FLAV_TABLE(MASK_J, FLAV_IDX)
            ENDDO
          ELSE
            DO MASK_J = 1, NEXTERNAL-1
              FLAVOR(MASK_J) = FLAV_TABLE(MASK_J, 1)
            ENDDO
          ENDIF
          CALL OXXXXX(P(0,1),ZERO,NHEL(1),-1, FLAVOR(1),W(1))
          CALL IXXXXX(P(0,2),ZERO,NHEL(2),+1, FLAVOR(2),W(2))
          CALL OXXXXX(P(0,3),MDL_MT,NHEL(3),+1, FLAVOR(3),W(3))
          CALL IXXXXX(P(0,4),MDL_MT,NHEL(4),-1, FLAVOR(4),W(4))
          CALL FFV1MP0_3(W(2),W(1),FLV_94,ZERO,ZERO,W(5))
C         Amplitude(s) for diagram number 1
          CALL FFV1_0(W(4),W(3),W(5),GC_2,AMP(1))
          CALL FFV1P0_3(W(2),W(1),GC_11_VEC(IVEC),ZERO,ZERO,W(5))
C         Amplitude(s) for diagram number 2
          CALL FFV1_0(W(4),W(3),W(5),GC_11_VEC(IVEC),AMP(2))
          CALL FFV6_2M_3(W(2),W(1),FLV_96,FLV_97,MDL_MZ,MDL_WZ,W(5))
C         Amplitude(s) for diagram number 3
          CALL FFV6_2_0(W(4),W(3),W(5),GC_FFV_4,GC_FFV_5,AMP(3))
          DO I=1,NGRAPHS
            IF(IHEL.EQ.BACK_HEL)THEN
              RET_SAVEAMP(I,HELL) = AMP(I)
            ELSEIF(IHEL.EQ.-BACK_HEL)THEN
              RET_SAVEAMP(I,HELL+SKIP(IFKS)) = AMP(I)
            ELSE
              WRITE(*,*) 'ERROR #1 in born.f'
              STOP
            ENDIF
          ENDDO
C         elseif (calculatedBorn) then
C         do i=1,ngraphs
C         if(ihel.eq.back_hel)then
C         amp(i)=saveamp(i,hell)
C         ret_saveamp(i,hell) = saveamp(i,hell)
C         elseif(ihel.eq.-back_hel)then
C         amp(i)=saveamp(i,hell+skip(ifks))
C         ret_saveamp(i,hell+skip(ifks)) = saveamp(i,hell+skip(ifks))
C         else
C         write(*,*) "ERROR #1 in born.f"
C         stop
C         endif
C         enddo
C         ret_saveamp(:,:) = saveamp(:,:)
C         endif
C         JAMPs contributing to orders QCD=2 QED=0
          JAMP(1,1) = (-1.666666666666667D-01)*AMP(2)
          JAMP(2,1) = (5.000000000000000D-01)*AMP(2)
C         JAMPs contributing to orders QCD=0 QED=2
          JAMP(1,2) = AMP(1)+AMP(3)
          DO M = 1, NAMPSO
            CF_INDEX = 0
            DO I = 1, NCOLOR
              ZTEMP = (0.D0,0.D0)
              DO J = I, NCOLOR
                CF_INDEX = CF_INDEX + 1
                ZTEMP = ZTEMP + CF(CF_INDEX)*JAMP(J,M)
              ENDDO
              DO N = 1, NAMPSO
                BORNS(2-(1+BACK_HEL*IHEL)/2,SQSOINDEXB(M,N))=BORNS(2
     $           -(1+BACK_HEL*IHEL)/2,SQSOINDEXB(M,N))+ZTEMP
     $           *DCONJG(JAMP(I,N))
              ENDDO
            ENDDO
          ENDDO
          DO I = 1, NGRAPHS
            AMP2(I)=AMP2(I)+AMP(I)*DCONJG(AMP(I))
          ENDDO
          DO J = 1,NAMPSO
            DO I = 1, NCOLOR
              JAMP2(I,J)=JAMP2(I,J)+JAMP(I,J)*DCONJG(JAMP(I,J))
              JAMPH(2-(1+BACK_HEL*IHEL)/2,I,J)=JAMP(I,J)
            ENDDO
          ENDDO
        ENDIF
      ENDDO
      BORNS(:,:) = BORNS(:,:)/DENOM
      DO I = 1, NSQAMPSO
        BORNS(1,0)=BORNS(1,0)+BORNS(1,I)
        BORNS(2,0)=BORNS(2,0)+BORNS(2,I)
        ANS(1,I) = BORNS(1,I) + BORNS(2,I)
      ENDDO
      DO M = 1, NAMPSO
        CF_INDEX = 0
        DO I = 1, NCOLOR
          ZTEMP = (0.D0,0.D0)
          DO J = I, NCOLOR
            CF_INDEX = CF_INDEX +1
            DO  N = 1, NAMPSO
              ANS(2,SQSOINDEXB(M,N))= ANS(2,SQSOINDEXB(M,N)) +
     $          CF(CF_INDEX)*(JAMPH(2,J,M)*DCONJG(JAMPH(1,I,N))
     $         +JAMPH(2,I,M)*DCONJG(JAMPH(1,J,N)))
            ENDDO
          ENDDO
        ENDDO

      ENDDO
      ANS(2,:) = ANS(2,:)/(2D0*DENOM)
      IF (GLU_IJ.NE.0) NHEL(GLU_IJ) = BACK_HEL
      END

      BLOCK DATA GOODHELS
      INTEGER     NCOMB
      PARAMETER ( NCOMB=  16 )
      INTEGER    THEL
      PARAMETER (THEL=NCOMB*48)
      LOGICAL GOODHEL(NCOMB,48)
      COMMON /C_GOODHEL/GOODHEL
      INTEGER CALCULATED_BORN_FLAVOR
      COMMON/CCALCULATEDBORNFLAVOR/CALCULATED_BORN_FLAVOR
      DATA GOODHEL/THEL*.FALSE./
      DATA CALCULATED_BORN_FLAVOR /0/
      END




      RECURSIVE INTEGER FUNCTION SQSOINDEXB(AMPORDERA,AMPORDERB)
C     
C     This functions plays the role of the interference matrix. It can
C      be hardcoded or 
C     made more elegant using hashtables if its execution speed ever
C      becomes a relevant
C     factor. From two split order indices of the jamps, it return the
C      corresponding
C     index in the squared order canonical ordering.
C     
C     CONSTANTS
C     
      IMPLICIT NONE
      INTEGER NAMPSO, NSQAMPSO
      PARAMETER (NAMPSO=2, NSQAMPSO=3)
      INTEGER NSPLITORDERS
      PARAMETER (NSPLITORDERS=2)
C     
C     ARGUMENTS
C     
      INTEGER AMPORDERA, AMPORDERB
C     
C     LOCAL VARIABLES
C     
      INTEGER I, SQORDERS(NSPLITORDERS)
      INTEGER AMPSPLITORDERS(NAMPSO,NSPLITORDERS)
      DATA (AMPSPLITORDERS(  1,I),I=  1,  2) /    2,    0/
      DATA (AMPSPLITORDERS(  2,I),I=  1,  2) /    0,    2/
C     
C     FUNCTION
C     
      INTEGER SQSOINDEXB_FROM_ORDERS
C     
C     BEGIN CODE
C     
      DO I=1,NSPLITORDERS
        SQORDERS(I)=AMPSPLITORDERS(AMPORDERA,I)
     $   +AMPSPLITORDERS(AMPORDERB,I)
      ENDDO
      SQSOINDEXB=SQSOINDEXB_FROM_ORDERS(SQORDERS)
      END



      RECURSIVE INTEGER FUNCTION SQSOINDEXB_FROM_ORDERS(ORDERS)
C     
C     From a list of values for the split orders, this function
C      returns the
C     corresponding index in the squared orders canonical ordering.
C     
      IMPLICIT NONE
      INTEGER NSQAMPSO
      PARAMETER (NSQAMPSO=3)
      INTEGER NSPLITORDERS
      PARAMETER (NSPLITORDERS=2)
C     
C     ARGUMENTS
C     
      INTEGER ORDERS(NSPLITORDERS)
C     
C     LOCAL VARIABLES
C     
      INTEGER I,J
      INTEGER SQSPLITORDERS(NSQAMPSO,NSPLITORDERS)
C     the values listed below are for QCD, QED
      DATA (SQSPLITORDERS(  1,I),I=  1,  2) /    4,    0/
      DATA (SQSPLITORDERS(  2,I),I=  1,  2) /    2,    2/
      DATA (SQSPLITORDERS(  3,I),I=  1,  2) /    0,    4/
C     
C     BEGIN CODE
C     
      DO I=1,NSQAMPSO
        DO J=1,NSPLITORDERS
          IF (ORDERS(J).NE.SQSPLITORDERS(I,J)) GOTO 1009
        ENDDO
        SQSOINDEXB_FROM_ORDERS = I
        RETURN
 1009   CONTINUE
      ENDDO

      WRITE(*,*) 'ERROR:: Stopping function sqsoindex_from_orders'
      WRITE(*,*) 'Could not find squared orders ',(ORDERS(I),I=1
     $ ,NSPLITORDERS)
      STOP

      END



      RECURSIVE INTEGER FUNCTION GETORDPOWFROMINDEX_B(IORDER, INDX)
C     
C     Return the power of the IORDER-th order appearing at position
C      INDX
C     in the split-orders output
C     
      IMPLICIT NONE
      INTEGER NSQAMPSO
      PARAMETER (NSQAMPSO=3)
      INTEGER NSPLITORDERS
      PARAMETER (NSPLITORDERS=2)
C     
C     ARGUMENTS
C     
      INTEGER IORDER, INDX
C     
C     LOCAL VARIABLES
C     
      INTEGER I
      INTEGER SQSPLITORDERS(NSQAMPSO,NSPLITORDERS)
C     the values listed below are for QCD, QED
      DATA (SQSPLITORDERS(  1,I),I=  1,  2) /    4,    0/
      DATA (SQSPLITORDERS(  2,I),I=  1,  2) /    2,    2/
      DATA (SQSPLITORDERS(  3,I),I=  1,  2) /    0,    4/
C     
C     BEGIN CODE
C     
      IF (IORDER.GT.NSPLITORDERS.OR.IORDER.LT.1) THEN
        WRITE(*,*) 'INVALID IORDER B', IORDER
        WRITE(*,*) 'SHOULD BE BETWEEN 1 AND ', NSPLITORDERS
        STOP
      ENDIF

      IF (INDX.GT.NSQAMPSO.OR.INDX.LT.1) THEN
        WRITE(*,*) 'INVALID INDX B', INDX
        WRITE(*,*) 'SHOULD BE BETWEEN 1 AND ', NSQAMPSO
        STOP
      ENDIF

      GETORDPOWFROMINDEX_B=SQSPLITORDERS(INDX, IORDER)
      END


      RECURSIVE SUBROUTINE GET_NSQSO_B(NSQSO)
C     
C     Simple recursive subroutine returning the number of squared
C      split order
C     contributions returned in ANS when calling SMATRIX_SPLITORDERS
C     
      IMPLICIT NONE
      INTEGER NSQAMPSO
      PARAMETER (NSQAMPSO=3)
      INTEGER NSQSO

      NSQSO=NSQAMPSO

      END

