      SUBROUTINE SMATRIX2(P,ANS_SUMMED)
C     
C     Generated by MadGraph7 v. %(version)s, %(date)s
C     By the MadGraph7 Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     
C     Return the sum of the split orders which are required in
C      orders.inc (NLO_ORDERS)
C     
C     
C     Process: a _anti_quark > t t~ _anti_quark [ real = QCD QED ]
C      QCD^2<=4 QED^2<=2
C     
C     
C     CONSTANTS
C     
      IMPLICIT NONE
      INCLUDE 'orders.inc'
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=5)
      INTEGER NSQAMPSO
      PARAMETER (NSQAMPSO=1)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL), ANS_SUMMED
C     
C     VARIABLES
C     
      INTEGER I,J
      REAL*8 ANS(0:NSQAMPSO)
      LOGICAL KEEP_ORDER(NSQAMPSO), FIRSTTIME
      DATA KEEP_ORDER / NSQAMPSO*.TRUE. /
      DATA FIRSTTIME / .TRUE. /
      INTEGER AMP_ORDERS(NSPLITORDERS)
      DOUBLE PRECISION ANS_MAX, TINY
      PARAMETER (TINY = 1D-12)
      DOUBLE PRECISION DUMMY_AMP_SPLIT(AMP_SPLIT_SIZE)
      DOUBLE PRECISION WGT_ME_BORN,WGT_ME_REAL
      COMMON/C_WGT_ME_TREE/WGT_ME_BORN,WGT_ME_REAL
C     
C     FUNCTIONS
C     
      INTEGER GETORDPOWFROMINDEX2
      INTEGER ORDERS_TO_AMP_SPLIT_POS
C     
C     BEGIN CODE
C     

      CALL SMATRIX2_AMP(P,DUMMY_AMP_SPLIT,ANS_SUMMED)
      AMP_SPLIT(:)=DUMMY_AMP_SPLIT(:)
      WGT_ME_REAL=ANS_SUMMED

      END


      SUBROUTINE SMATRIX2_AMP(P,RET_AMP_SPLIT,ANS_SUMMED)
C     
C     Generated by MadGraph7 v. %(version)s, %(date)s
C     By the MadGraph7 Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     
C     Return the sum of the split orders which are required in
C      orders.inc (NLO_ORDERS)
C     
C     
C     Process: a _anti_quark > t t~ _anti_quark [ real = QCD QED ]
C      QCD^2<=4 QED^2<=2
C     
C     
C     CONSTANTS
C     
      IMPLICIT NONE
      INCLUDE 'orders.inc'
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=5)
      INTEGER NSQAMPSO
      PARAMETER (NSQAMPSO=1)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL), ANS_SUMMED
      DOUBLE PRECISION RET_AMP_SPLIT(AMP_SPLIT_SIZE)
C     
C     VARIABLES
C     
      INTEGER I,J
      REAL*8 ANS(0:NSQAMPSO)
      LOGICAL KEEP_ORDER2(NSQAMPSO), FIRSTTIME
      COMMON /TO_KEEP_ORDER2/KEEP_ORDER2
      DATA FIRSTTIME / .TRUE. /
      INTEGER AMP_ORDERS(NSPLITORDERS)
      DOUBLE PRECISION ANS_MAX, TINY
      PARAMETER (TINY = 1D-12)
C     
C     FUNCTIONS
C     
      INTEGER GETORDPOWFROMINDEX2
      INTEGER ORDERS_TO_AMP_SPLIT_POS
C     
C     BEGIN CODE
C     

C     look for orders which match the nlo order constraint 

      IF (FIRSTTIME) THEN
        KEEP_ORDER2(:) = .TRUE.
        CALL FIRSTTIME2_SETUP(FIRSTTIME,KEEP_ORDER2)
      ENDIF

      CALL SMATRIX2_SPLITORDERS(P,ANS)
      ANS_SUMMED = 0D0
      ANS_MAX = 0D0

C     reset the amp_split array
      RET_AMP_SPLIT(1:AMP_SPLIT_SIZE) = 0D0

      DO I = 1, NSQAMPSO
        ANS_MAX = MAX(DABS(ANS(I)),ANS_MAX)
      ENDDO

      DO I = 1, NSQAMPSO
        IF (KEEP_ORDER2(I)) THEN
          ANS_SUMMED = ANS_SUMMED + ANS(I)
C         keep track of the separate pieces correspoinding to
C          different coupling combinations
          DO J = 1, NSPLITORDERS
            AMP_ORDERS(J) = GETORDPOWFROMINDEX2(J, I)
          ENDDO
          IF (ABS(ANS(I)).GT.ANS_MAX*TINY)
     $      RET_AMP_SPLIT(ORDERS_TO_AMP_SPLIT_POS(AMP_ORDERS)) = ANS(I)
        ENDIF
      ENDDO

C     avoid fake non-zeros
      IF (DABS(ANS_SUMMED).LT.TINY*ANS_MAX) ANS_SUMMED=0D0

C     AMP_SPLIT(1:AMP_SPLIT_SIZE) = RET_AMP_SPLIT(1:AMP_SPLIT_SIZE)

      RETURN
      END




      RECURSIVE SUBROUTINE SMATRIX2_AMP_VEC(P,
     $     RET_AMP_SPLIT,ANS_SUMMED,IVEC,FLAV_IDX)
C     
C     Generated by MadGraph7 v. %(version)s, %(date)s
C     By the MadGraph7 Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     
C     Return the sum of the split orders which are required in
C      orders.inc (NLO_ORDERS)
C     
C     
C     Process: a _anti_quark > t t~ _anti_quark [ real = QCD QED ]
C      QCD^2<=4 QED^2<=2
C     
C     
C     CONSTANTS
C     
      IMPLICIT NONE
      INCLUDE 'orders.inc'
      INTEGER    NEXTERNAL
      PARAMETER (NEXTERNAL=5)
      INTEGER NSQAMPSO
      PARAMETER (NSQAMPSO=1)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL), ANS_SUMMED
      DOUBLE PRECISION RET_AMP_SPLIT(AMP_SPLIT_SIZE)
      INTEGER IVEC,FLAV_IDX
C     
C     VARIABLES
C     
      INTEGER I,J
      REAL*8 ANS(0:NSQAMPSO)
      LOGICAL KEEP_ORDER2(NSQAMPSO)
      COMMON /TO_KEEP_ORDER2/KEEP_ORDER2
      INTEGER AMP_ORDERS(NSPLITORDERS)
      DOUBLE PRECISION ANS_MAX, TINY
      PARAMETER (TINY = 1D-12)
C     
C     FUNCTIONS
C     
      INTEGER GETORDPOWFROMINDEX2
      INTEGER ORDERS_TO_AMP_SPLIT_POS
C     
C     BEGIN CODE
C     

C     look for orders which match the nlo order constraint 

C     if (firsttime) then
C     call firsttime2_setup(firsttime,keep_order)
C     endif

      CALL SMATRIX2_SPLITORDERS_VEC(P,ANS,IVEC,FLAV_IDX)
      ANS_SUMMED = 0D0
      ANS_MAX = 0D0

C     reset the amp_split array
      RET_AMP_SPLIT(1:AMP_SPLIT_SIZE) = 0D0

      DO I = 1, NSQAMPSO
        ANS_MAX = MAX(DABS(ANS(I)),ANS_MAX)
      ENDDO

      DO I = 1, NSQAMPSO
        IF (KEEP_ORDER2(I)) THEN
          ANS_SUMMED = ANS_SUMMED + ANS(I)
C         keep track of the separate pieces correspoinding to
C          different coupling combinations
          DO J = 1, NSPLITORDERS
            AMP_ORDERS(J) = GETORDPOWFROMINDEX2(J, I)
          ENDDO
          IF (ABS(ANS(I)).GT.ANS_MAX*TINY)
     $      RET_AMP_SPLIT(ORDERS_TO_AMP_SPLIT_POS(AMP_ORDERS)) = ANS(I)
        ENDIF
      ENDDO

C     avoid fake non-zeros
      IF (DABS(ANS_SUMMED).LT.TINY*ANS_MAX) ANS_SUMMED=0D0

      RETURN
      END




      SUBROUTINE FIRSTTIME2_SETUP(FIRSTTIME,KEEP_ORDER)
C     
C     Sets up the orders that match the NLO order constraint
C     
      IMPLICIT NONE
      INCLUDE 'orders.inc'
      INTEGER I,J
      INTEGER NSQAMPSO
      PARAMETER (NSQAMPSO=1)
      LOGICAL KEEP_ORDER(NSQAMPSO), FIRSTTIME
C     
C     FUNCTIONS
C     
      INTEGER GETORDPOWFROMINDEX2

      DO I = 1, NSQAMPSO
        DO J = 1, NSPLITORDERS
          IF(GETORDPOWFROMINDEX2(J, I) .GT. NLO_ORDERS(J)) THEN
            KEEP_ORDER(I) = .FALSE.
            EXIT
          ENDIF
        ENDDO
        IF (KEEP_ORDER(I)) THEN
          WRITE(*,*) 'REAL 2: keeping split order ', I
        ELSE
          WRITE(*,*) 'REAL 2: not keeping split order ', I
        ENDIF
      ENDDO
      FIRSTTIME = .FALSE.

      END


      SUBROUTINE SMATRIX2_SPLITORDERS(P,ANS)
C     
C     Generated by MadGraph7 v. %(version)s, %(date)s
C     By the MadGraph7 Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     Returns amplitude squared summed/avg over colors
C     and helicities
C     for the point in phase space P(0:3,NEXTERNAL)
C     
C     Process: a _anti_quark > t t~ _anti_quark [ real = QCD QED ]
C      QCD^2<=4 QED^2<=2
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INCLUDE 'nexternal.inc'
      INCLUDE 'nFKSconfigs.inc'
      INTEGER     NCOMB
      PARAMETER ( NCOMB=32)
      INTEGER HEL_CONFIGS
      PARAMETER (HEL_CONFIGS=FKS_CONFIGS)
      INTEGER THEL
      PARAMETER (THEL=NCOMB*HEL_CONFIGS)
      INTEGER NSQAMPSO
      PARAMETER (NSQAMPSO=1)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS(0:NSQAMPSO)
C     
C     LOCAL VARIABLES 
C     
      INCLUDE 'fks_info.inc'
      INTEGER IHEL,IDEN,I,J,FLAV_IDX,HEL_INDEX
      INTEGER T_IDENT(NCOMB,HEL_CONFIGS)
      REAL*8 T(0:NSQAMPSO)
      REAL*8 T_SAVE(NCOMB,0:NSQAMPSO,HEL_CONFIGS)
      SAVE T_SAVE,T_IDENT
      INTEGER NHEL(NEXTERNAL,NCOMB)
      DATA (NHEL(I,   1),I=1,5) /-1,-1,-1, 1, 1/
      DATA (NHEL(I,   2),I=1,5) /-1,-1,-1, 1,-1/
      DATA (NHEL(I,   3),I=1,5) /-1,-1,-1,-1, 1/
      DATA (NHEL(I,   4),I=1,5) /-1,-1,-1,-1,-1/
      DATA (NHEL(I,   5),I=1,5) /-1,-1, 1, 1, 1/
      DATA (NHEL(I,   6),I=1,5) /-1,-1, 1, 1,-1/
      DATA (NHEL(I,   7),I=1,5) /-1,-1, 1,-1, 1/
      DATA (NHEL(I,   8),I=1,5) /-1,-1, 1,-1,-1/
      DATA (NHEL(I,   9),I=1,5) /-1, 1,-1, 1, 1/
      DATA (NHEL(I,  10),I=1,5) /-1, 1,-1, 1,-1/
      DATA (NHEL(I,  11),I=1,5) /-1, 1,-1,-1, 1/
      DATA (NHEL(I,  12),I=1,5) /-1, 1,-1,-1,-1/
      DATA (NHEL(I,  13),I=1,5) /-1, 1, 1, 1, 1/
      DATA (NHEL(I,  14),I=1,5) /-1, 1, 1, 1,-1/
      DATA (NHEL(I,  15),I=1,5) /-1, 1, 1,-1, 1/
      DATA (NHEL(I,  16),I=1,5) /-1, 1, 1,-1,-1/
      DATA (NHEL(I,  17),I=1,5) / 1,-1,-1, 1, 1/
      DATA (NHEL(I,  18),I=1,5) / 1,-1,-1, 1,-1/
      DATA (NHEL(I,  19),I=1,5) / 1,-1,-1,-1, 1/
      DATA (NHEL(I,  20),I=1,5) / 1,-1,-1,-1,-1/
      DATA (NHEL(I,  21),I=1,5) / 1,-1, 1, 1, 1/
      DATA (NHEL(I,  22),I=1,5) / 1,-1, 1, 1,-1/
      DATA (NHEL(I,  23),I=1,5) / 1,-1, 1,-1, 1/
      DATA (NHEL(I,  24),I=1,5) / 1,-1, 1,-1,-1/
      DATA (NHEL(I,  25),I=1,5) / 1, 1,-1, 1, 1/
      DATA (NHEL(I,  26),I=1,5) / 1, 1,-1, 1,-1/
      DATA (NHEL(I,  27),I=1,5) / 1, 1,-1,-1, 1/
      DATA (NHEL(I,  28),I=1,5) / 1, 1,-1,-1,-1/
      DATA (NHEL(I,  29),I=1,5) / 1, 1, 1, 1, 1/
      DATA (NHEL(I,  30),I=1,5) / 1, 1, 1, 1,-1/
      DATA (NHEL(I,  31),I=1,5) / 1, 1, 1,-1, 1/
      DATA (NHEL(I,  32),I=1,5) / 1, 1, 1,-1,-1/
      LOGICAL GOODHEL(NCOMB,HEL_CONFIGS)
      DATA GOODHEL/THEL*.FALSE./
      INTEGER NTRY(HEL_CONFIGS)
      DATA NTRY/HEL_CONFIGS*0/
      INTEGER NFKSPROCESS
      COMMON/C_NFKSPROCESS/NFKSPROCESS
      INTEGER IDEN_FLAVOR(4)
      DATA IDEN_FLAVOR / 12, 12, 12, 12 /
C     ----------
C     BEGIN CODE
C     ----------
      FLAV_IDX=REAL_FLAVOR_INDEX_D(NFKSPROCESS)
      HEL_INDEX=NFKSPROCESS
      IF (FLAV_IDX.GE.1.AND.FLAV_IDX.LE.4) IDEN=IDEN_FLAVOR(FLAV_IDX)
      NTRY(HEL_INDEX)=NTRY(HEL_INDEX)+1
      DO I=0,NSQAMPSO
        ANS(I) = 0D0
      ENDDO
      DO IHEL=1,NCOMB
        IF (GOODHEL(IHEL,HEL_INDEX) .OR.
     $      NTRY(HEL_INDEX) .LT. 2) THEN
        IF (NTRY(HEL_INDEX).LT.2) THEN
C         for the first ps-point, check for helicities that give
C         identical matrix elements
          CALL MATRIX_2(P,NHEL(1,IHEL),FLAV_IDX,T)
          DO I=0,NSQAMPSO
            T_SAVE(IHEL,I,HEL_INDEX)=T(I)
          ENDDO
          T_IDENT(IHEL,HEL_INDEX)=-1
          DO I=1,IHEL-1
            IF (T(0).EQ.0D0) EXIT
            IF (T_SAVE(I,0,HEL_INDEX).EQ.0D0) CYCLE
            DO J = 0, NSQAMPSO
              IF (ABS(T(J)/T_SAVE(I,J,HEL_INDEX)-1D0)
     $                .GT. 1D-12) goto 444
            ENDDO
            T_IDENT(IHEL,HEL_INDEX) = I
 444        CONTINUE
          ENDDO
        ELSE
          IF (T_IDENT(IHEL,HEL_INDEX).GT.0) THEN
C           if two helicity states are identical, dont recompute
            DO I=0,NSQAMPSO
              T(I)=T_SAVE(T_IDENT(IHEL,HEL_INDEX),I,HEL_INDEX)
              T_SAVE(IHEL,I,HEL_INDEX)=T(I)
            ENDDO
          ELSE
            CALL MATRIX_2(P,NHEL(1,IHEL),FLAV_IDX,T)
            DO I=0,NSQAMPSO
              T_SAVE(IHEL,I,HEL_INDEX)=T(I)
            ENDDO
          ENDIF
        ENDIF
C       add to the sum of helicities
        DO I=1,NSQAMPSO  !keep loop from 1!!
          ANS(I)=ANS(I)+T(I)
        ENDDO
        IF (T(0) .NE. 0D0 .AND.
     $        .NOT. GOODHEL(IHEL,HEL_INDEX)) THEN
        GOODHEL(IHEL,HEL_INDEX)=.TRUE.
        ENDIF
        ENDIF
      ENDDO
      DO I=1,NSQAMPSO
        ANS(I)=ANS(I)/DBLE(IDEN)
        ANS(0)=ANS(0)+ANS(I)
      ENDDO
      END


      RECURSIVE SUBROUTINE SMATRIX2_SPLITORDERS_VEC(P,
     $     ANS,IVEC,FLAV_IDX)
C     
C     Generated by MadGraph7 v. %(version)s, %(date)s
C     By the MadGraph7 Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     Returns amplitude squared summed/avg over colors
C     and helicities
C     for the point in phase space P(0:3,NEXTERNAL)
C     
C     Process: a _anti_quark > t t~ _anti_quark [ real = QCD QED ]
C      QCD^2<=4 QED^2<=2
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INCLUDE 'nexternal.inc'
      INTEGER     NCOMB
      PARAMETER ( NCOMB=32)
      INTEGER NSQAMPSO
      PARAMETER (NSQAMPSO=1)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS(0:NSQAMPSO)
      INTEGER IVEC,FLAV_IDX
C     
C     LOCAL VARIABLES 
C     
      INTEGER IHEL,IDEN,I,J,T_IDENT2(NCOMB)
      REAL*8 T(0:NSQAMPSO),T_SAVE(NCOMB,0:NSQAMPSO)
C     SAVE T_SAVE,T_IDENT
      COMMON /TO_T_IDENT2/T_IDENT2
      INTEGER NHEL(NEXTERNAL,NCOMB)
      DATA (NHEL(I,   1),I=1,5) /-1,-1,-1, 1, 1/
      DATA (NHEL(I,   2),I=1,5) /-1,-1,-1, 1,-1/
      DATA (NHEL(I,   3),I=1,5) /-1,-1,-1,-1, 1/
      DATA (NHEL(I,   4),I=1,5) /-1,-1,-1,-1,-1/
      DATA (NHEL(I,   5),I=1,5) /-1,-1, 1, 1, 1/
      DATA (NHEL(I,   6),I=1,5) /-1,-1, 1, 1,-1/
      DATA (NHEL(I,   7),I=1,5) /-1,-1, 1,-1, 1/
      DATA (NHEL(I,   8),I=1,5) /-1,-1, 1,-1,-1/
      DATA (NHEL(I,   9),I=1,5) /-1, 1,-1, 1, 1/
      DATA (NHEL(I,  10),I=1,5) /-1, 1,-1, 1,-1/
      DATA (NHEL(I,  11),I=1,5) /-1, 1,-1,-1, 1/
      DATA (NHEL(I,  12),I=1,5) /-1, 1,-1,-1,-1/
      DATA (NHEL(I,  13),I=1,5) /-1, 1, 1, 1, 1/
      DATA (NHEL(I,  14),I=1,5) /-1, 1, 1, 1,-1/
      DATA (NHEL(I,  15),I=1,5) /-1, 1, 1,-1, 1/
      DATA (NHEL(I,  16),I=1,5) /-1, 1, 1,-1,-1/
      DATA (NHEL(I,  17),I=1,5) / 1,-1,-1, 1, 1/
      DATA (NHEL(I,  18),I=1,5) / 1,-1,-1, 1,-1/
      DATA (NHEL(I,  19),I=1,5) / 1,-1,-1,-1, 1/
      DATA (NHEL(I,  20),I=1,5) / 1,-1,-1,-1,-1/
      DATA (NHEL(I,  21),I=1,5) / 1,-1, 1, 1, 1/
      DATA (NHEL(I,  22),I=1,5) / 1,-1, 1, 1,-1/
      DATA (NHEL(I,  23),I=1,5) / 1,-1, 1,-1, 1/
      DATA (NHEL(I,  24),I=1,5) / 1,-1, 1,-1,-1/
      DATA (NHEL(I,  25),I=1,5) / 1, 1,-1, 1, 1/
      DATA (NHEL(I,  26),I=1,5) / 1, 1,-1, 1,-1/
      DATA (NHEL(I,  27),I=1,5) / 1, 1,-1,-1, 1/
      DATA (NHEL(I,  28),I=1,5) / 1, 1,-1,-1,-1/
      DATA (NHEL(I,  29),I=1,5) / 1, 1, 1, 1, 1/
      DATA (NHEL(I,  30),I=1,5) / 1, 1, 1, 1,-1/
      DATA (NHEL(I,  31),I=1,5) / 1, 1, 1,-1, 1/
      DATA (NHEL(I,  32),I=1,5) / 1, 1, 1,-1,-1/
      LOGICAL GOODHEL2(NCOMB), DO_TRY
      DATA DO_TRY/.TRUE./
      COMMON /TO_GOODHEL2/GOODHEL2
      INTEGER IDEN_FLAVOR(4)
      DATA IDEN_FLAVOR / 12, 12, 12, 12 /
C     ----------
C     BEGIN CODE
C     ----------
      T(:) = 0D0
      T_SAVE(:,:) = 0D0
      IF (FLAV_IDX.GE.1.AND.FLAV_IDX.LE.4) IDEN=IDEN_FLAVOR(FLAV_IDX)
C     IF (DO_TRY) THEN
C     CALL SMATRIX2_SPLITORDERS_NTRY_VEC(P,ANS,DO_TRY,GOODHEL2,T_IDENT2
C     ,IVEC)
C     ELSE
      DO I=0,NSQAMPSO
        ANS(I) = 0D0
      ENDDO
      DO IHEL=1,NCOMB
        T(:) = 0D0
        CALL MATRIX_2_VEC(P,NHEL(1,IHEL),FLAV_IDX,T,
     $       IVEC)
C       add to the sum of helicities
        DO I=1,NSQAMPSO  !keep loop from 1!!
          ANS(I)=ANS(I)+T(I)
        ENDDO
      ENDDO
      DO I=1,NSQAMPSO
        ANS(I)=ANS(I)/DBLE(IDEN)
        ANS(0)=ANS(0)+ANS(I)
      ENDDO
C     ENDIF
      END


      SUBROUTINE SMATRIX2_SPLITORDERS_NTRY(P,ANS,DO_TRY,GOODHEL
     $ ,T_IDENT)
C     
C     Generated by MadGraph7 v. %(version)s, %(date)s
C     By the MadGraph7 Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     Returns amplitude squared summed/avg over colors
C     and helicities
C     for the point in phase space P(0:3,NEXTERNAL)
C     
C     Process: a _anti_quark > t t~ _anti_quark [ real = QCD QED ]
C      QCD^2<=4 QED^2<=2
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INCLUDE 'nexternal.inc'
      INCLUDE 'fks_info.inc'
      INTEGER     NCOMB
      PARAMETER ( NCOMB=32)
      INTEGER NSQAMPSO
      PARAMETER (NSQAMPSO=1)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS(0:NSQAMPSO)
C     
C     LOCAL VARIABLES 
C     
      INTEGER IHEL,IDEN,I,J,T_IDENT(NCOMB),FLAV_IDX,NFKSPROCESS
      COMMON/C_NFKSPROCESS/NFKSPROCESS
      REAL*8 T(0:NSQAMPSO),T_SAVE(NCOMB,0:NSQAMPSO)
      SAVE T_SAVE
      INTEGER NHEL(NEXTERNAL,NCOMB)
      DATA (NHEL(I,   1),I=1,5) /-1,-1,-1, 1, 1/
      DATA (NHEL(I,   2),I=1,5) /-1,-1,-1, 1,-1/
      DATA (NHEL(I,   3),I=1,5) /-1,-1,-1,-1, 1/
      DATA (NHEL(I,   4),I=1,5) /-1,-1,-1,-1,-1/
      DATA (NHEL(I,   5),I=1,5) /-1,-1, 1, 1, 1/
      DATA (NHEL(I,   6),I=1,5) /-1,-1, 1, 1,-1/
      DATA (NHEL(I,   7),I=1,5) /-1,-1, 1,-1, 1/
      DATA (NHEL(I,   8),I=1,5) /-1,-1, 1,-1,-1/
      DATA (NHEL(I,   9),I=1,5) /-1, 1,-1, 1, 1/
      DATA (NHEL(I,  10),I=1,5) /-1, 1,-1, 1,-1/
      DATA (NHEL(I,  11),I=1,5) /-1, 1,-1,-1, 1/
      DATA (NHEL(I,  12),I=1,5) /-1, 1,-1,-1,-1/
      DATA (NHEL(I,  13),I=1,5) /-1, 1, 1, 1, 1/
      DATA (NHEL(I,  14),I=1,5) /-1, 1, 1, 1,-1/
      DATA (NHEL(I,  15),I=1,5) /-1, 1, 1,-1, 1/
      DATA (NHEL(I,  16),I=1,5) /-1, 1, 1,-1,-1/
      DATA (NHEL(I,  17),I=1,5) / 1,-1,-1, 1, 1/
      DATA (NHEL(I,  18),I=1,5) / 1,-1,-1, 1,-1/
      DATA (NHEL(I,  19),I=1,5) / 1,-1,-1,-1, 1/
      DATA (NHEL(I,  20),I=1,5) / 1,-1,-1,-1,-1/
      DATA (NHEL(I,  21),I=1,5) / 1,-1, 1, 1, 1/
      DATA (NHEL(I,  22),I=1,5) / 1,-1, 1, 1,-1/
      DATA (NHEL(I,  23),I=1,5) / 1,-1, 1,-1, 1/
      DATA (NHEL(I,  24),I=1,5) / 1,-1, 1,-1,-1/
      DATA (NHEL(I,  25),I=1,5) / 1, 1,-1, 1, 1/
      DATA (NHEL(I,  26),I=1,5) / 1, 1,-1, 1,-1/
      DATA (NHEL(I,  27),I=1,5) / 1, 1,-1,-1, 1/
      DATA (NHEL(I,  28),I=1,5) / 1, 1,-1,-1,-1/
      DATA (NHEL(I,  29),I=1,5) / 1, 1, 1, 1, 1/
      DATA (NHEL(I,  30),I=1,5) / 1, 1, 1, 1,-1/
      DATA (NHEL(I,  31),I=1,5) / 1, 1, 1,-1, 1/
      DATA (NHEL(I,  32),I=1,5) / 1, 1, 1,-1,-1/
      LOGICAL GOODHEL(NCOMB), DO_TRY
C     DATA GOODHEL/NCOMB*.FALSE./
      INTEGER MAX_TRY
      DATA MAX_TRY/20/
      INTEGER NTRY
      DATA NTRY/0/
      INTEGER IDEN_FLAVOR(4)
      DATA IDEN_FLAVOR / 12, 12, 12, 12 /
C     ----------
C     BEGIN CODE
C     ----------
      NTRY=NTRY+1
      FLAV_IDX=REAL_FLAVOR_INDEX_D(NFKSPROCESS)
      IF (FLAV_IDX.GE.1.AND.FLAV_IDX.LE.4) IDEN=IDEN_FLAVOR(FLAV_IDX)
      T_SAVE(:,:) = 0D0
      DO I=0,NSQAMPSO
        ANS(I) = 0D0
      ENDDO
      DO IHEL=1,NCOMB
        T(:) = 0D0
C       for the first ps-point, check for helicities that give
C       identical matrix elements
        CALL MATRIX_2(P,NHEL(1,IHEL),FLAV_IDX,T)
        DO I=0,NSQAMPSO
          T_SAVE(IHEL,I)=T(I)
        ENDDO
C       T_IDENT(IHEL)=-1
        DO I=1,IHEL-1
          IF (T(0).EQ.0D0) EXIT
          IF (T_SAVE(I,0).EQ.0D0) CYCLE
          DO J = 0, NSQAMPSO
            IF (ABS(T(J)/T_SAVE(I,J)-1D0) .GT. 1D-12) GOTO 444
          ENDDO
          T_IDENT(IHEL) = I
 444      CONTINUE
        ENDDO
C       add to the sum of helicities
        DO I=1,NSQAMPSO  !keep loop from 1!!
          ANS(I)=ANS(I)+T(I)
        ENDDO
        IF (T(0) .NE. 0D0) THEN
          GOODHEL(IHEL)=.TRUE.
        ENDIF
      ENDDO
      DO I=1,NSQAMPSO
        ANS(I)=ANS(I)/DBLE(IDEN)
        ANS(0)=ANS(0)+ANS(I)
      ENDDO

      IF (NTRY.GE.MAX_TRY) THEN
        DO_TRY = .FALSE.
      ENDIF

      END


      SUBROUTINE SMATRIX2_SPLITORDERS_NTRY_VEC(P,ANS,
     $     DO_TRY,GOODHEL,T_IDENT,IVEC,FLAV_IDX)
C     
C     Generated by MadGraph7 v. %(version)s, %(date)s
C     By the MadGraph7 Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     Returns amplitude squared summed/avg over colors
C     and helicities
C     for the point in phase space P(0:3,NEXTERNAL)
C     
C     Process: a _anti_quark > t t~ _anti_quark [ real = QCD QED ]
C      QCD^2<=4 QED^2<=2
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INCLUDE 'nexternal.inc'
      INTEGER     NCOMB
      PARAMETER ( NCOMB=32)
      INTEGER NSQAMPSO
      PARAMETER (NSQAMPSO=1)
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL),ANS(0:NSQAMPSO)
      INTEGER IVEC,FLAV_IDX
C     
C     LOCAL VARIABLES 
C     
      INTEGER IHEL,IDEN,I,J,T_IDENT(NCOMB)
      REAL*8 T(0:NSQAMPSO),T_SAVE(NCOMB,0:NSQAMPSO)
      SAVE T_SAVE
      INTEGER NHEL(NEXTERNAL,NCOMB)
      DATA (NHEL(I,   1),I=1,5) /-1,-1,-1, 1, 1/
      DATA (NHEL(I,   2),I=1,5) /-1,-1,-1, 1,-1/
      DATA (NHEL(I,   3),I=1,5) /-1,-1,-1,-1, 1/
      DATA (NHEL(I,   4),I=1,5) /-1,-1,-1,-1,-1/
      DATA (NHEL(I,   5),I=1,5) /-1,-1, 1, 1, 1/
      DATA (NHEL(I,   6),I=1,5) /-1,-1, 1, 1,-1/
      DATA (NHEL(I,   7),I=1,5) /-1,-1, 1,-1, 1/
      DATA (NHEL(I,   8),I=1,5) /-1,-1, 1,-1,-1/
      DATA (NHEL(I,   9),I=1,5) /-1, 1,-1, 1, 1/
      DATA (NHEL(I,  10),I=1,5) /-1, 1,-1, 1,-1/
      DATA (NHEL(I,  11),I=1,5) /-1, 1,-1,-1, 1/
      DATA (NHEL(I,  12),I=1,5) /-1, 1,-1,-1,-1/
      DATA (NHEL(I,  13),I=1,5) /-1, 1, 1, 1, 1/
      DATA (NHEL(I,  14),I=1,5) /-1, 1, 1, 1,-1/
      DATA (NHEL(I,  15),I=1,5) /-1, 1, 1,-1, 1/
      DATA (NHEL(I,  16),I=1,5) /-1, 1, 1,-1,-1/
      DATA (NHEL(I,  17),I=1,5) / 1,-1,-1, 1, 1/
      DATA (NHEL(I,  18),I=1,5) / 1,-1,-1, 1,-1/
      DATA (NHEL(I,  19),I=1,5) / 1,-1,-1,-1, 1/
      DATA (NHEL(I,  20),I=1,5) / 1,-1,-1,-1,-1/
      DATA (NHEL(I,  21),I=1,5) / 1,-1, 1, 1, 1/
      DATA (NHEL(I,  22),I=1,5) / 1,-1, 1, 1,-1/
      DATA (NHEL(I,  23),I=1,5) / 1,-1, 1,-1, 1/
      DATA (NHEL(I,  24),I=1,5) / 1,-1, 1,-1,-1/
      DATA (NHEL(I,  25),I=1,5) / 1, 1,-1, 1, 1/
      DATA (NHEL(I,  26),I=1,5) / 1, 1,-1, 1,-1/
      DATA (NHEL(I,  27),I=1,5) / 1, 1,-1,-1, 1/
      DATA (NHEL(I,  28),I=1,5) / 1, 1,-1,-1,-1/
      DATA (NHEL(I,  29),I=1,5) / 1, 1, 1, 1, 1/
      DATA (NHEL(I,  30),I=1,5) / 1, 1, 1, 1,-1/
      DATA (NHEL(I,  31),I=1,5) / 1, 1, 1,-1, 1/
      DATA (NHEL(I,  32),I=1,5) / 1, 1, 1,-1,-1/
      LOGICAL GOODHEL(NCOMB), DO_TRY
C     DATA GOODHEL/NCOMB*.FALSE./
      INTEGER MAX_TRY
      DATA MAX_TRY/20/
      INTEGER NTRY
      DATA NTRY/0/
      INTEGER IDEN_FLAVOR(4)
      DATA IDEN_FLAVOR / 12, 12, 12, 12 /
C     ----------
C     BEGIN CODE
C     ----------
      NTRY=NTRY+1
      IF (FLAV_IDX.GE.1.AND.FLAV_IDX.LE.4) IDEN=IDEN_FLAVOR(FLAV_IDX)
      T_SAVE(:,:) = 0D0
      DO I=0,NSQAMPSO
        ANS(I) = 0D0
      ENDDO
      DO IHEL=1,NCOMB
        T(:) = 0D0
C       for the first ps-point, check for helicities that give
C       identical matrix elements
        CALL MATRIX_2_VEC(P,NHEL(1,IHEL),FLAV_IDX,T,
     $           IVEC)
        DO I=0,NSQAMPSO
          T_SAVE(IHEL,I)=T(I)
        ENDDO
C       T_IDENT(IHEL)=-1
        DO I=1,IHEL-1
          IF (T(0).EQ.0D0) EXIT
          IF (T_SAVE(I,0).EQ.0D0) CYCLE
          DO J = 0, NSQAMPSO
            IF (ABS(T(J)/T_SAVE(I,J)-1D0) .GT. 1D-12) GOTO 444
          ENDDO
          T_IDENT(IHEL) = I
 444      CONTINUE
        ENDDO
C       add to the sum of helicities
        DO I=1,NSQAMPSO  !keep loop from 1!!
          ANS(I)=ANS(I)+T(I)
        ENDDO
        IF (T(0) .NE. 0D0) THEN
          GOODHEL(IHEL)=.TRUE.
        ENDIF
      ENDDO
      DO I=1,NSQAMPSO
        ANS(I)=ANS(I)/DBLE(IDEN)
        ANS(0)=ANS(0)+ANS(I)
      ENDDO

      IF (NTRY.GE.MAX_TRY) THEN
        DO_TRY = .FALSE.
      ENDIF

      END


      SUBROUTINE MATRIX_2(P,NHEL,FLAV_IDX,RES)
C     
C     Generated by MadGraph7 v. %(version)s, %(date)s
C     By the MadGraph7 Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     Returns amplitude squared summed/avg over colors
C     for the point with external lines W(0:6,NEXTERNAL)
C     
C     Process: a _anti_quark > t t~ _anti_quark [ real = QCD QED ]
C      QCD^2<=4 QED^2<=2
C     
      USE ALOHA_OBJECT
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=4)
      INTEGER    NWAVEFUNCS, NCOLOR
      PARAMETER (NWAVEFUNCS=8, NCOLOR=2)
      INTEGER NAMPSO, NSQAMPSO
      PARAMETER (NAMPSO=1, NSQAMPSO=1)
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
      COMPLEX*16 IMAG1
      PARAMETER (IMAG1=(0D0,1D0))
      INCLUDE 'nexternal.inc'
      INCLUDE 'coupl.inc'
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL),FLAV_IDX
      REAL*8 RES(0:NSQAMPSO)
C     
C     LOCAL VARIABLES 
C     
      INTEGER I,J,M,N
      INTEGER IC(NEXTERNAL)
      DATA IC /NEXTERNAL*1/
      INTEGER FLAVOR(NEXTERNAL)
      INTEGER CF(NCOLOR*(NCOLOR+1))
      INTEGER CF_INDEX, DENOM
      COMPLEX*16 ZTEMP, AMP(NGRAPHS), JAMP(NCOLOR,NAMPSO)
      TYPE(ALOHA) W(NWAVEFUNCS)
      COMPLEX*16 TMP_JAMP(3)
C     Flavor table for the FLAV_IDX -> FLAVOR rebuild.
      INTEGER NMASK_FLAV
      PARAMETER (NMASK_FLAV=4)
      INTEGER MASK_J
      INTEGER FLAV_TABLE(NEXTERNAL, NMASK_FLAV)
      DATA FLAV_TABLE / 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 3, 1, 1, 3, 1
     $ , 4, 1, 1, 4 /
C     
C     FUNCTION
C     
      INTEGER SQSOINDEX2
C     
C     COLOR DATA
C     
      DATA DENOM/1/
      DATA (CF(I),I=  1,  2) /9,6/
C     1 T(2,4) T(3,5)
      DATA (CF(I),I=  3,  3) /9/
C     1 T(2,5) T(3,4)
C     ----------
C     BEGIN CODE
C     ----------
      JAMP(:,:) = (0D0,0D0)
      FLAVOR(:) = 1
C     Rebuild FLAVOR(NEXTERNAL) from the resolved flavor index.
      IF (FLAV_IDX .GE. 1 .AND. FLAV_IDX .LE. NMASK_FLAV) THEN
        DO MASK_J = 1, NEXTERNAL
          FLAVOR(MASK_J) = FLAV_TABLE(MASK_J, FLAV_IDX)
        ENDDO
      ELSE
        DO MASK_J = 1, NEXTERNAL
          FLAVOR(MASK_J) = FLAV_TABLE(MASK_J, 1)
        ENDDO
      ENDIF
      CALL VXXXXX(P(0,1),ZERO,NHEL(1),-1,W(1))
      CALL OXXXXX(P(0,2),ZERO,NHEL(2),-1, FLAVOR(2),W(2))
      CALL OXXXXX(P(0,3),MDL_MT,NHEL(3),+1, FLAVOR(3),W(3))
      CALL IXXXXX(P(0,4),MDL_MT,NHEL(4),-1, FLAVOR(4),W(4))
      CALL IXXXXX(P(0,5),ZERO,NHEL(5),-1, FLAVOR(5),W(5))
      CALL FFV1M_1(W(2),W(1),FLV_94,ZERO,ZERO,W(6))
      CALL FFV1P0_3(W(4),W(3),GC_11,ZERO,ZERO,W(7))
C     Amplitude(s) for diagram number 1
      CALL FFV1_0(W(5),W(6),W(7),GC_11,AMP(1))
      CALL FFV1_1(W(3),W(1),GC_2,MDL_MT,MDL_WT,W(6))
      CALL FFV1P0_3(W(5),W(2),GC_11,ZERO,ZERO,W(8))
C     Amplitude(s) for diagram number 2
      CALL FFV1_0(W(4),W(6),W(8),GC_11,AMP(2))
      CALL FFV1_2(W(4),W(1),GC_2,MDL_MT,MDL_WT,W(6))
C     Amplitude(s) for diagram number 3
      CALL FFV1_0(W(6),W(3),W(8),GC_11,AMP(3))
      CALL FFV1M_2(W(5),W(1),FLV_94,ZERO,ZERO,W(6))
C     Amplitude(s) for diagram number 4
      CALL FFV1_0(W(6),W(2),W(7),GC_11,AMP(4))
C     JAMPs contributing to orders QCD=2 QED=1
      TMP_JAMP(2) = AMP(3) +  AMP(4)  ! used 2 times
      TMP_JAMP(1) = AMP(1) +  AMP(2)  ! used 2 times
      TMP_JAMP(3) = TMP_JAMP(2) +  TMP_JAMP(1)  ! used 2 times
      JAMP(1,1) = (5.000000000000000D-01)*TMP_JAMP(3)
      JAMP(2,1) = (-1.666666666666667D-01)*TMP_JAMP(3)

      RES(:) = 0D0
      DO M = 1, NAMPSO
        CF_INDEX = 0
        DO I = 1, NCOLOR
          ZTEMP = (0.D0,0.D0)
          DO J = I, NCOLOR
            CF_INDEX = CF_INDEX+1
            ZTEMP = ZTEMP + CF(CF_INDEX)*JAMP(J,M)
          ENDDO
          DO N = 1, NAMPSO
            RES(SQSOINDEX2(M,N)) = RES(SQSOINDEX2(M,N)) + ZTEMP
     $       *DCONJG(JAMP(I,N))
          ENDDO
        ENDDO

      ENDDO
      RES(:) = RES(:)/DENOM
      DO I=1,NSQAMPSO
        RES(0)=RES(0)+RES(I)
      ENDDO

      END


      RECURSIVE SUBROUTINE MATRIX_2_VEC(P,NHEL,FLAV_IDX,
     $     RES,IVEC)
C     
C     Generated by MadGraph7 v. %(version)s, %(date)s
C     By the MadGraph7 Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     Returns amplitude squared summed/avg over colors
C     for the point with external lines W(0:6,NEXTERNAL)
C     
C     Process: a _anti_quark > t t~ _anti_quark [ real = QCD QED ]
C      QCD^2<=4 QED^2<=2
C     
      USE COUPLINGS
      USE ALOHA_OBJECT
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=4)
      INTEGER    NWAVEFUNCS, NCOLOR
      PARAMETER (NWAVEFUNCS=8, NCOLOR=2)
      INTEGER NAMPSO, NSQAMPSO
      PARAMETER (NAMPSO=1, NSQAMPSO=1)
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
      COMPLEX*16 IMAG1
      PARAMETER (IMAG1=(0D0,1D0))
      INCLUDE 'nexternal.inc'
      INCLUDE 'coupl.inc'
C     
C     ARGUMENTS 
C     
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL),FLAV_IDX
      REAL*8 RES(0:NSQAMPSO)
      INTEGER IVEC
C     
C     LOCAL VARIABLES 
C     
      INTEGER I,J,M,N
      INTEGER IC(NEXTERNAL)
      DATA IC /NEXTERNAL*1/
      INTEGER FLAVOR(NEXTERNAL)
      INTEGER CF(NCOLOR*(NCOLOR+1))
      INTEGER CF_INDEX, DENOM
      COMPLEX*16 ZTEMP, AMP(NGRAPHS), JAMP(NCOLOR,NAMPSO)
      TYPE(ALOHA) W(NWAVEFUNCS)
      COMPLEX*16 TMP_JAMP(3)
C     Flavor table for the FLAV_IDX -> FLAVOR rebuild.
      INTEGER NMASK_FLAV
      PARAMETER (NMASK_FLAV=4)
      INTEGER MASK_J
      INTEGER FLAV_TABLE(NEXTERNAL, NMASK_FLAV)
      DATA FLAV_TABLE / 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 3, 1, 1, 3, 1
     $ , 4, 1, 1, 4 /
C     
C     FUNCTION
C     
      INTEGER SQSOINDEX2
C     
C     COLOR DATA
C     
      DATA DENOM/1/
      DATA (CF(I),I=  1,  2) /9,6/
C     1 T(2,4) T(3,5)
      DATA (CF(I),I=  3,  3) /9/
C     1 T(2,5) T(3,4)
C     ----------
C     BEGIN CODE
C     ----------
      JAMP(:,:) = (0D0,0D0)
      FLAVOR(:) = 1
C     Rebuild FLAVOR(NEXTERNAL) from the resolved flavor index.
      IF (FLAV_IDX .GE. 1 .AND. FLAV_IDX .LE. NMASK_FLAV) THEN
        DO MASK_J = 1, NEXTERNAL
          FLAVOR(MASK_J) = FLAV_TABLE(MASK_J, FLAV_IDX)
        ENDDO
      ELSE
        DO MASK_J = 1, NEXTERNAL
          FLAVOR(MASK_J) = FLAV_TABLE(MASK_J, 1)
        ENDDO
      ENDIF
      CALL VXXXXX(P(0,1),ZERO,NHEL(1),-1,W(1))
      CALL OXXXXX(P(0,2),ZERO,NHEL(2),-1, FLAVOR(2),W(2))
      CALL OXXXXX(P(0,3),MDL_MT,NHEL(3),+1, FLAVOR(3),W(3))
      CALL IXXXXX(P(0,4),MDL_MT,NHEL(4),-1, FLAVOR(4),W(4))
      CALL IXXXXX(P(0,5),ZERO,NHEL(5),-1, FLAVOR(5),W(5))
      CALL FFV1M_1(W(2),W(1),FLV_94,ZERO,ZERO,W(6))
      CALL FFV1P0_3(W(4),W(3),GC_11_VEC(IVEC),ZERO,ZERO,W(7))
C     Amplitude(s) for diagram number 1
      CALL FFV1_0(W(5),W(6),W(7),GC_11_VEC(IVEC),AMP(1))
      CALL FFV1_1(W(3),W(1),GC_2,MDL_MT,MDL_WT,W(6))
      CALL FFV1P0_3(W(5),W(2),GC_11_VEC(IVEC),ZERO,ZERO,W(8))
C     Amplitude(s) for diagram number 2
      CALL FFV1_0(W(4),W(6),W(8),GC_11_VEC(IVEC),AMP(2))
      CALL FFV1_2(W(4),W(1),GC_2,MDL_MT,MDL_WT,W(6))
C     Amplitude(s) for diagram number 3
      CALL FFV1_0(W(6),W(3),W(8),GC_11_VEC(IVEC),AMP(3))
      CALL FFV1M_2(W(5),W(1),FLV_94,ZERO,ZERO,W(6))
C     Amplitude(s) for diagram number 4
      CALL FFV1_0(W(6),W(2),W(7),GC_11_VEC(IVEC),AMP(4))
C     JAMPs contributing to orders QCD=2 QED=1
      TMP_JAMP(2) = AMP(3) +  AMP(4)  ! used 2 times
      TMP_JAMP(1) = AMP(1) +  AMP(2)  ! used 2 times
      TMP_JAMP(3) = TMP_JAMP(2) +  TMP_JAMP(1)  ! used 2 times
      JAMP(1,1) = (5.000000000000000D-01)*TMP_JAMP(3)
      JAMP(2,1) = (-1.666666666666667D-01)*TMP_JAMP(3)

      RES(:) = 0D0
      DO M = 1, NAMPSO
        CF_INDEX = 0
        DO I = 1, NCOLOR
          ZTEMP = (0.D0,0.D0)
          DO J = I, NCOLOR
            CF_INDEX = CF_INDEX+1
            ZTEMP = ZTEMP + CF(CF_INDEX)*JAMP(J,M)
          ENDDO
          DO N = 1, NAMPSO
            RES(SQSOINDEX2(M,N)) = RES(SQSOINDEX2(M,N)) + ZTEMP
     $       *DCONJG(JAMP(I,N))
          ENDDO
        ENDDO

      ENDDO
      RES(:) = RES(:)/DENOM
      DO I=1,NSQAMPSO
        RES(0)=RES(0)+RES(I)
      ENDDO

      END


C     
C     Helper functions to deal with the split orders.
C     

      RECURSIVE INTEGER FUNCTION SQSOINDEX2(AMPORDERA,AMPORDERB)
C     
C     This functions plays the role of the interference matrix. It can
C      be hardcoded or 
C     made more elegant using hashtables if its execution speed ever
C      becomes a relevant
C     factor. From two split order indices of the jamps, it return the
C      corresponding
C     index in the squared order canonical ordering.
C     
C     CONSTANTS
C     
      IMPLICIT NONE
      INTEGER NAMPSO, NSQAMPSO
      PARAMETER (NAMPSO=1, NSQAMPSO=1)
      INTEGER NSPLITORDERS
      PARAMETER (NSPLITORDERS=2)
C     
C     ARGUMENTS
C     
      INTEGER AMPORDERA, AMPORDERB
C     
C     LOCAL VARIABLES
C     
      INTEGER I, SQORDERS(NSPLITORDERS)
      INTEGER AMPSPLITORDERS(NAMPSO,NSPLITORDERS)
      DATA (AMPSPLITORDERS(  1,I),I=  1,  2) /    2,    1/
C     
C     FUNCTION
C     
      INTEGER SQSOINDEX_FROM_ORDERS2
C     
C     BEGIN CODE
C     
      DO I=1,NSPLITORDERS
        SQORDERS(I)=AMPSPLITORDERS(AMPORDERA,I)
     $   +AMPSPLITORDERS(AMPORDERB,I)
      ENDDO
      SQSOINDEX2=SQSOINDEX_FROM_ORDERS2(SQORDERS)
      END



      RECURSIVE INTEGER FUNCTION SQSOINDEX_FROM_ORDERS2(ORDERS)
C     
C     From a list of values for the split orders, this function
C      returns the
C     corresponding index in the squared orders canonical ordering.
C     
      IMPLICIT NONE
      INTEGER NSQAMPSO
      PARAMETER (NSQAMPSO=1)
      INTEGER NSPLITORDERS
      PARAMETER (NSPLITORDERS=2)
C     
C     ARGUMENTS
C     
      INTEGER ORDERS(NSPLITORDERS)
C     
C     LOCAL VARIABLES
C     
      INTEGER I,J
      INTEGER SQSPLITORDERS(NSQAMPSO,NSPLITORDERS)
C     the values listed below are for QCD, QED
      DATA (SQSPLITORDERS(  1,I),I=  1,  2) /    4,    2/
C     
C     BEGIN CODE
C     
      DO I=1,NSQAMPSO
        DO J=1,NSPLITORDERS
          IF (ORDERS(J).NE.SQSPLITORDERS(I,J)) GOTO 1009
        ENDDO
        SQSOINDEX_FROM_ORDERS2 = I
        RETURN
 1009   CONTINUE
      ENDDO

      WRITE(*,*) 'ERROR:: Stopping function sqsoindex_from_orders'
      WRITE(*,*) 'Could not find squared orders ',(ORDERS(I),I=1
     $ ,NSPLITORDERS)
      STOP

      END



      RECURSIVE INTEGER FUNCTION GETORDPOWFROMINDEX2(IORDER, INDX)
C     
C     Return the power of the IORDER-th order appearing at position
C      INDX
C     in the split-orders output
C     
      IMPLICIT NONE
      INTEGER NSQAMPSO
      PARAMETER (NSQAMPSO=1)
      INTEGER NSPLITORDERS
      PARAMETER (NSPLITORDERS=2)
C     
C     ARGUMENTS
C     
      INTEGER IORDER, INDX
C     
C     LOCAL VARIABLES
C     
      INTEGER I
      INTEGER SQSPLITORDERS(NSQAMPSO,NSPLITORDERS)
C     the values listed below are for QCD, QED
      DATA (SQSPLITORDERS(  1,I),I=  1,  2) /    4,    2/
C     
C     BEGIN CODE
C     
      IF (IORDER.GT.NSPLITORDERS.OR.IORDER.LT.1) THEN
        WRITE(*,*) 'INVALID IORDER 2', IORDER
        WRITE(*,*) 'SHOULD BE BETWEEN 1 AND ', NSPLITORDERS
        STOP
      ENDIF

      IF (INDX.GT.NSQAMPSO.OR.INDX.LT.1) THEN
        WRITE(*,*) 'INVALID INDX 2', INDX
        WRITE(*,*) 'SHOULD BE BETWEEN 1 AND ', NSQAMPSO
        STOP
      ENDIF

      GETORDPOWFROMINDEX2=SQSPLITORDERS(INDX, IORDER)
      END



      RECURSIVE SUBROUTINE GET_NSQSO_REAL2(NSQSO)
C     
C     Simple subroutine returning the number of squared split order
C     contributions returned in ANS when calling SMATRIX_SPLITORDERS
C     
      IMPLICIT NONE
      INTEGER NSQAMPSO
      PARAMETER (NSQAMPSO=1)
      INTEGER NSQSO

      NSQSO=NSQAMPSO

      END

