

      DOUBLE PRECISION FUNCTION DLUM()
      IMPLICIT NONE
      INTEGER NFKSPROCESS
      COMMON/C_NFKSPROCESS/NFKSPROCESS
      IF (NFKSPROCESS.EQ.1) THEN
        CALL DLUM_1(DLUM)
      ELSEIF (NFKSPROCESS.EQ.2) THEN
        CALL DLUM_1(DLUM)
      ELSEIF (NFKSPROCESS.EQ.3) THEN
        CALL DLUM_1(DLUM)
      ELSEIF (NFKSPROCESS.EQ.4) THEN
        CALL DLUM_1(DLUM)
      ELSEIF (NFKSPROCESS.EQ.5) THEN
        CALL DLUM_1(DLUM)
      ELSEIF (NFKSPROCESS.EQ.6) THEN
        CALL DLUM_1(DLUM)
      ELSEIF (NFKSPROCESS.EQ.7) THEN
        CALL DLUM_1(DLUM)
      ELSEIF (NFKSPROCESS.EQ.8) THEN
        CALL DLUM_1(DLUM)
      ELSEIF (NFKSPROCESS.EQ.9) THEN
        CALL DLUM_1(DLUM)
      ELSEIF (NFKSPROCESS.EQ.10) THEN
        CALL DLUM_1(DLUM)
      ELSEIF (NFKSPROCESS.EQ.11) THEN
        CALL DLUM_1(DLUM)
      ELSEIF (NFKSPROCESS.EQ.12) THEN
        CALL DLUM_1(DLUM)
      ELSEIF (NFKSPROCESS.EQ.13) THEN
        CALL DLUM_1(DLUM)
      ELSEIF (NFKSPROCESS.EQ.14) THEN
        CALL DLUM_1(DLUM)
      ELSEIF (NFKSPROCESS.EQ.15) THEN
        CALL DLUM_1(DLUM)
      ELSEIF (NFKSPROCESS.EQ.16) THEN
        CALL DLUM_1(DLUM)
      ELSEIF (NFKSPROCESS.EQ.17) THEN
        CALL DLUM_2(DLUM)
      ELSEIF (NFKSPROCESS.EQ.18) THEN
        CALL DLUM_2(DLUM)
      ELSEIF (NFKSPROCESS.EQ.19) THEN
        CALL DLUM_2(DLUM)
      ELSEIF (NFKSPROCESS.EQ.20) THEN
        CALL DLUM_2(DLUM)
      ELSEIF (NFKSPROCESS.EQ.21) THEN
        CALL DLUM_3(DLUM)
      ELSEIF (NFKSPROCESS.EQ.22) THEN
        CALL DLUM_3(DLUM)
      ELSEIF (NFKSPROCESS.EQ.23) THEN
        CALL DLUM_3(DLUM)
      ELSEIF (NFKSPROCESS.EQ.24) THEN
        CALL DLUM_3(DLUM)
      ELSEIF (NFKSPROCESS.EQ.25) THEN
        CALL DLUM_3(DLUM)
      ELSEIF (NFKSPROCESS.EQ.26) THEN
        CALL DLUM_3(DLUM)
      ELSEIF (NFKSPROCESS.EQ.27) THEN
        CALL DLUM_3(DLUM)
      ELSEIF (NFKSPROCESS.EQ.28) THEN
        CALL DLUM_3(DLUM)
      ELSEIF (NFKSPROCESS.EQ.29) THEN
        CALL DLUM_3(DLUM)
      ELSEIF (NFKSPROCESS.EQ.30) THEN
        CALL DLUM_3(DLUM)
      ELSEIF (NFKSPROCESS.EQ.31) THEN
        CALL DLUM_3(DLUM)
      ELSEIF (NFKSPROCESS.EQ.32) THEN
        CALL DLUM_3(DLUM)
      ELSEIF (NFKSPROCESS.EQ.33) THEN
        CALL DLUM_3(DLUM)
      ELSEIF (NFKSPROCESS.EQ.34) THEN
        CALL DLUM_3(DLUM)
      ELSEIF (NFKSPROCESS.EQ.35) THEN
        CALL DLUM_3(DLUM)
      ELSEIF (NFKSPROCESS.EQ.36) THEN
        CALL DLUM_3(DLUM)
      ELSEIF (NFKSPROCESS.EQ.37) THEN
        CALL DLUM_4(DLUM)
      ELSEIF (NFKSPROCESS.EQ.38) THEN
        CALL DLUM_4(DLUM)
      ELSEIF (NFKSPROCESS.EQ.39) THEN
        CALL DLUM_4(DLUM)
      ELSEIF (NFKSPROCESS.EQ.40) THEN
        CALL DLUM_4(DLUM)
      ELSEIF (NFKSPROCESS.EQ.41) THEN
        CALL DLUM_5(DLUM)
      ELSEIF (NFKSPROCESS.EQ.42) THEN
        CALL DLUM_5(DLUM)
      ELSEIF (NFKSPROCESS.EQ.43) THEN
        CALL DLUM_5(DLUM)
      ELSEIF (NFKSPROCESS.EQ.44) THEN
        CALL DLUM_5(DLUM)
      ELSEIF (NFKSPROCESS.EQ.45) THEN
        CALL DLUM_6(DLUM)
      ELSEIF (NFKSPROCESS.EQ.46) THEN
        CALL DLUM_6(DLUM)
      ELSEIF (NFKSPROCESS.EQ.47) THEN
        CALL DLUM_6(DLUM)
      ELSEIF (NFKSPROCESS.EQ.48) THEN
        CALL DLUM_6(DLUM)
      ELSE
        WRITE(*,*) 'ERROR: invalid n in dlum :', NFKSPROCESS
        STOP
      ENDIF
      RETURN
      END



      DOUBLE PRECISION FUNCTION DLUM_VEC(NFKSPROCESS)
      IMPLICIT NONE
      INTEGER NFKSPROCESS
      IF (NFKSPROCESS.EQ.1) THEN
        CALL DLUM_1(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.2) THEN
        CALL DLUM_1(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.3) THEN
        CALL DLUM_1(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.4) THEN
        CALL DLUM_1(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.5) THEN
        CALL DLUM_1(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.6) THEN
        CALL DLUM_1(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.7) THEN
        CALL DLUM_1(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.8) THEN
        CALL DLUM_1(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.9) THEN
        CALL DLUM_1(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.10) THEN
        CALL DLUM_1(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.11) THEN
        CALL DLUM_1(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.12) THEN
        CALL DLUM_1(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.13) THEN
        CALL DLUM_1(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.14) THEN
        CALL DLUM_1(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.15) THEN
        CALL DLUM_1(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.16) THEN
        CALL DLUM_1(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.17) THEN
        CALL DLUM_2(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.18) THEN
        CALL DLUM_2(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.19) THEN
        CALL DLUM_2(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.20) THEN
        CALL DLUM_2(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.21) THEN
        CALL DLUM_3(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.22) THEN
        CALL DLUM_3(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.23) THEN
        CALL DLUM_3(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.24) THEN
        CALL DLUM_3(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.25) THEN
        CALL DLUM_3(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.26) THEN
        CALL DLUM_3(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.27) THEN
        CALL DLUM_3(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.28) THEN
        CALL DLUM_3(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.29) THEN
        CALL DLUM_3(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.30) THEN
        CALL DLUM_3(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.31) THEN
        CALL DLUM_3(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.32) THEN
        CALL DLUM_3(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.33) THEN
        CALL DLUM_3(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.34) THEN
        CALL DLUM_3(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.35) THEN
        CALL DLUM_3(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.36) THEN
        CALL DLUM_3(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.37) THEN
        CALL DLUM_4(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.38) THEN
        CALL DLUM_4(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.39) THEN
        CALL DLUM_4(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.40) THEN
        CALL DLUM_4(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.41) THEN
        CALL DLUM_5(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.42) THEN
        CALL DLUM_5(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.43) THEN
        CALL DLUM_5(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.44) THEN
        CALL DLUM_5(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.45) THEN
        CALL DLUM_6(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.46) THEN
        CALL DLUM_6(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.47) THEN
        CALL DLUM_6(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.48) THEN
        CALL DLUM_6(DLUM_VEC)
      ELSE
        WRITE(*,*) 'ERROR: invalid n in dlum_vec :', NFKSPROCESS
        STOP
      ENDIF
      RETURN
      END

