

      DOUBLE PRECISION FUNCTION DLUM()
      IMPLICIT NONE
      INTEGER NFKSPROCESS
      COMMON/C_NFKSPROCESS/NFKSPROCESS
      IF (NFKSPROCESS.EQ.1) THEN
        CALL DLUM_1(DLUM)
      ELSEIF (NFKSPROCESS.EQ.2) THEN
        CALL DLUM_1(DLUM)
      ELSEIF (NFKSPROCESS.EQ.3) THEN
        CALL DLUM_1(DLUM)
      ELSEIF (NFKSPROCESS.EQ.4) THEN
        CALL DLUM_2(DLUM)
      ELSEIF (NFKSPROCESS.EQ.5) THEN
        CALL DLUM_2(DLUM)
      ELSEIF (NFKSPROCESS.EQ.6) THEN
        CALL DLUM_2(DLUM)
      ELSEIF (NFKSPROCESS.EQ.7) THEN
        CALL DLUM_2(DLUM)
      ELSEIF (NFKSPROCESS.EQ.8) THEN
        CALL DLUM_3(DLUM)
      ELSEIF (NFKSPROCESS.EQ.9) THEN
        CALL DLUM_3(DLUM)
      ELSEIF (NFKSPROCESS.EQ.10) THEN
        CALL DLUM_3(DLUM)
      ELSEIF (NFKSPROCESS.EQ.11) THEN
        CALL DLUM_3(DLUM)
      ELSE
        WRITE(*,*) 'ERROR: invalid n in dlum :', NFKSPROCESS
        STOP
      ENDIF
      RETURN
      END



      DOUBLE PRECISION FUNCTION DLUM_VEC(NFKSPROCESS)
      IMPLICIT NONE
      INTEGER NFKSPROCESS
      IF (NFKSPROCESS.EQ.1) THEN
        CALL DLUM_1(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.2) THEN
        CALL DLUM_1(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.3) THEN
        CALL DLUM_1(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.4) THEN
        CALL DLUM_2(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.5) THEN
        CALL DLUM_2(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.6) THEN
        CALL DLUM_2(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.7) THEN
        CALL DLUM_2(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.8) THEN
        CALL DLUM_3(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.9) THEN
        CALL DLUM_3(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.10) THEN
        CALL DLUM_3(DLUM_VEC)
      ELSEIF (NFKSPROCESS.EQ.11) THEN
        CALL DLUM_3(DLUM_VEC)
      ELSE
        WRITE(*,*) 'ERROR: invalid n in dlum_vec :', NFKSPROCESS
        STOP
      ENDIF
      RETURN
      END

