      SUBROUTINE SBORN(P,ANS_SUMMED)
C     
C     Generated by MadGraph7 v. %(version)s, %(date)s
C     By the MadGraph7 Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     
C     Return the sum of the split orders which are required in
C      orders.inc (BORN_ORDERS)
C     Also the values needed for the counterterms are stored in the
C      C_BORN_CNT common block
C     
C     
C     Process: g g > t t~ [ real = QCD QED ] QCD^2<=4 QED^2<=2
C     
C     
C     CONSTANTS
C     
      IMPLICIT NONE
      INCLUDE 'nexternal.inc'
      INTEGER NAMPSO, NSQAMPSO
      PARAMETER (NAMPSO=1, NSQAMPSO=1)
      INTEGER NGRAPHS
      PARAMETER (NGRAPHS=   3)
C     
C     ARGUMENTS
C     
      REAL*8 P(0:3,NEXTERNAL-1)
      DOUBLE PRECISION ANS_SUMMED
C     
C     VARIABLES
C     
      INTEGER I,J,K
      INCLUDE 'has_ewsudakov.inc'
      INTEGER NORD_INTEGRATED_BORN
      INCLUDE 'orders.inc'
      COMPLEX*16 ANS(2,0:NSQAMPSO), ANS_CNT(2, NSPLITORDERS)
      LOGICAL KEEP_ORDER(NSQAMPSO), KEEP_ORDER_CNT(NSPLITORDERS,
     $  NSQAMPSO), FIRSTTIME
      DATA KEEP_ORDER / NSQAMPSO * .TRUE. /
      LOGICAL KEEP_ORDER_BORN(NSQAMPSO)
      COMMON /C_KEEP_ORDER_B/ KEEP_ORDER_BORN
      COMMON /C_KEEP_ORDER_CNT/ KEEP_ORDER_CNT
      COMMON /C_BORN_CNT/ ANS_CNT
      INTEGER ORD_SUBTRACT
      DATA FIRSTTIME / .TRUE. /
      INTEGER AMP_ORDERS(NSPLITORDERS)
      DOUBLE PRECISION TINY
      PARAMETER (TINY = 1D-12)
      DOUBLE PRECISION MAX_VAL
      DOUBLE PRECISION       WGT_ME_BORN,WGT_ME_REAL
      COMMON /C_WGT_ME_TREE/ WGT_ME_BORN,WGT_ME_REAL

      DOUBLE PRECISION AMP2B(3), JAMP2B(0:2,0:NAMPSO)
      COMMON/TO_AMPS_BORN/  AMP2B,       JAMP2B
      DOUBLE PRECISION AMP2(3), JAMP2(0:2)
      COMMON/TO_AMPS/  AMP2,       JAMP2
      LOGICAL SPLIT_TYPE_USED(NSPLITORDERS)
      COMMON/TO_SPLIT_TYPE_USED/SPLIT_TYPE_USED
      LOGICAL FORCE_IJGLU_ZERO
      COMMON /TO_FORCE_IJGLU/ FORCE_IJGLU_ZERO
C     
C     FUNCTIONS
C     
      INTEGER GETORDPOWFROMINDEX_B
      INTEGER ORDERS_TO_AMP_SPLIT_POS
C     
C     BEGIN CODE
C     
C     look for orders which match the born order constraint

      FORCE_IJGLU_ZERO = .FALSE.

      IF (FIRSTTIME) THEN
        DO I = 1, NSQAMPSO
C         this is for the orders of the born to integrate
          DO J = 1, NSPLITORDERS
            IF(GETORDPOWFROMINDEX_B(J, I) .GT. BORN_ORDERS(J)) THEN
              KEEP_ORDER(I) = .FALSE.
              EXIT
            ENDIF
          ENDDO
          KEEP_ORDER_BORN = KEEP_ORDER

C         this is for the orders of the counterterms
          DO J = 1, NSPLITORDERS
            KEEP_ORDER_CNT(J,I) = .TRUE.
            DO K = 1, NSPLITORDERS
              IF (J.EQ.K) THEN
                ORD_SUBTRACT=2
              ELSE
                ORD_SUBTRACT=0
              ENDIF
              IF(GETORDPOWFROMINDEX_B(K, I) .GT. NLO_ORDERS(K)
     $         -ORD_SUBTRACT) THEN
                KEEP_ORDER_CNT(J,I) = .FALSE.
                EXIT
              ENDIF
            ENDDO
          ENDDO

          NORD_INTEGRATED_BORN = 0
          IF (KEEP_ORDER(I)) THEN
            NORD_INTEGRATED_BORN = NORD_INTEGRATED_BORN + 1
C           write(*,*) 'BORN: keeping split order ', i
C           else
C           write(*,*) 'BORN: not keeping split order ', i
          ENDIF
        ENDDO

C       check that, if one include the sudakov corrections, there is
C        at most one contribution to be integrated at LO
        IF (HAS_EWSUDAKOV.AND.NORD_INTEGRATED_BORN.GT.1) THEN
          WRITE(*,*) 'ERROR in born.f, cannot compute Sudakov EW'
     $     //' corrections with more than one Born coupling'
     $     //' combination to be integrated.Found',
     $      NORD_INTEGRATED_BORN
          STOP 1
        ENDIF

        DO J = 1, NSPLITORDERS
          WRITE(*,*) 'counterterm S.O', J, ORDERNAMES(J)
          DO I = 1, NSQAMPSO
            IF (KEEP_ORDER_CNT(J,I)) THEN
              WRITE(*,*) 'BORN: keeping split order', I
            ELSE
              WRITE(*,*) 'BORN: not keeping split order', I
            ENDIF
          ENDDO
        ENDDO
        FIRSTTIME = .FALSE.
      ENDIF

      CALL SBORN_SPLITORDERS(P,ANS)

C     the born to be integrated
      ANS_SUMMED = 0D0
      MAX_VAL = 0D0

C     reset the amp_split array
      AMP_SPLIT(1:AMP_SPLIT_SIZE) = 0D0
      AMP_SPLIT_CNT(1:AMP_SPLIT_SIZE,1:2,1:NSPLITORDERS) = DCMPLX(0D0
     $ ,0D0)

      DO I = 1, NSQAMPSO
        MAX_VAL = MAX(MAX_VAL, ABS(ANS(1,I)))
      ENDDO
      DO I = 1, NSQAMPSO
        IF (KEEP_ORDER(I)) THEN
          ANS_SUMMED = ANS_SUMMED + ANS(1,I)
C         keep track of the separate pieces correspoinding to
C          different coupling combinations
          DO J = 1, NSPLITORDERS
            AMP_ORDERS(J) = GETORDPOWFROMINDEX_B(J, I)
          ENDDO
          IF(ABS(ANS(1,I)).GT.MAX_VAL*TINY)
     $      AMP_SPLIT(ORDERS_TO_AMP_SPLIT_POS(AMP_ORDERS)) = ANS(1,I)
        ENDIF
      ENDDO
C     this is to avoid fake non-zero contributions
      IF (ABS(ANS_SUMMED).LT.MAX_VAL*TINY) ANS_SUMMED=0D0

      WGT_ME_BORN=ANS_SUMMED

C     fill the amp2 and jamp2 arrays
      AMP2(1:NGRAPHS)=AMP2B(1:NGRAPHS)  ! amp2 just needs to be copyed

      DO I = 0, INT(JAMP2B(0,0))
        JAMP2(I)=0D0
        DO J = 1, NAMPSO
C         here sum all, this may be refined later
          JAMP2(I)=JAMP2(I)+JAMP2B(I,J)
        ENDDO
      ENDDO


C     quantities for the counterterms
      DO J = 1, NSPLITORDERS
        ANS_CNT(1:2,J) = (0D0, 0D0)
        IF (.NOT.SPLIT_TYPE_USED(J)) CYCLE
        DO I = 1, NSQAMPSO
          IF (KEEP_ORDER_CNT(J,I)) THEN
            ANS_CNT(1,J) = ANS_CNT(1,J) + ANS(1,I)
            ANS_CNT(2,J) = ANS_CNT(2,J) + ANS(2,I)
C           keep track of the separate pieces also for counterterms
            DO K = 1, NSPLITORDERS
              AMP_ORDERS(K) = GETORDPOWFROMINDEX_B(K, I)
C             take into account the fact that the counterterm for a
C              given split order
C             will be multiplied by the corresponding squared coupling
              IF (K.EQ.J) AMP_ORDERS(K) = AMP_ORDERS(K) + 2
            ENDDO
C           this is to avoid fake non-zero contributions
            IF (ABS(ANS(1,I)).GT.MAX_VAL*TINY)
     $        AMP_SPLIT_CNT(ORDERS_TO_AMP_SPLIT_POS(AMP_ORDERS),1,J) =
     $        ANS(1,I)
            IF (ABS(ANS(2,I)).GT.MAX_VAL*TINY)
     $        AMP_SPLIT_CNT(ORDERS_TO_AMP_SPLIT_POS(AMP_ORDERS),2,J) =
     $        ANS(2,I)
          ENDIF
        ENDDO
C       this is to avoid fake non-zero contributions
        IF (ABS(ANS_CNT(1,J)).LT.MAX_VAL*TINY) ANS_CNT(1,J)=(0D0,0D0)
        IF (ABS(ANS_CNT(2,J)).LT.MAX_VAL*TINY) ANS_CNT(2,J)=(0D0,0D0)
      ENDDO


 999  RETURN
      END





      SUBROUTINE SBORN_ONEHEL(P,NHEL,HELL,ANS_SUMMED)
C     
C     Generated by MadGraph7 v. %(version)s, %(date)s
C     By the MadGraph7 Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     
C     Return the sum of the split orders which are required in
C      orders.inc (BORN_ORDERS)
C     It works for a single set of helicities, passed by NHEL
C     Also the values needed for the counterterms are stored in the
C      C_BORN_CNT common block
C     
C     
C     Process: g g > t t~ [ real = QCD QED ] QCD^2<=4 QED^2<=2
C     
C     
C     CONSTANTS
C     
      IMPLICIT NONE
      INCLUDE 'nexternal.inc'
      INTEGER NAMPSO, NSQAMPSO
      PARAMETER (NAMPSO=1, NSQAMPSO=1)
      INTEGER NGRAPHS
      PARAMETER (NGRAPHS=   3)
C     
C     ARGUMENTS
C     
      REAL*8 P(0:3,NEXTERNAL-1)
      INTEGER NHEL(NEXTERNAL-1)
      INTEGER HELL
      DOUBLE PRECISION ANS_SUMMED
C     
C     VARIABLES
C     
      INTEGER I,J,K
      INCLUDE 'orders.inc'
      COMPLEX*16 ANS(2,NSQAMPSO)
      REAL*8 BORNS(2,0:NSQAMPSO)
      LOGICAL KEEP_ORDER(NSQAMPSO)
      COMMON /C_KEEP_ORDER_B/ KEEP_ORDER

      LOGICAL KEEP_ORDER_CNT(NSPLITORDERS, NSQAMPSO)
      COMMON /C_KEEP_ORDER_CNT/ KEEP_ORDER_CNT

      INTEGER AMP_ORDERS(NSPLITORDERS)
      DOUBLE PRECISION TINY
      PARAMETER (TINY = 1D-12)
      DOUBLE PRECISION MAX_VAL
      INCLUDE 'ewsudakov_haslo.inc'
      DOUBLE COMPLEX AMP_SPLIT_EWSUD(AMP_SPLIT_SIZE)
      COMMON /TO_AMP_SPLIT_EWSUD/ AMP_SPLIT_EWSUD
      DOUBLE COMPLEX AMP_SPLIT_EWSUD_LO2(AMP_SPLIT_SIZE)
      COMMON /TO_AMP_SPLIT_EWSUD_LO2/ AMP_SPLIT_EWSUD_LO2
      INTEGER IDEN
      LOGICAL FORCE_IJGLU_ZERO
      COMMON /TO_FORCE_IJGLU/ FORCE_IJGLU_ZERO
      INTEGER IDEN_VALUES(10)
      DATA IDEN_VALUES /256, 256, 256, 256, 256, 256, 256, 256, 256,
     $  256/
      INTEGER NFKSPROCESS
      COMMON/C_NFKSPROCESS/NFKSPROCESS
C     
C     FUNCTIONS
C     
      INTEGER GETORDPOWFROMINDEX_B
      INTEGER ORDERS_TO_AMP_SPLIT_POS
C     
C     stuff for the LO2
      INTEGER LO2_ORDERS(NSPLITORDERS)
      LOGICAL ORDERS_EQUAL
      EXTERNAL ORDERS_EQUAL
C     
C     BEGIN CODE
C     
C     look for orders which match the born order constraint

      IDEN=IDEN_VALUES(NFKSPROCESS)
      FORCE_IJGLU_ZERO = .TRUE.

      CALL BORN(P,NHEL,HELL,ANS,BORNS)

      ANS_SUMMED = 0D0
      MAX_VAL = 0D0

C     reset the amp_split array
      AMP_SPLIT_EWSUD(1:AMP_SPLIT_SIZE) = DCMPLX(0D0,0D0)
      AMP_SPLIT_EWSUD_LO2(1:AMP_SPLIT_SIZE) = DCMPLX(0D0,0D0)

      DO I = 1, NSQAMPSO
        MAX_VAL = MAX(MAX_VAL, ABS(ANS(1,I)))
      ENDDO

      CALL GET_LO2_ORDERS(LO2_ORDERS)

      DO I = 1, NSQAMPSO
        IF (KEEP_ORDER(I)) THEN
          ANS_SUMMED = ANS_SUMMED + ANS(1,I) / IDEN
          DO J = 1, NSPLITORDERS
            AMP_ORDERS(J) = GETORDPOWFROMINDEX_B(J, I)
          ENDDO
C         amp_split_ewsud(orders_to_amp_split_pos(amp_orders)) =
C          ans(1,I)
          IF(ABS(ANS(1,I)).GT.MAX_VAL*TINY)
     $      AMP_SPLIT_EWSUD(ORDERS_TO_AMP_SPLIT_POS(AMP_ORDERS)) =
     $      ANS(1,I) / IDEN
        ENDIF
C       the following is for the LO2
        IF (HAS_LO2) THEN
          DO J = 1, NSPLITORDERS
            AMP_ORDERS(J) = GETORDPOWFROMINDEX_B(J, I)
          ENDDO
          IF (ORDERS_EQUAL(AMP_ORDERS, LO2_ORDERS)) THEN
            IF(ABS(ANS(1,I)).GT.MAX_VAL*TINY)
     $        AMP_SPLIT_EWSUD_LO2(ORDERS_TO_AMP_SPLIT_POS(AMP_ORDERS))
     $        = ANS(1,I) / IDEN
          ENDIF
        ENDIF
      ENDDO

C     this is to avoid fake non-zero contributions
      IF (ABS(ANS_SUMMED).LT.MAX_VAL*TINY) ANS_SUMMED=0D0

      RETURN
      END




      SUBROUTINE SBORN_SPLITORDERS(P1,ANS)
C     
C     Generated by MadGraph7 v. %(version)s, %(date)s
C     By the MadGraph7 Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     RETURNS AMPLITUDE SQUARED SUMMED/AVG OVER COLORS
C     AND HELICITIES
C     FOR THE POINT IN PHASE SPACE P1(0:3,NEXTERNAL-1)
C     
C     Process: g g > t t~ [ real = QCD QED ] QCD^2<=4 QED^2<=2
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INCLUDE 'nexternal.inc'
      INCLUDE 'born_nhel.inc'
      INTEGER     NCOMB
      PARAMETER ( NCOMB=  16 )
      INTEGER NAMPSO, NSQAMPSO
      PARAMETER (NAMPSO=1, NSQAMPSO=1)
      INTEGER    THEL
      PARAMETER (THEL=NCOMB*10)
      INTEGER NGRAPHS
      PARAMETER (NGRAPHS=   3)
C     
C     ARGUMENTS
C     
      REAL*8 P1(0:3,NEXTERNAL-1)
      COMPLEX*16 ANS(2,0:NSQAMPSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER IHEL,IDEN,I,J,JJ,GLU_IJ
      REAL*8 BORNS(2,0:NSQAMPSO)
      COMPLEX*16 BORNTILDE
      INTEGER NTRY(10)
      DATA NTRY /10*0/
      COMPLEX*16 T(2,NSQAMPSO)
      INTEGER NHEL(NEXTERNAL-1,NCOMB)
      DATA (NHEL(I,   1),I=1,4) /-1,-1,-1, 1/
      DATA (NHEL(I,   2),I=1,4) /-1,-1,-1,-1/
      DATA (NHEL(I,   3),I=1,4) /-1,-1, 1, 1/
      DATA (NHEL(I,   4),I=1,4) /-1,-1, 1,-1/
      DATA (NHEL(I,   5),I=1,4) /-1, 1,-1, 1/
      DATA (NHEL(I,   6),I=1,4) /-1, 1,-1,-1/
      DATA (NHEL(I,   7),I=1,4) /-1, 1, 1, 1/
      DATA (NHEL(I,   8),I=1,4) /-1, 1, 1,-1/
      DATA (NHEL(I,   9),I=1,4) / 1,-1,-1, 1/
      DATA (NHEL(I,  10),I=1,4) / 1,-1,-1,-1/
      DATA (NHEL(I,  11),I=1,4) / 1,-1, 1, 1/
      DATA (NHEL(I,  12),I=1,4) / 1,-1, 1,-1/
      DATA (NHEL(I,  13),I=1,4) / 1, 1,-1, 1/
      DATA (NHEL(I,  14),I=1,4) / 1, 1,-1,-1/
      DATA (NHEL(I,  15),I=1,4) / 1, 1, 1, 1/
      DATA (NHEL(I,  16),I=1,4) / 1, 1, 1,-1/
      INTEGER IDEN_VALUES(10)
      DATA IDEN_VALUES /256, 256, 256, 256, 256, 256, 256, 256, 256,
     $  256/
      INTEGER IJ_VALUES(10)
      DATA IJ_VALUES /1, 1, 1, 1, 2, 2, 2, 2, 0, 0/
C     
C     GLOBAL VARIABLES
C     
      DOUBLE PRECISION AMP2(NGRAPHS), JAMP2(0:2,0:NAMPSO)
      COMMON/TO_AMPS_BORN/  AMP2,       JAMP2
      DATA JAMP2(0,0) /   2/
      LOGICAL GOODHEL(NCOMB,10)
      COMMON /C_GOODHEL/GOODHEL
      DOUBLE COMPLEX SAVEAMP(NGRAPHS,MAX_BHEL)
      COMMON/TO_SAVEAMP/SAVEAMP
      DOUBLE PRECISION SAVEMOM(NEXTERNAL-1,2)
      COMMON/TO_SAVEMOM/SAVEMOM
      DOUBLE PRECISION HEL_FAC
      INTEGER GET_HEL,SKIP(10)
      COMMON/CBORN/HEL_FAC,GET_HEL,SKIP
      LOGICAL CALCULATEDBORN
      COMMON/CCALCULATEDBORN/CALCULATEDBORN
      INTEGER NFKSPROCESS
      COMMON/C_NFKSPROCESS/NFKSPROCESS
      LOGICAL COND_IJ
C     ----------
C     BEGIN CODE
C     ----------
      IDEN=IDEN_VALUES(NFKSPROCESS)
      GLU_IJ = IJ_VALUES(NFKSPROCESS)
      NTRY(NFKSPROCESS)=NTRY(NFKSPROCESS)+1
      IF (NTRY(NFKSPROCESS).LT.2) THEN
        IF (GLU_IJ.EQ.0) THEN
          SKIP(NFKSPROCESS)=0
        ELSE
          SKIP(NFKSPROCESS)=1
          DO WHILE(NHEL(GLU_IJ ,SKIP(NFKSPROCESS)).NE.-NHEL(GLU_IJ ,1))
            SKIP(NFKSPROCESS)=SKIP(NFKSPROCESS)+1
          ENDDO
          SKIP(NFKSPROCESS)=SKIP(NFKSPROCESS)-1
        ENDIF
      ENDIF
      DO JJ=1,NGRAPHS
        AMP2(JJ)=0D0
      ENDDO
      DO I=0,NAMPSO
        DO JJ=1,INT(JAMP2(0,0))
          JAMP2(JJ,I)=0D0
        ENDDO
      ENDDO
      IF (CALCULATEDBORN) THEN
        DO J=1,NEXTERNAL-1
          IF (SAVEMOM(J,1).NE.P1(0,J) .OR. SAVEMOM(J,2).NE.P1(3,J))
     $      THEN
            CALCULATEDBORN=.FALSE.
            WRITE (*,*) 'momenta not the same in Born'
            STOP
          ENDIF
        ENDDO
      ENDIF
      IF (.NOT.CALCULATEDBORN) THEN
        DO J=1,NEXTERNAL-1
          SAVEMOM(J,1)=P1(0,J)
          SAVEMOM(J,2)=P1(3,J)
        ENDDO
        DO J=1,MAX_BHEL
          DO JJ=1,NGRAPHS
            SAVEAMP(JJ,J)=(0D0,0D0)
          ENDDO
        ENDDO
      ENDIF
      DO I=0,NSQAMPSO
        ANS(1,I) = 0D0
        ANS(2,I) = 0D0
      ENDDO
      HEL_FAC=1D0
      DO IHEL=1,NCOMB
C       the following lines are to avoid segfaults when glu_ij=0
        COND_IJ=SKIP(NFKSPROCESS).EQ.0
        IF (.NOT.COND_IJ) COND_IJ=COND_IJ.OR.NHEL(GLU_IJ,IHEL)
     $   .EQ.NHEL(GLU_IJ,1)
C       if (nhel(glu_ij,ihel).EQ.NHEL(GLU_IJ,1).or.skip(nfksprocess).eq
C       .0) then
        IF (COND_IJ) THEN
          IF ((GOODHEL(IHEL,NFKSPROCESS) .OR. GOODHEL(IHEL
     $     +SKIP(NFKSPROCESS),NFKSPROCESS) .OR. NTRY(NFKSPROCESS) .LT.
     $      2) ) THEN

            CALL BORN(P1,NHEL(1,IHEL),IHEL,T,BORNS)
            DO I=1,NSQAMPSO
              ANS(1,I)=ANS(1,I)+T(1,I)
              ANS(2,I)=ANS(2,I)+T(2,I)
            ENDDO
            IF ( BORNS(1,0).NE.0D0 .AND. .NOT. GOODHEL(IHEL
     $       ,NFKSPROCESS) ) THEN
              GOODHEL(IHEL,NFKSPROCESS)=.TRUE.
            ENDIF
            IF ( BORNS(2,0).NE.0D0 .AND. .NOT. GOODHEL(IHEL
     $       +SKIP(NFKSPROCESS),NFKSPROCESS) ) THEN
              GOODHEL(IHEL+SKIP(NFKSPROCESS),NFKSPROCESS)=.TRUE.
            ENDIF
          ENDIF
        ENDIF
      ENDDO
      DO I=1,NSQAMPSO
        ANS(1,I)=ANS(1,I)/DBLE(IDEN)
        ANS(2,I)=ANS(2,I)/DBLE(IDEN)
        ANS(1,0)=ANS(1,0)+ANS(1,I)
        ANS(2,0)=ANS(2,0)+ANS(2,I)
      ENDDO
      CALCULATEDBORN=.TRUE.
      END


      SUBROUTINE BORN(P,NHEL,HELL,ANS,BORNS)
C     
C     Generated by MadGraph7 v. %(version)s, %(date)s
C     By the MadGraph7 Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     RETURNS AMPLITUDE SQUARED SUMMED/AVG OVER COLORS
C     FOR THE POINT WITH EXTERNAL LINES W(0:6,NEXTERNAL-1)
C     
C     The amplitudes are computed by GET_AMP_BORN, the Born JAMPs by
C     GET_JAMP_BORN and all colour sums by BORN_COLOR_SQUARE (colour
C     matrix 0 = the Born one). The JAMPs of every helicity are saved
C      in
C     /TO_SAVEJAMP/ so that the colour-linked Borns (SB_SF_LINK) are
C      just
C     a contraction of the same JAMPs with another colour matrix.

C     Process: g g > t t~ [ real = QCD QED ] QCD^2<=4 QED^2<=2
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER NAMPSO, NSQAMPSO
      PARAMETER (NAMPSO=1, NSQAMPSO=1)
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=   3)
      INTEGER    NCOLOR
      PARAMETER (NCOLOR=2)
      INCLUDE 'nexternal.inc'
      INCLUDE 'born_nhel.inc'
C     
C     ARGUMENTS
C     
      REAL*8 P(0:3,NEXTERNAL-1),BORNS(2,0:NSQAMPSO)
      INTEGER NHEL(NEXTERNAL-1), HELL
      COMPLEX*16 ANS(2,NSQAMPSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I,J,IHEL,BACK_HEL,GLU_IJ,IHSAVE,IFLIP
      COMPLEX*16 AMP(NGRAPHS), JAMP(NCOLOR,NAMPSO), JAMPH(2, NCOLOR
     $ ,NAMPSO)
      COMPLEX*16 RES(NSQAMPSO)
C     
C     GLOBAL VARIABLES
C     
      DOUBLE PRECISION AMP2(3), JAMP2(0:2,0:NAMPSO)
      COMMON/TO_AMPS_BORN/  AMP2,       JAMP2
      DOUBLE COMPLEX SAVEAMP(NGRAPHS,MAX_BHEL)
      COMMON/TO_SAVEAMP/SAVEAMP
      DOUBLE COMPLEX SAVEJAMP(NCOLOR,NAMPSO,MAX_BHEL)
      COMMON/TO_SAVEJAMP/SAVEJAMP
      DOUBLE PRECISION HEL_FAC
      INTEGER GET_HEL,SKIP(10)
      COMMON/CBORN/HEL_FAC,GET_HEL,SKIP
      LOGICAL CALCULATEDBORN
      COMMON/CCALCULATEDBORN/CALCULATEDBORN
      INTEGER NFKSPROCESS
      COMMON/C_NFKSPROCESS/NFKSPROCESS
      INTEGER STEP_HEL
      LOGICAL COND_IJ
      LOGICAL FORCE_IJGLU_ZERO
      COMMON /TO_FORCE_IJGLU/ FORCE_IJGLU_ZERO

      INTEGER IJ_VALUES(10)
      DATA IJ_VALUES /1, 1, 1, 1, 2, 2, 2, 2, 0, 0/
C     ----------
C     BEGIN CODE
C     ----------
      BORNS(:,:) =0D0
      ANS(:,:) = (0D0, 0D0)
      JAMPH(:,:,:) = (0D0, 0D0)

      GLU_IJ = IJ_VALUES(NFKSPROCESS)
      IF (FORCE_IJGLU_ZERO) GLU_IJ = 0
      IF (GLU_IJ.NE.0) THEN
        BACK_HEL = NHEL(GLU_IJ)
        IF (BACK_HEL.NE.0) THEN
          STEP_HEL=-2*BACK_HEL
        ELSE
          STEP_HEL=1
        ENDIF
      ELSE
        BACK_HEL=0
        STEP_HEL=1
      ENDIF
      DO IHEL=BACK_HEL,-BACK_HEL,STEP_HEL
        IF (GLU_IJ.NE.0) THEN
          COND_IJ=IHEL.EQ.BACK_HEL.OR.NHEL(GLU_IJ).NE.0
        ELSE
          COND_IJ=IHEL.EQ.BACK_HEL
        ENDIF
        IF (COND_IJ) THEN
          IF (GLU_IJ.NE.0) THEN
            IF (NHEL(GLU_IJ).NE.0) NHEL(GLU_IJ) = IHEL
          ENDIF
C         helicity slot of the saved amplitudes: hell for the helicity
C         passed in, hell+skip for the flipped one of the FKS gluon
          IF(IHEL.EQ.BACK_HEL)THEN
            IHSAVE=HELL
          ELSEIF(IHEL.EQ.-BACK_HEL)THEN
            IHSAVE=HELL+SKIP(NFKSPROCESS)
          ELSE
            WRITE(*,*) 'ERROR #1 in born.f'
            STOP
          ENDIF
          IF (.NOT. CALCULATEDBORN) THEN
            CALL GET_AMP_BORN(P,NHEL,AMP)
            SAVEAMP(1:NGRAPHS,IHSAVE)=AMP(1:NGRAPHS)
          ELSE
            AMP(1:NGRAPHS)=SAVEAMP(1:NGRAPHS,IHSAVE)
          ENDIF
          CALL GET_JAMP_BORN(AMP,JAMP)
          SAVEJAMP(:,:,IHSAVE)=JAMP(:,:)
C         the Born: contraction with the Born colour matrix
          CALL BORN_COLOR_SQUARE(0,JAMP,RES)
          IFLIP=2-(1+BACK_HEL*IHEL)/2
          DO I = 1, NSQAMPSO
            BORNS(IFLIP,I)=BORNS(IFLIP,I)+DBLE(RES(I))
          ENDDO
          DO I = 1, NGRAPHS
            AMP2(I)=AMP2(I)+AMP(I)*DCONJG(AMP(I))
          ENDDO
          DO J = 1,NAMPSO
            DO I = 1, NCOLOR
              JAMP2(I,J)=JAMP2(I,J)+JAMP(I,J)*DCONJG(JAMP(I,J))
              JAMPH(IFLIP,I,J)=JAMP(I,J)
            ENDDO
          ENDDO
        ENDIF
      ENDDO
      DO I = 1, NSQAMPSO
        BORNS(1,0)=BORNS(1,0)+BORNS(1,I)
        BORNS(2,0)=BORNS(2,0)+BORNS(2,I)
        ANS(1,I) = BORNS(1,I) + BORNS(2,I)
      ENDDO
C     the spin-correlated Born: the Born colour matrix between the
C      JAMPs
C     of the two helicities of the FKS gluon
      CALL BORN_COLOR_CONTRACT(0,JAMPH(2,:,:),JAMPH(1,:,:),RES)
      ANS(2,:) = RES(:)
      IF (GLU_IJ.NE.0) NHEL(GLU_IJ) = BACK_HEL
      END


      SUBROUTINE GET_AMP_BORN(P,NHEL,AMP)
C     
C     Generated by MadGraph7 v. %(version)s, %(date)s
C     By the MadGraph7 Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     Returns the Born amplitudes AMP(NGRAPHS) for the helicity
C     configuration NHEL (the HELAS calls)
C     Process: g g > t t~ [ real = QCD QED ] QCD^2<=4 QED^2<=2
C     
      USE ALOHA_OBJECT
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER    NGRAPHS,    NEIGEN
      PARAMETER (NGRAPHS=   3,NEIGEN=  1)
      INTEGER    NWAVEFUNCS
      PARAMETER (NWAVEFUNCS=5)
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
      COMPLEX*16 IMAG1
      PARAMETER (IMAG1 = (0D0,1D0))
      INCLUDE 'nexternal.inc'
      INCLUDE 'coupl.inc'
C     
C     ARGUMENTS
C     
      REAL*8 P(0:3,NEXTERNAL-1)
      INTEGER NHEL(NEXTERNAL-1)
      COMPLEX*16 AMP(NGRAPHS)
C     
C     LOCAL VARIABLES
C     
      INTEGER IC(NEXTERNAL-1),NMO
      PARAMETER (NMO=NEXTERNAL-1)
      DATA IC /NMO*1/
      INTEGER FLAVOR(NEXTERNAL-1)
      DATA FLAVOR /NMO*1/
      TYPE(ALOHA) W(NWAVEFUNCS)
C     ----------
C     BEGIN CODE
C     ----------
      CALL VXXXXX(P(0,1),ZERO,NHEL(1),-1,W(1))
      CALL VXXXXX(P(0,2),ZERO,NHEL(2),-1,W(2))
      CALL OXXXXX(P(0,3),MDL_MT,NHEL(3),+1, FLAVOR(3),W(3))
      CALL IXXXXX(P(0,4),MDL_MT,NHEL(4),-1, FLAVOR(4),W(4))
      CALL VVV1P0_1(W(1),W(2),GC_10,ZERO,ZERO,W(5))
C     Amplitude(s) for diagram number 1
      CALL FFV1_0(W(4),W(3),W(5),GC_11,AMP(1))
      CALL FFV1_1(W(3),W(1),GC_11,MDL_MT,MDL_WT,W(5))
C     Amplitude(s) for diagram number 2
      CALL FFV1_0(W(4),W(5),W(2),GC_11,AMP(2))
      CALL FFV1_2(W(4),W(1),GC_11,MDL_MT,MDL_WT,W(5))
C     Amplitude(s) for diagram number 3
      CALL FFV1_0(W(5),W(3),W(2),GC_11,AMP(3))
      END


      SUBROUTINE GET_JAMP_BORN(AMP,JAMP)
C     
C     Generated by MadGraph7 v. %(version)s, %(date)s
C     By the MadGraph7 Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     Returns the Born JAMPs (colour-ordered amplitudes, in the Born
C      colour
C     basis) for each amplitude split order
C     Process: g g > t t~ [ real = QCD QED ] QCD^2<=4 QED^2<=2
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER NAMPSO
      PARAMETER (NAMPSO=1)
      INTEGER    NGRAPHS
      PARAMETER (NGRAPHS=   3)
      INTEGER    NCOLOR
      PARAMETER (NCOLOR=2)
      COMPLEX*16 IMAG1
      PARAMETER (IMAG1 = (0D0,1D0))
C     
C     ARGUMENTS
C     
      COMPLEX*16 AMP(NGRAPHS), JAMP(NCOLOR,NAMPSO)
C     
C     LOCAL VARIABLES
C     
      COMPLEX*16 TMP_JAMP(0)
C     ----------
C     BEGIN CODE
C     ----------
      JAMP(:,:) = (0D0,0D0)
C     JAMPs contributing to orders QCD=2 QED=0
      JAMP(1,1) = ((0.000000000000000D+00,1.000000000000000D+00))
     $ *AMP(1)+(-1.000000000000000D+00)*AMP(2)
      JAMP(2,1) = ((0.000000000000000D+00,-1.000000000000000D+00))
     $ *AMP(1)+(-1.000000000000000D+00)*AMP(3)
      END


      SUBROUTINE BORN_COLOR_CONTRACT(ILINK,JAMPA,JAMPB,RES)
C     
C     Generated by MadGraph7 v. %(version)s, %(date)s
C     By the MadGraph7 Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     Contracts two sets of Born JAMPs with one of the colour
C      matrices, all
C     expressed in the Born colour basis:
C     ILINK = 0      : the Born colour matrix
C     ILINK = 1..NLINKS : the colour-linked Born for the ILINK-th link
C     (the same numbering as sborn_sf and born_links.dat)
C     For each squared split order it returns
C     RES = sum_ij S_ij (JAMPA(j,M) conj(JAMPB(i,N))
C     + JAMPA(i,M) conj(JAMPB(j,N)))/2
C     i.e. the symmetrised interference needed for the spin-correlated
C      Born.
C     For JAMPA = JAMPB (the Born and the colour-linked Borns) use the
C      cheaper
C     BORN_COLOR_SQUARE. The matrices are symmetric: only the upper
C      triangle
C     is stored, with the off-diagonal entries doubled, as integers
C      over
C     DENOM(ILINK) (BLOCK DATA BORN_COLOR_DATA).
C     Process: g g > t t~ [ real = QCD QED ] QCD^2<=4 QED^2<=2
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER NAMPSO, NSQAMPSO
      PARAMETER (NAMPSO=1, NSQAMPSO=1)
      INTEGER    NCOLOR, NCF, NLINKS
      PARAMETER (NCOLOR=2, NCF=NCOLOR*(NCOLOR+1)/2)
      PARAMETER (NLINKS=8)
C     
C     ARGUMENTS
C     
      INTEGER ILINK
      COMPLEX*16 JAMPA(NCOLOR,NAMPSO), JAMPB(NCOLOR,NAMPSO)
      COMPLEX*16 RES(NSQAMPSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I,J,M,N,CF_INDEX
      COMPLEX*16 ZTEMP
      INTEGER CF(NCF,0:NLINKS), DENOM(0:NLINKS)
      COMMON /C_BORN_COLOR_MATRICES/ CF, DENOM
C     
C     FUNCTION
C     
      INTEGER SQSOINDEXB
C     ----------
C     BEGIN CODE
C     ----------
      RES(:) = (0D0,0D0)
      DO M = 1, NAMPSO
        DO N = 1, NAMPSO
          ZTEMP = (0D0,0D0)
          CF_INDEX = 0
          DO I = 1, NCOLOR
            DO J = I, NCOLOR
              CF_INDEX = CF_INDEX + 1
              IF (CF(CF_INDEX,ILINK).NE.0) ZTEMP = ZTEMP + CF(CF_INDEX
     $         ,ILINK)*(JAMPA(J,M)*DCONJG(JAMPB(I,N))+JAMPA(I,M)
     $         *DCONJG(JAMPB(J,N)))
            ENDDO
          ENDDO
          RES(SQSOINDEXB(M,N)) = RES(SQSOINDEXB(M,N)) + ZTEMP
        ENDDO
      ENDDO
      RES(:) = RES(:)/(2D0*DENOM(ILINK))
      END


      SUBROUTINE BORN_COLOR_SQUARE(ILINK,JAMP,RES)
C     
C     Generated by MadGraph7 v. %(version)s, %(date)s
C     By the MadGraph7 Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     conj(JAMP).S.JAMP for each squared split order, S being the Born
C      colour
C     matrix (ILINK = 0) or the one of the ILINK-th colour link, all
C      in the
C     Born colour basis. Only the real part of RES is meaningful.
C     Process: g g > t t~ [ real = QCD QED ] QCD^2<=4 QED^2<=2
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INTEGER NAMPSO, NSQAMPSO
      PARAMETER (NAMPSO=1, NSQAMPSO=1)
      INTEGER    NCOLOR, NCF, NLINKS
      PARAMETER (NCOLOR=2, NCF=NCOLOR*(NCOLOR+1)/2)
      PARAMETER (NLINKS=8)
C     
C     ARGUMENTS
C     
      INTEGER ILINK
      COMPLEX*16 JAMP(NCOLOR,NAMPSO), RES(NSQAMPSO)
C     
C     LOCAL VARIABLES
C     
      INTEGER I,J,M,N,CF_INDEX
      COMPLEX*16 ZTEMP, ZSUM, ZT(NCOLOR)
      INTEGER CF(NCF,0:NLINKS), DENOM(0:NLINKS)
      COMMON /C_BORN_COLOR_MATRICES/ CF, DENOM
      INTEGER SQSO(NAMPSO,NAMPSO)
      LOGICAL FIRSTTIME
      DATA FIRSTTIME /.TRUE./
      SAVE SQSO, FIRSTTIME
C     
C     FUNCTION
C     
      INTEGER SQSOINDEXB
C     ----------
C     BEGIN CODE
C     ----------
C     the squared split-order index of each (M,N) pair, looked up once
      IF (FIRSTTIME) THEN
        DO M = 1, NAMPSO
          DO N = 1, NAMPSO
            SQSO(M,N) = SQSOINDEXB(M,N)
          ENDDO
        ENDDO
        FIRSTTIME = .FALSE.
      ENDIF
      RES(:) = (0D0,0D0)
      DO M = 1, NAMPSO
C       ZT = S.JAMP(:,M), using the packed upper triangle
        CF_INDEX = 0
        DO I = 1, NCOLOR
          ZTEMP = (0D0,0D0)
          DO J = I, NCOLOR
            CF_INDEX = CF_INDEX + 1
            ZTEMP = ZTEMP + CF(CF_INDEX,ILINK)*JAMP(J,M)
          ENDDO
          ZT(I) = ZTEMP
        ENDDO
        DO N = 1, NAMPSO
          ZSUM = (0D0,0D0)
          DO I = 1, NCOLOR
            ZSUM = ZSUM + ZT(I)*DCONJG(JAMP(I,N))
          ENDDO
          RES(SQSO(M,N)) = RES(SQSO(M,N)) + ZSUM
        ENDDO
      ENDDO
      RES(:) = RES(:)/DENOM(ILINK)
      END


      BLOCK DATA BORN_COLOR_DATA
C     The colour matrices in the Born colour basis: index 0 is the
C      Born one,
C     1..NLINKS the colour links (upper triangle, off-diagonal entries
C      doubled,
C     integers over DENOM)
      IMPLICIT NONE
      INTEGER    NCOLOR, NCF, NLINKS
      PARAMETER (NCOLOR=2, NCF=NCOLOR*(NCOLOR+1)/2)
      PARAMETER (NLINKS=8)
      INTEGER I
      INTEGER CF(NCF,0:NLINKS), DENOM(0:NLINKS)
      COMMON /C_BORN_COLOR_MATRICES/ CF, DENOM
      DATA DENOM(0)/3/
      DATA (CF(I,0),I=1,3) /16,-4,16/
      DATA DENOM(1)/1/
      DATA (CF(I,1),I=1,3) /-9,0,-9/
      DATA DENOM(2)/1/
      DATA (CF(I,2),I=1,3) /-8,2,1/
      DATA DENOM(3)/1/
      DATA (CF(I,3),I=1,3) /1,2,-8/
      DATA DENOM(4)/1/
      DATA (CF(I,4),I=1,3) /1,2,-8/
      DATA DENOM(5)/1/
      DATA (CF(I,5),I=1,3) /-8,2,1/
      DATA DENOM(6)/9/
      DATA (CF(I,6),I=1,3) /32,-8,32/
      DATA DENOM(7)/9/
      DATA (CF(I,7),I=1,3) /-1,-20,-1/
      DATA DENOM(8)/9/
      DATA (CF(I,8),I=1,3) /32,-8,32/
      END


      SUBROUTINE SB_SF_LINK(P,ILINK,ANS_SUMMED)
C     
C     Generated by MadGraph7 v. %(version)s, %(date)s
C     By the MadGraph7 Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     
C     The ILINK-th colour-linked Born, summed over the split orders
C     required for the counterterms (the values per split order are
C     stored in AMP_SPLIT_CNT). It contracts the Born JAMPs saved by
C      the
C     last Born call with the colour matrix of the link, so SBORN must
C     have been called before at the same momenta.
C     
C     Process: g g > t t~ [ real = QCD QED ] QCD^2<=4 QED^2<=2
C     
      IMPLICIT NONE
C     
C     CONSTANTS
C     
      INCLUDE 'nexternal.inc'
      INCLUDE 'born_nhel.inc'
      INTEGER     NCOMB
      PARAMETER ( NCOMB=  16 )
      INTEGER NAMPSO, NSQAMPSO
      PARAMETER (NAMPSO=1, NSQAMPSO=1)
      INTEGER    NCOLOR
      PARAMETER (NCOLOR=2)
C     
C     ARGUMENTS
C     
      REAL*8 P(0:3,NEXTERNAL-1), ANS_SUMMED
      INTEGER ILINK
C     
C     VARIABLES
C     
      INTEGER I,J,IHEL,IDEN
      INCLUDE 'orders.inc'
      REAL*8 ANS(0:NSQAMPSO)
      COMPLEX*16 RES(NSQAMPSO)
      LOGICAL KEEP_ORDER_CNT(NSPLITORDERS, NSQAMPSO)
      COMMON /C_KEEP_ORDER_CNT/ KEEP_ORDER_CNT
      INTEGER AMP_ORDERS(NSPLITORDERS)
      DOUBLE PRECISION TINY
      PARAMETER (TINY = 1D-12)
      DOUBLE PRECISION MAX_VAL
      INTEGER IDEN_VALUES(10)
      DATA IDEN_VALUES /256, 256, 256, 256, 256, 256, 256, 256, 256,
     $  256/
C     
C     GLOBAL VARIABLES
C     
      LOGICAL GOODHEL(NCOMB,10)
      COMMON /C_GOODHEL/ GOODHEL
      DOUBLE COMPLEX SAVEJAMP(NCOLOR,NAMPSO,MAX_BHEL)
      COMMON/TO_SAVEJAMP/SAVEJAMP
      DOUBLE PRECISION SAVEMOM(NEXTERNAL-1,2)
      COMMON/TO_SAVEMOM/SAVEMOM
      LOGICAL CALCULATEDBORN
      COMMON/CCALCULATEDBORN/CALCULATEDBORN
      INTEGER NFKSPROCESS
      COMMON/C_NFKSPROCESS/NFKSPROCESS
C     
C     FUNCTIONS
C     
      INTEGER GETORDPOWFROMINDEX_B
      INTEGER ORDERS_TO_AMP_SPLIT_POS
C     ----------
C     BEGIN CODE
C     ----------
      IDEN=IDEN_VALUES(NFKSPROCESS)
      IF (CALCULATEDBORN) THEN
        DO J=1,NEXTERNAL-1
          IF (SAVEMOM(J,1).NE.P(0,J) .OR. SAVEMOM(J,2).NE.P(3,J)) THEN
            CALCULATEDBORN=.FALSE.
            WRITE(*,*) 'Error in sb_sf: momenta not the same in the'
     $       //' born'
            STOP
          ENDIF
        ENDDO
      ELSE
        WRITE(*,*) 'Error in sb_sf: color_linked borns should be'
     $   //' called only with calculatedborn = true'
        STOP
      ENDIF
      ANS(:) = 0D0
      DO IHEL=1,NCOMB
        IF (GOODHEL(IHEL,NFKSPROCESS)) THEN
          CALL BORN_COLOR_SQUARE(ILINK,SAVEJAMP(:,:,IHEL),RES)
          DO I=1,NSQAMPSO
            ANS(I)=ANS(I)+DBLE(RES(I))
          ENDDO
        ENDIF
      ENDDO
      DO I=1,NSQAMPSO
        ANS(I)=ANS(I)/DBLE(IDEN)
        ANS(0)=ANS(0)+ANS(I)
      ENDDO

C     color-linked borns are called for QCD-type emissions
      ANS_SUMMED = 0D0
      MAX_VAL = 0D0

C     reset the amp_split_cnt array
      AMP_SPLIT_CNT(1:AMP_SPLIT_SIZE,1:2,1:NSPLITORDERS) = DCMPLX(0D0
     $ ,0D0)

      DO I = 1, NSQAMPSO
        MAX_VAL = MAX(MAX_VAL, ABS(ANS(I)))
      ENDDO

      DO I = 1, NSQAMPSO
        IF (KEEP_ORDER_CNT(QCD_POS, I)) THEN
          ANS_SUMMED = ANS_SUMMED + ANS(I)
          DO J = 1, NSPLITORDERS
            AMP_ORDERS(J) = GETORDPOWFROMINDEX_B(J, I)
C           take into account the fact that this is for QCD
            IF (J.EQ.QCD_POS) AMP_ORDERS(J) = AMP_ORDERS(J) + 2
          ENDDO
          IF(ABS(ANS(I)).GT.MAX_VAL*TINY)
     $      AMP_SPLIT_CNT(ORDERS_TO_AMP_SPLIT_POS(AMP_ORDERS),1
     $     ,QCD_POS) = ANS(I)
        ENDIF
      ENDDO

C     this is to avoid fake non-zero contributions
      IF (ABS(ANS_SUMMED).LT.MAX_VAL*TINY) ANS_SUMMED=0D0

      RETURN
      END


      BLOCK DATA GOODHELS
      INTEGER     NCOMB
      PARAMETER ( NCOMB=  16 )
      INTEGER    THEL
      PARAMETER (THEL=NCOMB*10)
      LOGICAL GOODHEL(NCOMB,10)
      COMMON /C_GOODHEL/GOODHEL
      DATA GOODHEL/THEL*.FALSE./
      END



C     
C     Helper functions to deal with the split orders.
C     

      INTEGER FUNCTION SQSOINDEXB(AMPORDERA,AMPORDERB)
C     
C     This functions plays the role of the interference matrix. It can
C      be hardcoded or
C     made more elegant using hashtables if its execution speed ever
C      becomes a relevant
C     factor. From two split order indices of the jamps, it return the
C      corresponding
C     index in the squared order canonical ordering.
C     
C     CONSTANTS
C     
      IMPLICIT NONE
      INTEGER NAMPSO, NSQAMPSO
      PARAMETER (NAMPSO=1, NSQAMPSO=1)
      INTEGER NSPLITORDERS
      PARAMETER (NSPLITORDERS=2)
C     
C     ARGUMENTS
C     
      INTEGER AMPORDERA, AMPORDERB
C     
C     LOCAL VARIABLES
C     
      INTEGER I, SQORDERS(NSPLITORDERS)
      INTEGER AMPSPLITORDERS(NAMPSO,NSPLITORDERS)
      DATA (AMPSPLITORDERS(  1,I),I=  1,  2) /    2,    0/
C     
C     FUNCTION
C     
      INTEGER SQSOINDEXB_FROM_ORDERS
C     
C     BEGIN CODE
C     
      DO I=1,NSPLITORDERS
        SQORDERS(I)=AMPSPLITORDERS(AMPORDERA,I)
     $   +AMPSPLITORDERS(AMPORDERB,I)
      ENDDO
      SQSOINDEXB=SQSOINDEXB_FROM_ORDERS(SQORDERS)
      END



      INTEGER FUNCTION SQSOINDEXB_FROM_ORDERS(ORDERS)
C     
C     From a list of values for the split orders, this function
C      returns the
C     corresponding index in the squared orders canonical ordering.
C     
      IMPLICIT NONE
      INTEGER NSQAMPSO
      PARAMETER (NSQAMPSO=1)
      INTEGER NSPLITORDERS
      PARAMETER (NSPLITORDERS=2)
C     
C     ARGUMENTS
C     
      INTEGER ORDERS(NSPLITORDERS)
C     
C     LOCAL VARIABLES
C     
      INTEGER I,J
      INTEGER SQSPLITORDERS(NSQAMPSO,NSPLITORDERS)
C     the values listed below are for QCD, QED
      DATA (SQSPLITORDERS(  1,I),I=  1,  2) /    4,    0/
C     
C     BEGIN CODE
C     
      DO I=1,NSQAMPSO
        DO J=1,NSPLITORDERS
          IF (ORDERS(J).NE.SQSPLITORDERS(I,J)) GOTO 1009
        ENDDO
        SQSOINDEXB_FROM_ORDERS = I
        RETURN
 1009   CONTINUE
      ENDDO

      WRITE(*,*) 'ERROR:: Stopping function sqsoindex_from_orders'
      WRITE(*,*) 'Could not find squared orders ',(ORDERS(I),I=1
     $ ,NSPLITORDERS)
      STOP

      END



      INTEGER FUNCTION GETORDPOWFROMINDEX_B(IORDER, INDX)
C     
C     Return the power of the IORDER-th order appearing at position
C      INDX
C     in the split-orders output
C     
      IMPLICIT NONE
      INTEGER NSQAMPSO
      PARAMETER (NSQAMPSO=1)
      INTEGER NSPLITORDERS
      PARAMETER (NSPLITORDERS=2)
C     
C     ARGUMENTS
C     
      INTEGER IORDER, INDX
C     
C     LOCAL VARIABLES
C     
      INTEGER I
      INTEGER SQSPLITORDERS(NSQAMPSO,NSPLITORDERS)
C     the values listed below are for QCD, QED
      DATA (SQSPLITORDERS(  1,I),I=  1,  2) /    4,    0/
C     
C     BEGIN CODE
C     
      IF (IORDER.GT.NSPLITORDERS.OR.IORDER.LT.1) THEN
        WRITE(*,*) 'INVALID IORDER B', IORDER
        WRITE(*,*) 'SHOULD BE BETWEEN 1 AND ', NSPLITORDERS
        STOP
      ENDIF

      IF (INDX.GT.NSQAMPSO.OR.INDX.LT.1) THEN
        WRITE(*,*) 'INVALID INDX B', INDX
        WRITE(*,*) 'SHOULD BE BETWEEN 1 AND ', NSQAMPSO
        STOP
      ENDIF

      GETORDPOWFROMINDEX_B=SQSPLITORDERS(INDX, IORDER)
      END


      SUBROUTINE GET_NSQSO_B(NSQSO)
C     
C     Simple subroutine returning the number of squared split order
C     contributions returned in ANS when calling SMATRIX_SPLITORDERS
C     
      IMPLICIT NONE
      INTEGER NSQAMPSO
      PARAMETER (NSQAMPSO=1)
      INTEGER NSQSO

      NSQSO=NSQAMPSO

      END



