      SUBROUTINE SMATRIX_REAL(P, RET_AMP_SPLIT, WGT)
      IMPLICIT NONE
      INCLUDE 'nexternal.inc'
      INCLUDE 'orders.inc'
      DOUBLE PRECISION RET_AMP_SPLIT(AMP_SPLIT_SIZE)
      DOUBLE PRECISION P(0:3, NEXTERNAL)
      DOUBLE PRECISION WGT
      INTEGER NFKSPROCESS
      COMMON/C_NFKSPROCESS/NFKSPROCESS
      IF (NFKSPROCESS.EQ.1) THEN
        CALL SMATRIX1_AMP(P, RET_AMP_SPLIT, WGT)
      ELSEIF (NFKSPROCESS.EQ.2) THEN
        CALL SMATRIX1_AMP(P, RET_AMP_SPLIT, WGT)
      ELSEIF (NFKSPROCESS.EQ.3) THEN
        CALL SMATRIX1_AMP(P, RET_AMP_SPLIT, WGT)
      ELSEIF (NFKSPROCESS.EQ.4) THEN
        CALL SMATRIX1_AMP(P, RET_AMP_SPLIT, WGT)
      ELSEIF (NFKSPROCESS.EQ.5) THEN
        CALL SMATRIX2_AMP(P, RET_AMP_SPLIT, WGT)
      ELSEIF (NFKSPROCESS.EQ.6) THEN
        CALL SMATRIX2_AMP(P, RET_AMP_SPLIT, WGT)
      ELSEIF (NFKSPROCESS.EQ.7) THEN
        CALL SMATRIX2_AMP(P, RET_AMP_SPLIT, WGT)
      ELSEIF (NFKSPROCESS.EQ.8) THEN
        CALL SMATRIX2_AMP(P, RET_AMP_SPLIT, WGT)
      ELSEIF (NFKSPROCESS.EQ.9) THEN
        CALL SMATRIX3_AMP(P, RET_AMP_SPLIT, WGT)
      ELSEIF (NFKSPROCESS.EQ.10) THEN
        CALL SMATRIX3_AMP(P, RET_AMP_SPLIT, WGT)
      ELSEIF (NFKSPROCESS.EQ.11) THEN
        CALL SMATRIX3_AMP(P, RET_AMP_SPLIT, WGT)
      ELSEIF (NFKSPROCESS.EQ.12) THEN
        CALL SMATRIX3_AMP(P, RET_AMP_SPLIT, WGT)
      ELSEIF (NFKSPROCESS.EQ.13) THEN
        CALL SMATRIX4_AMP(P, RET_AMP_SPLIT, WGT)
      ELSEIF (NFKSPROCESS.EQ.14) THEN
        CALL SMATRIX4_AMP(P, RET_AMP_SPLIT, WGT)
      ELSEIF (NFKSPROCESS.EQ.15) THEN
        CALL SMATRIX4_AMP(P, RET_AMP_SPLIT, WGT)
      ELSEIF (NFKSPROCESS.EQ.16) THEN
        CALL SMATRIX4_AMP(P, RET_AMP_SPLIT, WGT)
      ELSEIF (NFKSPROCESS.EQ.17) THEN
        CALL SMATRIX5_AMP(P, RET_AMP_SPLIT, WGT)
      ELSEIF (NFKSPROCESS.EQ.18) THEN
        CALL SMATRIX5_AMP(P, RET_AMP_SPLIT, WGT)
      ELSE
        WRITE(*,*) 'ERROR: invalid n in real_matrix :', NFKSPROCESS
        STOP
      ENDIF
      RETURN
      END

      RECURSIVE SUBROUTINE SMATRIX_REAL_VEC(P, RET_AMP_SPLIT, WGT,
     $  IVEC, NFKSPROCESS, REAL_FLAV_IDX)
      IMPLICIT NONE
      INCLUDE 'nexternal.inc'
      INCLUDE 'orders.inc'
      DOUBLE PRECISION RET_AMP_SPLIT(AMP_SPLIT_SIZE)
      DOUBLE PRECISION P(0:3, NEXTERNAL)
      DOUBLE PRECISION WGT
      INTEGER IVEC
      INTEGER NFKSPROCESS, REAL_FLAV_IDX
      IF (NFKSPROCESS.EQ.1) THEN
        CALL SMATRIX1_AMP_VEC(P, RET_AMP_SPLIT, WGT, IVEC,
     $                   real_flav_idx)
      ELSEIF (NFKSPROCESS.EQ.2) THEN
        CALL SMATRIX1_AMP_VEC(P, RET_AMP_SPLIT, WGT, IVEC,
     $                   real_flav_idx)
      ELSEIF (NFKSPROCESS.EQ.3) THEN
        CALL SMATRIX1_AMP_VEC(P, RET_AMP_SPLIT, WGT, IVEC,
     $                   real_flav_idx)
      ELSEIF (NFKSPROCESS.EQ.4) THEN
        CALL SMATRIX1_AMP_VEC(P, RET_AMP_SPLIT, WGT, IVEC,
     $                   real_flav_idx)
      ELSEIF (NFKSPROCESS.EQ.5) THEN
        CALL SMATRIX2_AMP_VEC(P, RET_AMP_SPLIT, WGT, IVEC,
     $                   real_flav_idx)
      ELSEIF (NFKSPROCESS.EQ.6) THEN
        CALL SMATRIX2_AMP_VEC(P, RET_AMP_SPLIT, WGT, IVEC,
     $                   real_flav_idx)
      ELSEIF (NFKSPROCESS.EQ.7) THEN
        CALL SMATRIX2_AMP_VEC(P, RET_AMP_SPLIT, WGT, IVEC,
     $                   real_flav_idx)
      ELSEIF (NFKSPROCESS.EQ.8) THEN
        CALL SMATRIX2_AMP_VEC(P, RET_AMP_SPLIT, WGT, IVEC,
     $                   real_flav_idx)
      ELSEIF (NFKSPROCESS.EQ.9) THEN
        CALL SMATRIX3_AMP_VEC(P, RET_AMP_SPLIT, WGT, IVEC,
     $                   real_flav_idx)
      ELSEIF (NFKSPROCESS.EQ.10) THEN
        CALL SMATRIX3_AMP_VEC(P, RET_AMP_SPLIT, WGT, IVEC,
     $                   real_flav_idx)
      ELSEIF (NFKSPROCESS.EQ.11) THEN
        CALL SMATRIX3_AMP_VEC(P, RET_AMP_SPLIT, WGT, IVEC,
     $                   real_flav_idx)
      ELSEIF (NFKSPROCESS.EQ.12) THEN
        CALL SMATRIX3_AMP_VEC(P, RET_AMP_SPLIT, WGT, IVEC,
     $                   real_flav_idx)
      ELSEIF (NFKSPROCESS.EQ.13) THEN
        CALL SMATRIX4_AMP_VEC(P, RET_AMP_SPLIT, WGT, IVEC,
     $                   real_flav_idx)
      ELSEIF (NFKSPROCESS.EQ.14) THEN
        CALL SMATRIX4_AMP_VEC(P, RET_AMP_SPLIT, WGT, IVEC,
     $                   real_flav_idx)
      ELSEIF (NFKSPROCESS.EQ.15) THEN
        CALL SMATRIX4_AMP_VEC(P, RET_AMP_SPLIT, WGT, IVEC,
     $                   real_flav_idx)
      ELSEIF (NFKSPROCESS.EQ.16) THEN
        CALL SMATRIX4_AMP_VEC(P, RET_AMP_SPLIT, WGT, IVEC,
     $                   real_flav_idx)
      ELSEIF (NFKSPROCESS.EQ.17) THEN
        CALL SMATRIX5_AMP_VEC(P, RET_AMP_SPLIT, WGT, IVEC,
     $                   real_flav_idx)
      ELSEIF (NFKSPROCESS.EQ.18) THEN
        CALL SMATRIX5_AMP_VEC(P, RET_AMP_SPLIT, WGT, IVEC,
     $                   real_flav_idx)
      ELSE
        WRITE(*,*) 'ERROR: invalid n in real_matrix_vec :', NFKSPROCESS
        STOP
      ENDIF
      RETURN
      END

