C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(3,2,-1)*ProjM(-1,1)
C     
      SUBROUTINE FFV2M_3(F1, F2, MCOUP, M3, W3,V3)
      USE ALOHA_OBJECT
      USE MODEL_OBJECT
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 CZERO
      PARAMETER (CZERO=(0D0,0D0))
      TYPE(FLV_COUPLING) MCOUP
      DOUBLE COMPLEX COUP
      INTEGER FLV_INDEX
      TYPE(ALOHA) F1
      INTEGER FLV_INDEX1
      TYPE(ALOHA) F2
      INTEGER FLV_INDEX2
      COMPLEX*16 FDJS1
      COMPLEX*16 FDJS2
      REAL*8 FDN(0:4)
      REAL*8 FDNQ
      COMPLEX*16 FDQ(0:4)
      REAL*8 M3
      REAL*8 P3(0:3)
      TYPE(ALOHA) V3
      REAL*8 W3
      COMPLEX*16 DENOM
      INTEGER*4 I
      V3%P(:) = +F1%P(:)+F2%P(:)
      P3(:) = -V3 % P (:)
      V3 % W(:) = CZERO
      FDQ(0:3) = -V3 % P(:)
      FDQ(4) = -CI*M3
      CALL DEFINE_GAUGE_DIR(FDQ, FDN)
      FDNQ = FDN(0)*DBLE(FDQ(0))-FDN(1)*DBLE(FDQ(1))-FDN(2)*DBLE(FDQ(2)
     $ )-FDN(3)*DBLE(FDQ(3))
      FLV_INDEX1 = F1 %FLV_INDEX
      FLV_INDEX2 = F2 %FLV_INDEX
      IF(FLV_INDEX1.EQ.0.OR.FLV_INDEX2.EQ.0)THEN
        V3%W(:) = (0D0,0D0)
        RETURN
      ENDIF
      IF(MCOUP % PARTNER(FLV_INDEX1).NE.FLV_INDEX2)THEN
        V3%W(:) = (0D0,0D0)
        RETURN
      ENDIF
      COUP = MCOUP % VAL(FLV_INDEX1) % P
      DENOM = COUP/(P3(0)**2-P3(1)**2-P3(2)**2-P3(3)**2 - M3 * (M3 -CI
     $ * W3))
      V3%W(1)= DENOM*(-CI)*(F2 % W(3)*F1 % W(1)+F2 % W(4)*F1 % W(2))
      V3%W(2)= DENOM*(-CI)*(-F2 % W(4)*F1 % W(1)-F2 % W(3)*F1 % W(2))
      V3%W(3)= DENOM*(-CI)*(-CI*(F2 % W(4)*F1 % W(1))+CI*(F2 % W(3)*F1
     $  % W(2)))
      V3%W(4)= DENOM*(-CI)*(-F2 % W(3)*F1 % W(1)+F2 % W(4)*F1 % W(2))
      FDJS1 = (FDN(0)*V3%W(1)-FDN(1)*V3%W(2)-FDN(2)*V3%W(3)-FDN(3)
     $ *V3%W(4))/FDNQ
      FDJS2 = (FDQ(0)*V3%W(1)-FDQ(1)*V3%W(2)-FDQ(2)*V3%W(3)-FDQ(3)
     $ *V3%W(4)-DCONJG(FDQ(4))*V3%W(5))/FDNQ
      V3%W(1) = V3%W(1)-FDQ(0)*FDJS1-FDN(0)*FDJS2
      V3%W(2) = V3%W(2)-FDQ(1)*FDJS1-FDN(1)*FDJS2
      V3%W(3) = V3%W(3)-FDQ(2)*FDJS1-FDN(2)*FDJS2
      V3%W(4) = V3%W(4)-FDQ(3)*FDJS1-FDN(3)*FDJS2
      V3%W(5) = V3%W(5)-FDQ(4)*FDJS1-FDN(4)*FDJS2
      END


