C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Metric(1,3)
C     
      SUBROUTINE VSV2_0(V1, S2, V3, COUP,VERTEX)
      USE ALOHA_OBJECT
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 CZERO
      PARAMETER (CZERO=(0D0,0D0))
      COMPLEX*16 COUP
      TYPE(ALOHA) S2
      COMPLEX*16 TMP5
      TYPE(ALOHA) V1
      TYPE(ALOHA) V3
      INTEGER*4 I
      COMPLEX*16 VERTEX
      TMP5 = (V3 % W(1)*V1 % W(1)-V3 % W(2)*V1 % W(2)-V3 % W(3)*V1 %
     $  W(3)-V3 % W(4)*V1 % W(4))
      VERTEX = COUP*(-CI * TMP5*S2 % W(5))
      END


