C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(3,1) - P(3,2)
C     
      SUBROUTINE SSV3_0(S1, S2, V3, COUP,VERTEX)
      USE ALOHA_OBJECT
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 CZERO
      PARAMETER (CZERO=(0D0,0D0))
      COMPLEX*16 COUP
      REAL*8 P1(0:3)
      REAL*8 P2(0:3)
      TYPE(ALOHA) S1
      TYPE(ALOHA) S2
      COMPLEX*16 TMP2
      COMPLEX*16 TMP3
      TYPE(ALOHA) V3
      INTEGER*4 I
      COMPLEX*16 VERTEX
      P1(:) = S1 % P (:)
      P2(:) = S2 % P (:)
      TMP2 = (V3 % W(1)*P1(0)-V3 % W(2)*P1(1)-V3 % W(3)*P1(2)-V3 % W(4)
     $ *P1(3))
      TMP3 = (V3 % W(1)*P2(0)-V3 % W(2)*P2(1)-V3 % W(3)*P2(2)-V3 % W(4)
     $ *P2(3))
      VERTEX = COUP*S1 % W(5)*S2 % W(5)*(-CI*(TMP2)+CI*(TMP3))
      END


