C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     P(3,1)*Metric(1,2) - P(3,2)*Metric(1,2) - P(2,1)*Metric(1,3) +
C      P(2,3)*Metric(1,3) + P(1,2)*Metric(2,3) - P(1,3)*Metric(2,3)
C     
      SUBROUTINE VVV1_0(V1, V2, V3, COUP,VERTEX)
      USE ALOHA_OBJECT
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 CZERO
      PARAMETER (CZERO=(0D0,0D0))
      COMPLEX*16 COUP
      REAL*8 P1(0:3)
      REAL*8 P2(0:3)
      REAL*8 P3(0:3)
      COMPLEX*16 TMP1
      COMPLEX*16 TMP2
      COMPLEX*16 TMP3
      COMPLEX*16 TMP4
      COMPLEX*16 TMP5
      COMPLEX*16 TMP6
      COMPLEX*16 TMP7
      COMPLEX*16 TMP8
      COMPLEX*16 TMP9
      TYPE(ALOHA) V1
      TYPE(ALOHA) V2
      TYPE(ALOHA) V3
      INTEGER*4 I
      COMPLEX*16 VERTEX
      P1(:) = V1 % P (:)
      P2(:) = V2 % P (:)
      P3(:) = V3 % P (:)
      TMP1 = (V2 % W(1)*V1 % W(1)-V2 % W(2)*V1 % W(2)-V2 % W(3)*V1 %
     $  W(3)-V2 % W(4)*V1 % W(4))
      TMP2 = (V3 % W(1)*P1(0)-V3 % W(2)*P1(1)-V3 % W(3)*P1(2)-V3 % W(4)
     $ *P1(3))
      TMP3 = (V3 % W(1)*P2(0)-V3 % W(2)*P2(1)-V3 % W(3)*P2(2)-V3 % W(4)
     $ *P2(3))
      TMP4 = (V2 % W(1)*P1(0)-V2 % W(2)*P1(1)-V2 % W(3)*P1(2)-V2 % W(4)
     $ *P1(3))
      TMP5 = (V3 % W(1)*V1 % W(1)-V3 % W(2)*V1 % W(2)-V3 % W(3)*V1 %
     $  W(3)-V3 % W(4)*V1 % W(4))
      TMP6 = (V2 % W(1)*P3(0)-V2 % W(2)*P3(1)-V2 % W(3)*P3(2)-V2 % W(4)
     $ *P3(3))
      TMP7 = (V3 % W(1)*V2 % W(1)-V3 % W(2)*V2 % W(2)-V3 % W(3)*V2 %
     $  W(3)-V3 % W(4)*V2 % W(4))
      TMP8 = (P2(0)*V1 % W(1)-P2(1)*V1 % W(2)-P2(2)*V1 % W(3)-P2(3)*V1
     $  % W(4))
      TMP9 = (V1 % W(1)*P3(0)-V1 % W(2)*P3(1)-V1 % W(3)*P3(2)-V1 % W(4)
     $ *P3(3))
      VERTEX = COUP*(TMP1*(-CI*(TMP2)+CI*(TMP3))+(TMP5*(+CI*(TMP4)-CI
     $ *(TMP6))+TMP7*(-CI*(TMP8)+CI*(TMP9))))
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Coup(1) * (P(3,1)*Metric(1,2) - P(3,2)*Metric(1,2) -
C      P(2,1)*Metric(1,3) + P(2,3)*Metric(1,3) + P(1,2)*Metric(2,3) -
C      P(1,3)*Metric(2,3))
C     Coup(2) * (Metric(1,2))
C     Coup(3) * (Metric(1,3))
C     Coup(4) * (P(1,2) - P(1,3))
C     
      SUBROUTINE VVV1_VVS1_VSV2_VSS1_0(V1, V2, V3, COUP1, COUP2, COUP3
     $ , COUP4,VERTEX)
      USE ALOHA_OBJECT
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 CZERO
      PARAMETER (CZERO=(0D0,0D0))
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 COUP3
      COMPLEX*16 COUP4
      REAL*8 P1(0:3)
      REAL*8 P2(0:3)
      REAL*8 P3(0:3)
      COMPLEX*16 TMP1
      COMPLEX*16 TMP2
      COMPLEX*16 TMP3
      COMPLEX*16 TMP4
      COMPLEX*16 TMP5
      COMPLEX*16 TMP6
      COMPLEX*16 TMP7
      COMPLEX*16 TMP8
      COMPLEX*16 TMP9
      TYPE(ALOHA) V1
      TYPE(ALOHA) V2
      TYPE(ALOHA) V3
      INTEGER*4 I
      COMPLEX*16 VERTEX
      P1(:) = V1 % P (:)
      P2(:) = V2 % P (:)
      P3(:) = V3 % P (:)
      VERTEX = (0D0,0D0)
      TMP1 = (V2 % W(1)*V1 % W(1)-V2 % W(2)*V1 % W(2)-V2 % W(3)*V1 %
     $  W(3)-V2 % W(4)*V1 % W(4))
      TMP2 = (V3 % W(1)*P1(0)-V3 % W(2)*P1(1)-V3 % W(3)*P1(2)-V3 % W(4)
     $ *P1(3))
      TMP3 = (V3 % W(1)*P2(0)-V3 % W(2)*P2(1)-V3 % W(3)*P2(2)-V3 % W(4)
     $ *P2(3))
      TMP4 = (V2 % W(1)*P1(0)-V2 % W(2)*P1(1)-V2 % W(3)*P1(2)-V2 % W(4)
     $ *P1(3))
      TMP5 = (V3 % W(1)*V1 % W(1)-V3 % W(2)*V1 % W(2)-V3 % W(3)*V1 %
     $  W(3)-V3 % W(4)*V1 % W(4))
      TMP6 = (V2 % W(1)*P3(0)-V2 % W(2)*P3(1)-V2 % W(3)*P3(2)-V2 % W(4)
     $ *P3(3))
      TMP7 = (V3 % W(1)*V2 % W(1)-V3 % W(2)*V2 % W(2)-V3 % W(3)*V2 %
     $  W(3)-V3 % W(4)*V2 % W(4))
      TMP8 = (P2(0)*V1 % W(1)-P2(1)*V1 % W(2)-P2(2)*V1 % W(3)-P2(3)*V1
     $  % W(4))
      TMP9 = (V1 % W(1)*P3(0)-V1 % W(2)*P3(1)-V1 % W(3)*P3(2)-V1 % W(4)
     $ *P3(3))
      VERTEX = VERTEX + COUP1*(TMP1*(-CI*(TMP2)+CI*(TMP3))+(TMP5*(+CI
     $ *(TMP4)-CI*(TMP6))+TMP7*(-CI*(TMP8)+CI*(TMP9))))
      VERTEX = VERTEX + COUP2*(-CI * TMP1*V3 % W(5))
      VERTEX = VERTEX + COUP3*(-CI * TMP5*V2 % W(5))
      VERTEX = VERTEX + COUP4*V2 % W(5)*V3 % W(5)*(-CI*(TMP8)+CI*(TMP9)
     $ )
      END


C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Coup(1) * (P(3,1)*Metric(1,2) - P(3,2)*Metric(1,2) -
C      P(2,1)*Metric(1,3) + P(2,3)*Metric(1,3) + P(1,2)*Metric(2,3) -
C      P(1,3)*Metric(2,3))
C     Coup(2) * (Metric(1,3))
C     Coup(3) * (P(1,3) - P(1,2))
C     Coup(4) * (Metric(2,3))
C     Coup(5) * (P(2,3) - P(2,1))
C     Coup(6) * (P(3,1) - P(3,2))
C     
      SUBROUTINE VVV1_VSV2_VSS2_SVV2_SVS2_SSV3_0(V1, V2, V3, COUP1,
     $  COUP2, COUP3, COUP4, COUP5, COUP6,VERTEX)
      USE ALOHA_OBJECT
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 CZERO
      PARAMETER (CZERO=(0D0,0D0))
      COMPLEX*16 COUP1
      COMPLEX*16 COUP2
      COMPLEX*16 COUP3
      COMPLEX*16 COUP4
      COMPLEX*16 COUP5
      COMPLEX*16 COUP6
      REAL*8 P1(0:3)
      REAL*8 P2(0:3)
      REAL*8 P3(0:3)
      COMPLEX*16 TMP1
      COMPLEX*16 TMP2
      COMPLEX*16 TMP3
      COMPLEX*16 TMP4
      COMPLEX*16 TMP5
      COMPLEX*16 TMP6
      COMPLEX*16 TMP7
      COMPLEX*16 TMP8
      COMPLEX*16 TMP9
      TYPE(ALOHA) V1
      TYPE(ALOHA) V2
      TYPE(ALOHA) V3
      INTEGER*4 I
      COMPLEX*16 VERTEX
      P1(:) = V1 % P (:)
      P2(:) = V2 % P (:)
      P3(:) = V3 % P (:)
      VERTEX = (0D0,0D0)
      TMP1 = (V2 % W(1)*V1 % W(1)-V2 % W(2)*V1 % W(2)-V2 % W(3)*V1 %
     $  W(3)-V2 % W(4)*V1 % W(4))
      TMP2 = (V3 % W(1)*P1(0)-V3 % W(2)*P1(1)-V3 % W(3)*P1(2)-V3 % W(4)
     $ *P1(3))
      TMP3 = (V3 % W(1)*P2(0)-V3 % W(2)*P2(1)-V3 % W(3)*P2(2)-V3 % W(4)
     $ *P2(3))
      TMP4 = (V2 % W(1)*P1(0)-V2 % W(2)*P1(1)-V2 % W(3)*P1(2)-V2 % W(4)
     $ *P1(3))
      TMP5 = (V3 % W(1)*V1 % W(1)-V3 % W(2)*V1 % W(2)-V3 % W(3)*V1 %
     $  W(3)-V3 % W(4)*V1 % W(4))
      TMP6 = (V2 % W(1)*P3(0)-V2 % W(2)*P3(1)-V2 % W(3)*P3(2)-V2 % W(4)
     $ *P3(3))
      TMP7 = (V3 % W(1)*V2 % W(1)-V3 % W(2)*V2 % W(2)-V3 % W(3)*V2 %
     $  W(3)-V3 % W(4)*V2 % W(4))
      TMP8 = (P2(0)*V1 % W(1)-P2(1)*V1 % W(2)-P2(2)*V1 % W(3)-P2(3)*V1
     $  % W(4))
      TMP9 = (V1 % W(1)*P3(0)-V1 % W(2)*P3(1)-V1 % W(3)*P3(2)-V1 % W(4)
     $ *P3(3))
      VERTEX = VERTEX + COUP1*(TMP1*(-CI*(TMP2)+CI*(TMP3))+(TMP5*(+CI
     $ *(TMP4)-CI*(TMP6))+TMP7*(-CI*(TMP8)+CI*(TMP9))))
      VERTEX = VERTEX + COUP2*(-CI * TMP5*V2 % W(5))
      VERTEX = VERTEX + COUP3*V2 % W(5)*V3 % W(5)*(-CI*(TMP9)+CI*(TMP8)
     $ )
      VERTEX = VERTEX + COUP4*(-CI * TMP7*V1 % W(5))
      VERTEX = VERTEX + COUP5*V1 % W(5)*V3 % W(5)*(-CI*(TMP6)+CI*(TMP4)
     $ )
      VERTEX = VERTEX + COUP6*V1 % W(5)*V2 % W(5)*(-CI*(TMP2)+CI*(TMP3)
     $ )
      END


