C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Metric(1,2)
C     
      SUBROUTINE VVS1_0(V1, V2, S3, COUP,VERTEX)
      USE ALOHA_OBJECT
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 CZERO
      PARAMETER (CZERO=(0D0,0D0))
      COMPLEX*16 COUP
      TYPE(ALOHA) S3
      COMPLEX*16 TMP1
      TYPE(ALOHA) V1
      TYPE(ALOHA) V2
      INTEGER*4 I
      COMPLEX*16 VERTEX
      TMP1 = (V2 % W(1)*V1 % W(1)-V2 % W(2)*V1 % W(2)-V2 % W(3)*V1 %
     $  W(3)-V2 % W(4)*V1 % W(4))
      VERTEX = COUP*(-CI * TMP1*S3 % W(5))
      END


