C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Metric(2,3)
C     
      SUBROUTINE SVV2_0(S1, V2, V3, COUP,VERTEX)
      USE ALOHA_OBJECT
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 CZERO
      PARAMETER (CZERO=(0D0,0D0))
      COMPLEX*16 COUP
      TYPE(ALOHA) S1
      COMPLEX*16 TMP7
      TYPE(ALOHA) V2
      TYPE(ALOHA) V3
      INTEGER*4 I
      COMPLEX*16 VERTEX
      TMP7 = (V3 % W(1)*V2 % W(1)-V3 % W(2)*V2 % W(2)-V3 % W(3)*V2 %
     $  W(3)-V3 % W(4)*V2 % W(4))
      VERTEX = COUP*(-CI * TMP7*S1 % W(5))
      END


