C     This File is Automatically generated by ALOHA 
C     The process calculated in this file is: 
C     Gamma(3,2,-1)*ProjM(-1,1)
C     
      SUBROUTINE FFV2M_2(F1, V3, MCOUP, M2, W2,F2)
      USE ALOHA_OBJECT
      USE MODEL_OBJECT
      IMPLICIT NONE
      COMPLEX*16 CI
      PARAMETER (CI=(0D0,1D0))
      COMPLEX*16 CZERO
      PARAMETER (CZERO=(0D0,0D0))
      TYPE(FLV_COUPLING) MCOUP
      DOUBLE COMPLEX COUP
      INTEGER FLV_INDEX
      TYPE(ALOHA) F1
      INTEGER FLV_INDEX1
      TYPE(ALOHA) F2
      INTEGER FLV_INDEX2
      REAL*8 M2
      REAL*8 P2(0:3)
      TYPE(ALOHA) V3
      REAL*8 W2
      COMPLEX*16 DENOM
      INTEGER*4 I
      F2%P(:) = +F1%P(:)+V3%P(:)
      P2(:) = -F2 % P (:)
      FLV_INDEX1 = F1 %FLV_INDEX
      IF(FLV_INDEX1.EQ.0)THEN
        F2 % W(:) = (0D0,0D0)
        F2 % FLV_INDEX = 0
        RETURN
      ENDIF
      FLV_INDEX2 = MCOUP % PARTNER(FLV_INDEX1)
      IF(FLV_INDEX2.EQ.0)THEN
        F2 % W(:) = (0D0,0D0)
        F2 % FLV_INDEX = 0
        RETURN
      ENDIF
      F2 % FLV_INDEX = FLV_INDEX2
      COUP = MCOUP % VAL(FLV_INDEX1) % P
      DENOM = COUP/(P2(0)**2-P2(1)**2-P2(2)**2-P2(3)**2 - M2 * (M2 -CI
     $ * W2))
      F2%W(1)= DENOM*CI*(F1 % W(1)*(P2(0)*(V3 % W(1)+V3 % W(4))+(P2(1)
     $ *(-1D0)*(V3 % W(2)+CI*(V3 % W(3)))+(P2(2)*(+CI*(V3 % W(2))-V3 %
     $  W(3))-P2(3)*(V3 % W(1)+V3 % W(4)))))+F1 % W(2)*(P2(0)*(V3 %
     $  W(2)-CI*(V3 % W(3)))+(P2(1)*(-V3 % W(1)+V3 % W(4))+(P2(2)*(+CI
     $ *(V3 % W(1))-CI*(V3 % W(4)))+P2(3)*(-V3 % W(2)+CI*(V3 % W(3)))))
     $ ))
      F2%W(2)= DENOM*CI*(F1 % W(1)*(P2(0)*(V3 % W(2)+CI*(V3 % W(3)))
     $ +(P2(1)*(-1D0)*(V3 % W(1)+V3 % W(4))+(P2(2)*(-1D0)*(+CI*(V3 %
     $  W(1)+V3 % W(4)))+P2(3)*(V3 % W(2)+CI*(V3 % W(3))))))+F1 % W(2)
     $ *(P2(0)*(V3 % W(1)-V3 % W(4))+(P2(1)*(-V3 % W(2)+CI*(V3 % W(3)))
     $ +(P2(2)*(-1D0)*(+CI*(V3 % W(2))+V3 % W(3))+P2(3)*(V3 % W(1)-V3
     $  % W(4))))))
      F2%W(3)= DENOM*(-CI )* M2*(F1 % W(1)*(-1D0)*(V3 % W(1)+V3 % W(4))
     $ +F1 % W(2)*(-V3 % W(2)+CI*(V3 % W(3))))
      F2%W(4)= DENOM*CI * M2*(F1 % W(1)*(V3 % W(2)+CI*(V3 % W(3)))+F1
     $  % W(2)*(V3 % W(1)-V3 % W(4)))
      END


