#! /usr/bin/env python3
################################################################################
#
# Copyright (c) 2010 The MadGraph5_aMC@NLO Development team and Contributors
#
# This file is a part of the MadGraph5_aMC@NLO project, an application which
# automatically generates Feynman diagrams and matrix elements for arbitrary
# high-energy processes in the Standard Model and beyond.
#
# It is subject to the MadGraph5_aMC@NLO license which should accompany this
# distribution.
#
# For more information, visit madgraph.phys.ucl.ac.be and amcatnlo.web.cern.ch
#
################################################################################
"""Differential jet rates from a showered HepMC file, for validating MLM merging.

Reads the final state of a showered event file, reruns the kT jet algorithm on
it with the same parameters the jet-matching veto uses, and records the
clustering scale of every step. Reversed, those are the differential jet rates:

    DJR_{n->n+1}, written d01, d12, d23, ... - the scale at which an event
    stops being resolved as n jets and starts being resolved as n+1.

Why this is the plot to look at
-------------------------------
In kT-MLM the veto clusters the showered event with SlowJet (kT, radius
JetMatching:coneRadius, |eta| < JetMatching:etaJetMax, visible final-state
particles) and compares the resulting jets against the matrix-element partons
at JetMatching:qCut. Reconstructing the same clustering here puts the DJRs on
exactly the scale the veto acts on, so each multiplicity sample has to switch
off where the next one switches on:

  * d01 is filled below qCut by the 0-jet sample (its hardest jet can only come
    from the shower) and above qCut by the 1-jet sample (its hardest jet is a
    matrix-element parton),
  * d12 likewise separates the 1-jet and 2-jet samples, and so on.

Summed over samples the distribution has to be smooth across qCut. A step, a
gap or a bump there means the merging is not working: the samples are either
double counting or leaving a hole.

Because the clustering is redone here from the particle record, the result is
independent of the merging implementation being validated. In particular it
does not need the djrs.dat that the MG5aMC-PY8 interface writes, and it works
the same for events generated by madevent and by madspace/mg7.

Usage
-----
    djr_from_hepmc.py --sample 0j:wj0.hepmc:1234.5 \\
                      --sample 1j:wj1.hepmc:567.8 \\
                      --qcut 30 --output-prefix djr

Each --sample is LABEL:PATH[:CROSS_SECTION_IN_PB]. Without a cross section the
one recorded in the file is used, and failing that the sample is normalised to
unit area, which is enough to see the shapes line up but not to check that the
sum is smooth.
"""

from __future__ import absolute_import

import argparse
import gzip
import math
import os
import sys

import numpy as np


# Defaults matching the MG5aMC Pythia8 card (see JetMatching:* in banner.py).
DEFAULT_RADIUS = 1.0
DEFAULT_ETA_MAX = 1000.0
DEFAULT_N_DJR = 4

# Particles the jet matching keeps out of the clustering. This is the list
# JetMatchingMadgraph applies when it builds workEventJet, the event it both
# vetoes on and takes its own DJRs from:
#
#     // Original AG+Py6 algorithm explicitly excludes tops,
#     // leptons and photons.
#     if ((id >= ID_LEPMIN && id <= ID_LEPMAX) || id == ID_TOP
#       || id == ID_PHOTON || id == 23 || id == 24 || id == 25) ...
#
# i.e. charged leptons and neutrinos (11-16), the top, the photon and the
# electroweak bosons. Getting this wrong does not fail loudly, it just fills
# the rates with things the veto never looked at: for t tbar + jets the top
# decay products swamp d01 and d12 and the merging structure disappears.
NON_JET_PDGS = frozenset([11, 12, 13, 14, 15, 16, 6, 22, 23, 24, 25])

# workEventJet is built from the hardest subsystem plus ISR and FSR, with no
# resonance showers, so the shower has to be run with the resonances left
# undecayed for the reconstruction to see the same final state.


################################################################################
# reading the event file
################################################################################


def open_maybe_gzip(path):
    if path.endswith(".gz"):
        return gzip.open(path, "rt", errors="replace")
    return open(path, "r", errors="replace")


class HepMCFormatError(Exception):
    pass


def read_hepmc(path, max_events=None):
    """Yield (weight, pdg_ids, momenta) for each event in a HepMC file.

    momenta is an (n, 4) array of (px, py, pz, E) for the final-state particles
    only. Both the HepMC2 and the HepMC3 ascii formats are understood; they
    differ in the particle line by one leading field.

    This reads only what the clustering needs, and skips the vertex records
    entirely, which is what makes it fast enough to run over a full sample.
    """
    version = None
    with open_maybe_gzip(path) as stream:
        pdgs, momenta, weight = [], [], 1.0
        in_event = False
        for line in stream:
            if not line:
                continue
            code = line[0]

            if code == "H" or line.startswith("HepMC::"):
                if "Asciiv3" in line or "Version 3" in line:
                    version = 3
                elif "IO_GenEvent" in line or "Version 2" in line:
                    version = 2
                continue

            if code == "E":
                if in_event:
                    yield weight, np.array(pdgs, dtype=np.int64), _as_momenta(momenta)
                    if max_events is not None:
                        max_events -= 1
                        if max_events <= 0:
                            return
                pdgs, momenta = [], []
                in_event = True
                weight = _event_line_weight(line, version)
                continue

            if not in_event:
                continue

            if code == "W":
                # HepMC3 keeps the weights on their own line
                fields = line.split()
                if len(fields) > 1:
                    weight = float(fields[1])
                continue

            if code == "P":
                fields = line.split()
                # HepMC2: P barcode pdg px py pz E m status ...
                # HepMC3: P id  vtx  pdg px py pz E m status
                offset = 3 if _particle_line_is_v3(fields, version) else 2
                if len(fields) < offset + 7:
                    continue
                if int(fields[offset + 6]) != 1:
                    continue  # not a final-state particle
                pdgs.append(int(fields[offset]))
                momenta.append(
                    (
                        float(fields[offset + 1]),
                        float(fields[offset + 2]),
                        float(fields[offset + 3]),
                        float(fields[offset + 4]),
                    )
                )

        if in_event:
            yield weight, np.array(pdgs, dtype=np.int64), _as_momenta(momenta)


def _as_momenta(momenta):
    if not momenta:
        return np.zeros((0, 4))
    return np.array(momenta, dtype=float)


def _particle_line_is_v3(fields, version):
    if version == 3:
        return True
    if version == 2:
        return False
    # No usable header: HepMC3 particle lines carry one more leading integer
    # than HepMC2 ones, and the status is the last field either way.
    return len(fields) >= 10 and fields[9].lstrip("-").isdigit()


def _event_line_weight(line, version):
    """The event weight from an E line. HepMC3 puts weights on a W line
    instead, so this returns 1 there and the W handler overwrites it."""
    fields = line.split()
    if version == 3 or len(fields) < 12:
        return 1.0
    try:
        # E num nmpi scale aQCD aQED sig_id sig_vtx nvtx beam1 beam2 nrandom ...
        index = 11
        n_random = int(fields[index])
        index += 1 + n_random
        n_weights = int(fields[index])
        if n_weights < 1:
            return 1.0
        return float(fields[index + 1])
    except (ValueError, IndexError):
        return 1.0


def read_cross_section(path):
    """The cross section in pb recorded in the file, or None.

    HepMC writes a running estimate on every event, so the last one is the
    converged value for the sample.
    """
    value = None
    with open_maybe_gzip(path) as stream:
        for line in stream:
            if line.startswith("C "):
                fields = line.split()
                if len(fields) >= 2:
                    try:
                        value = float(fields[1])
                    except ValueError:
                        pass
    return value


################################################################################
# the kT clustering
################################################################################


def rapidity(pz, energy):
    """y = 0.5 log((E + pz) / (E - pz)), clipped so that a particle exactly
    along the beam does not produce an infinity."""
    numerator = np.maximum(energy + pz, 1e-12)
    denominator = np.maximum(energy - pz, 1e-12)
    return 0.5 * np.log(numerator / denominator)


def clustering_scales(momenta, radius=DEFAULT_RADIUS):
    """Run the hadron-collider kT algorithm and return sqrt(d) for every step.

    The measures are the standard ones, and the ones SlowJet uses with
    slowJetPower = 1:

        d_ij = min(pT_i^2, pT_j^2) * dR_ij^2 / R^2 ,   dR^2 = dy^2 + dphi^2
        d_iB = pT_i^2

    A step either combines the closest pair or promotes a cluster to a jet,
    whichever measure is smaller; the sequence therefore ends with the beam
    distances of the final jets, so the largest scale is the pT of the hardest
    jet. Values come back in the order the algorithm found them, i.e. smallest
    first.
    """
    n = len(momenta)
    if n == 0:
        return np.empty(0)

    px = momenta[:, 0].astype(float).copy()
    py = momenta[:, 1].astype(float).copy()
    pz = momenta[:, 2].astype(float).copy()
    energy = momenta[:, 3].astype(float).copy()

    pt2 = px * px + py * py
    y = rapidity(pz, energy)
    phi = np.arctan2(py, px)
    r2 = radius * radius

    # d_ij for every pair, with the diagonal and the lower triangle masked off
    # so that each pair appears once
    delta_y = y[:, None] - y[None, :]
    delta_phi = np.abs(phi[:, None] - phi[None, :])
    delta_phi = np.minimum(delta_phi, 2.0 * math.pi - delta_phi)
    dij = np.minimum(pt2[:, None], pt2[None, :]) * (
        delta_y**2 + delta_phi**2
    ) / r2
    dij[np.tril_indices(n)] = np.inf

    # Scanning the whole matrix at every step would make the clustering cubic
    # in the number of particles, which is minutes per thousand events for a
    # hadron-level record. Keeping the minimum of each row instead makes the
    # search linear; the rows that can be invalidated by a step are the ones
    # whose minimum pointed at a cluster that just changed.
    alive = np.ones(n, dtype=bool)
    beam = pt2.copy()
    row_min = dij.min(axis=1)
    row_arg = dij.argmin(axis=1)

    state = _ClusterState(dij, alive, beam, row_min, row_arg, pt2, y, phi, r2)

    scales = []
    for _ in range(n):
        pair_row = int(np.argmin(row_min))
        pair_distance = row_min[pair_row]
        beam_index = int(np.argmin(beam))
        beam_distance = beam[beam_index]

        if beam_distance <= pair_distance:
            scales.append(beam_distance)
            state.drop(beam_index)
            continue

        i, j = pair_row, int(row_arg[pair_row])
        scales.append(pair_distance)
        # E-scheme recombination: add the four-momenta
        px[i] += px[j]
        py[i] += py[j]
        pz[i] += pz[j]
        energy[i] += energy[j]
        state.drop(j)

        pt2[i] = px[i] * px[i] + py[i] * py[i]
        y[i] = 0.5 * math.log(
            max(energy[i] + pz[i], 1e-12) / max(energy[i] - pz[i], 1e-12)
        )
        phi[i] = math.atan2(py[i], px[i])
        beam[i] = pt2[i]
        state.refresh(i)

    return np.sqrt(np.array(scales))


class _ClusterState(object):
    """Bookkeeping for the cached row minima of the distance matrix."""

    def __init__(self, dij, alive, beam, row_min, row_arg, pt2, y, phi, r2):
        self.dij = dij
        self.alive = alive
        self.beam = beam
        self.row_min = row_min
        self.row_arg = row_arg
        self.pt2 = pt2
        self.y = y
        self.phi = phi
        self.r2 = r2

    def _recompute_row(self, r):
        self.row_min[r] = self.dij[r].min()
        self.row_arg[r] = self.dij[r].argmin()

    def _revalidate_rows_pointing_at(self, index):
        rows = np.where((self.row_arg == index) & self.alive)[0]
        for r in rows:
            self._recompute_row(int(r))

    def drop(self, index):
        """Take a cluster out of the event."""
        self.alive[index] = False
        self.beam[index] = np.inf
        self.dij[index, :] = np.inf
        self.dij[:, index] = np.inf
        self.row_min[index] = np.inf
        self.row_arg[index] = index
        self._revalidate_rows_pointing_at(index)

    def refresh(self, i):
        """Recompute every distance involving cluster i, whose momentum
        changed, and repair the row minima that depended on them."""
        others = np.where(self.alive)[0]
        others = others[others != i]
        if len(others):
            delta_y = self.y[i] - self.y[others]
            delta_phi = np.abs(self.phi[i] - self.phi[others])
            delta_phi = np.minimum(delta_phi, 2.0 * math.pi - delta_phi)
            values = (
                np.minimum(self.pt2[i], self.pt2[others])
                * (delta_y**2 + delta_phi**2)
                / self.r2
            )
            # keep the upper-triangle convention so each pair is stored once
            below = others < i
            self.dij[others[below], i] = values[below]
            self.dij[i, others[~below]] = values[~below]

        self._recompute_row(i)
        # every row above i now has a different entry in column i
        for r in np.where(self.alive)[0]:
            r = int(r)
            if r >= i:
                continue
            if self.row_arg[r] == i or self.dij[r, i] < self.row_min[r]:
                self._recompute_row(r)


def differential_jet_rates(momenta, radius=DEFAULT_RADIUS, count=DEFAULT_N_DJR):
    """The first `count` DJRs, largest first: d01, d12, d23, ...

    Entries beyond the number of clustering steps the event has come back as
    NaN and are simply not filled, which is what keeps a low-multiplicity
    sample from contributing a spurious entry at zero.
    """
    scales = clustering_scales(momenta, radius)
    result = np.full(count, np.nan)
    take = min(count, len(scales))
    if take:
        result[:take] = scales[::-1][:take]
    return result


def visible_final_state(pdgs, momenta, eta_max=DEFAULT_ETA_MAX, exclude=None):
    """The particles the matching would cluster: light partons inside the
    acceptance, with the tops, leptons, photons and bosons taken out."""
    if len(pdgs) == 0:
        return momenta
    excluded = NON_JET_PDGS if exclude is None else exclude
    keep = ~np.isin(np.abs(pdgs), list(excluded))
    if eta_max < 100.0:
        px, py, pz = momenta[:, 0], momenta[:, 1], momenta[:, 2]
        p = np.sqrt(px * px + py * py + pz * pz)
        # pseudorapidity, guarded for a particle exactly along the beam
        eta = 0.5 * np.log(np.maximum(p + pz, 1e-12) / np.maximum(p - pz, 1e-12))
        keep &= np.abs(eta) < eta_max
    return momenta[keep]


################################################################################
# histogramming
################################################################################


class DJRHistograms(object):
    """log10(DJR/GeV) histograms for one sample, one per jet rate."""

    def __init__(self, label, count, bins, low, high):
        self.label = label
        self.count = count
        self.edges = np.linspace(low, high, bins + 1)
        self.values = np.zeros((count, bins))
        self.errors2 = np.zeros((count, bins))
        self.event_count = 0
        self.weight_sum = 0.0

    def fill(self, djrs, weight):
        self.event_count += 1
        self.weight_sum += weight
        for index, value in enumerate(djrs):
            if not np.isfinite(value) or value <= 0.0:
                continue
            bin_index = np.searchsorted(self.edges, math.log10(value)) - 1
            if 0 <= bin_index < self.values.shape[1]:
                self.values[index, bin_index] += weight
                self.errors2[index, bin_index] += weight * weight

    def normalise(self, cross_section):
        """Turn the weight sums into dsigma/dlog10(DJR) in pb.

        With a cross section the sample carries its physical normalisation, so
        the samples can be added; without one each is scaled to unit area,
        which shows the shapes but says nothing about the sum.
        """
        width = self.edges[1] - self.edges[0]
        if cross_section is None:
            scale = 1.0 / (self.weight_sum * width) if self.weight_sum else 0.0
        else:
            scale = cross_section / (self.weight_sum * width) if self.weight_sum else 0.0
        self.values *= scale
        self.errors2 *= scale * scale

    @property
    def errors(self):
        return np.sqrt(self.errors2)

    @property
    def centres(self):
        return 0.5 * (self.edges[:-1] + self.edges[1:])


################################################################################
# driving it
################################################################################


class Sample(object):
    def __init__(self, spec):
        parts = spec.split(":")
        if len(parts) < 2:
            raise ValueError(
                "expected LABEL:PATH[:CROSS_SECTION], got %r" % spec
            )
        self.label = parts[0]
        self.path = parts[1]
        self.cross_section = float(parts[2]) if len(parts) > 2 else None
        if not os.path.exists(self.path):
            raise ValueError("no such file: %s" % self.path)

    def __str__(self):
        return self.label


def analyse(sample, args):
    if sample.cross_section is None:
        sample.cross_section = read_cross_section(sample.path)
        if sample.cross_section is not None:
            print(
                "  %s: cross section %g pb read from the file"
                % (sample.label, sample.cross_section)
            )
        else:
            print(
                "  %s: no cross section given or found, normalising to unit area"
                % sample.label
            )

    histograms = DJRHistograms(
        sample.label, args.n_djr, args.bins, args.log_min, args.log_max
    )
    for weight, pdgs, momenta in read_hepmc(sample.path, args.max_events):
        selected = visible_final_state(
            pdgs, momenta, args.eta_max, args.exclude_pdg
        )
        djrs = differential_jet_rates(selected, args.radius, args.n_djr)
        histograms.fill(djrs, weight)
    histograms.normalise(sample.cross_section)
    print("  %s: %d events" % (sample.label, histograms.event_count))
    return histograms


def smoothness_across(centres, total, errors, qcut, window=2):
    """How big a step the summed distribution has across the merging scale.

    Interpolate log(sum) across qcut from the `window` bins on each side and
    compare with what is actually in the bins that straddle it. A merging that
    works gives 1 within the uncertainty; a normalisation mismatch between the
    samples, or a qcut they do not agree on, shows up as a departure from 1.

    Interpolating locally rather than extrapolating a fit from each side
    matters: a DJR distribution has a maximum not far from qcut, and a
    straight-line fit through a curved distribution lands well off the mark and
    reports a step that is not there.

    Returns (ratio, uncertainty) or (None, None) when the bins around qcut are
    not filled well enough to say anything.
    """
    log_qcut = math.log10(qcut)
    width = centres[1] - centres[0]
    index = int(np.searchsorted(centres, log_qcut))

    left = slice(max(index - 1 - window, 0), max(index - 1, 0))
    right = slice(index + 1, index + 1 + window)
    middle = slice(max(index - 1, 0), index + 1)

    x = np.concatenate([centres[left], centres[right]])
    y = np.concatenate([total[left], total[right]])
    if len(x) < 2 or np.any(y <= 0):
        return None, None

    slope, intercept = np.polyfit(x, np.log(y), 1)
    predicted = np.exp(slope * centres[middle] + intercept)
    observed = total[middle]
    if len(observed) == 0 or np.any(predicted <= 0):
        return None, None

    ratio = float(np.mean(observed / predicted))
    # statistical uncertainty of the straddling bins, plus the scatter of the
    # bins the interpolation is built on
    statistical = float(
        np.sqrt(np.sum(errors[middle] ** 2)) / max(np.sum(observed), 1e-30)
    )
    residual = np.log(y) - (slope * x + intercept)
    scatter = float(np.sqrt(np.mean(residual**2)))
    return ratio, ratio * math.sqrt(statistical**2 + scatter**2)


def report_smoothness(histograms, args):
    """Print the step in the summed distribution at qcut, per jet rate."""
    if not args.qcut:
        return
    print(
        "\nContinuity of the summed distribution across qcut = %g GeV\n"
        "(what is in the bins straddling qcut, over what the neighbouring bins\n"
        " interpolate to; 1 means the samples hand over without a step)"
        % args.qcut
    )
    centres = histograms[0].centres
    for index in range(args.n_djr):
        total = sum(h.values[index] for h in histograms)
        errors = np.sqrt(sum(h.errors2[index] for h in histograms))
        ratio, uncertainty = smoothness_across(centres, total, errors, args.qcut)
        name = "d%d%d" % (index, index + 1)
        if ratio is None:
            print("  %s : not enough filled bins on both sides of qcut" % name)
            continue
        pull = abs(ratio - 1.0) / uncertainty if uncertainty else float("inf")
        verdict = "smooth" if pull < 2.0 else "STEP"
        print(
            "  %s : ratio %6.3f +- %5.3f  (%.1f sigma)  %s"
            % (name, ratio, uncertainty, pull, verdict)
        )


def write_table(path, histograms, args):
    """Plain columns, so the numbers can be checked without matplotlib."""
    with open(path, "w") as out:
        out.write("# differential jet rates reconstructed from the showered event record\n")
        out.write(
            "# kT algorithm, R = %g, |eta| < %g, visible final state\n"
            % (args.radius, args.eta_max)
        )
        if args.qcut:
            out.write("# qcut = %g GeV (log10 = %.4f)\n" % (args.qcut, math.log10(args.qcut)))
        for index in range(args.n_djr):
            out.write("\n# d%d%d : dsigma/dlog10(DJR) [pb]\n" % (index, index + 1))
            header = ["log10(DJR)"] + [h.label for h in histograms] + ["sum"]
            out.write("# " + "  ".join("%16s" % name for name in header) + "\n")
            total = sum(h.values[index] for h in histograms)
            for bin_index, centre in enumerate(histograms[0].centres):
                row = [centre] + [h.values[index][bin_index] for h in histograms]
                row.append(total[bin_index])
                out.write("  " + "  ".join("%16.8g" % value for value in row) + "\n")
    print("wrote %s" % path)


def make_plots(prefix, histograms, args):
    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
        import matplotlib.gridspec as gridspec
    except ImportError:
        print(
            "matplotlib is not available, so only the table was written; "
            "plot %s_djr.dat by hand or install matplotlib" % prefix
        )
        return

    for index in range(args.n_djr):
        figure = plt.figure(figsize=(6.5, 5.5))
        grid = gridspec.GridSpec(2, 1, height_ratios=[4, 1])
        grid.update(hspace=0.05)
        main = plt.subplot(grid[0])
        ratio = plt.subplot(grid[1])

        centres = histograms[0].centres
        total = sum(h.values[index] for h in histograms)
        total_error = np.sqrt(sum(h.errors2[index] for h in histograms))

        for histogram in histograms:
            main.step(
                centres,
                histogram.values[index],
                where="mid",
                label=histogram.label,
                linewidth=1.2,
            )
        main.step(
            centres, total, where="mid", label="sum", color="black", linewidth=1.8
        )
        main.fill_between(
            centres,
            total - total_error,
            total + total_error,
            step="mid",
            color="black",
            alpha=0.2,
            linewidth=0,
        )

        if args.qcut:
            for axis in (main, ratio):
                axis.axvline(
                    math.log10(args.qcut), color="grey", linestyle="--", linewidth=1
                )
            main.text(
                math.log10(args.qcut),
                main.get_ylim()[1],
                " qcut",
                va="top",
                color="grey",
                fontsize=9,
            )

        main.set_yscale("log")
        main.set_ylabel(r"$d\sigma/d\log_{10}(\mathrm{DJR})$ [pb]")
        main.set_title("Differential jet rate $d_{%d%d}$" % (index, index + 1))
        main.set_xticklabels([])
        main.legend(loc="best", fontsize=9, ncol=2)

        # each sample's share of the total: this is where a step at qcut shows
        with np.errstate(divide="ignore", invalid="ignore"):
            for histogram in histograms:
                share = np.where(total > 0, histogram.values[index] / total, np.nan)
                ratio.step(centres, share, where="mid", linewidth=1.2)
        ratio.set_ylim(0.0, 1.05)
        ratio.set_ylabel("fraction")
        ratio.set_xlabel(r"$\log_{10}(\mathrm{DJR}/\mathrm{GeV})$")

        path = "%s_d%d%d.%s" % (prefix, index, index + 1, args.format)
        figure.savefig(path, bbox_inches="tight")
        plt.close(figure)
        print("wrote %s" % path)


def build_parser():
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--sample",
        action="append",
        required=True,
        metavar="LABEL:PATH[:XSEC_PB]",
        help="a jet-multiplicity sample; repeat once per sample",
    )
    parser.add_argument(
        "--qcut",
        type=float,
        default=None,
        help="merging scale in GeV, drawn as a line on the plots",
    )
    parser.add_argument(
        "--radius",
        type=float,
        default=DEFAULT_RADIUS,
        help="jet radius, i.e. JetMatching:coneRadius (default %(default)s)",
    )
    parser.add_argument(
        "--eta-max",
        type=float,
        default=DEFAULT_ETA_MAX,
        help="acceptance for the clustered particles, i.e. "
        "JetMatching:etaJetMax (default %(default)s, no cut)",
    )
    parser.add_argument(
        "--n-djr",
        type=int,
        default=DEFAULT_N_DJR,
        help="how many jet rates to compute (default %(default)s)",
    )
    parser.add_argument("--bins", type=int, default=50)
    parser.add_argument("--log-min", type=float, default=0.0)
    parser.add_argument("--log-max", type=float, default=3.0)
    parser.add_argument(
        "--max-events",
        type=int,
        default=None,
        help="stop after this many events per sample",
    )
    parser.add_argument("--output-prefix", default="djr")
    parser.add_argument(
        "--exclude-pdg",
        type=lambda text: frozenset(abs(int(v)) for v in text.split(",")),
        default=None,
        help="comma-separated |pdg| to keep out of the clustering "
        "(default: the tops, leptons, photon and bosons that "
        "JetMatchingMadgraph excludes)",
    )
    parser.add_argument(
        "--format", default="pdf", help="plot file format (default %(default)s)"
    )
    parser.add_argument(
        "--no-plot", action="store_true", help="write the table but no plot"
    )
    return parser


def main(argv=None):
    args = build_parser().parse_args(argv)
    samples = [Sample(spec) for spec in args.sample]

    print(
        "clustering with the kT algorithm, R = %g, |eta| < %g"
        % (args.radius, args.eta_max)
    )
    histograms = [analyse(sample, args) for sample in samples]

    missing = [h.label for h, s in zip(histograms, samples) if s.cross_section is None]
    if missing and len(samples) > 1:
        print(
            "\nWARNING: no cross section for %s, so the samples are not on a\n"
            "         common normalisation and their sum is meaningless.\n"
            "         Pass it as LABEL:PATH:XSEC to check that the sum is smooth."
            % ", ".join(missing)
        )

    report_smoothness(histograms, args)
    write_table("%s_djr.dat" % args.output_prefix, histograms, args)
    if not args.no_plot:
        make_plots(args.output_prefix, histograms, args)
    return 0


if __name__ == "__main__":
    sys.exit(main())
