      SUBROUTINE DLUM_1(LUM)
C     ****************************************************            
C         
C     Generated by MadGraph7 v. %(version)s, %(date)s
C     By the MadGraph7 Development Team
C     Visit launchpad.net/madgraph5 and amcatnlo.web.cern.ch
C     RETURNS PARTON LUMINOSITIES FOR MADFKS                          
C        
C     
C     Process: _anti_quark _quark > _neutrino _anti_lepton a [ all =
C      QCD QED ] QCD^2<=0 QED^2<=6
C     
C     ****************************************************            
C         
      IMPLICIT NONE
C     
C     CONSTANTS                                                       
C         
C     
      INCLUDE 'genps.inc'
      INCLUDE 'nexternal.inc'
      DOUBLE PRECISION       CONV
      PARAMETER (CONV=389379660D0)  !CONV TO PICOBARNS             
C     
C     ARGUMENTS                                                       
C         
C     
      DOUBLE PRECISION LUM
C     
C     LOCAL VARIABLES                                                 
C         
C     
      INTEGER I, ICROSS,LP
      INTEGER NFKSPROCESS
      COMMON/C_NFKSPROCESS/NFKSPROCESS
      INCLUDE 'fks_info.inc'
      INTEGER FKS_PDF_PDG1,FKS_PDF_PDG2
      DOUBLE PRECISION FKS_PDF1,FKS_PDF2
C     
C     STUFF FOR UPC
C     
      DOUBLE PRECISION PHOTONPDFSQUARE
C     
C     EXTERNAL FUNCTIONS                                              
C         
C     
      DOUBLE PRECISION PDG2PDF
C     
C     GLOBAL VARIABLES                                                
C         
C     
      INTEGER              IPROC
      DOUBLE PRECISION PD(0:MAXPROC)
      COMMON /SUBPROC/ PD, IPROC
      INCLUDE 'coupl.inc'
      INCLUDE 'run.inc'
      INTEGER IMIRROR
      COMMON/CMIRROR/IMIRROR
C     
C     STUFF FOR DRESSED EE COLLISIONS
C     
      INCLUDE 'eepdf.inc'
      DOUBLE PRECISION EE_COMP_PROD
      DOUBLE PRECISION DUMMY_COMPONENTS(N_EE)
      DOUBLE PRECISION FKS_PDF1_COMPONENTS(N_EE)
      DOUBLE PRECISION FKS_PDF2_COMPONENTS(N_EE)
      INTEGER I_EE
      INCLUDE '../../Source/PDF/pdf.inc'
C     
C     DATA                                                            
C         
C     

      DATA ICROSS/1/
C     ----------                                                      
C         
C     BEGIN CODE                                                      
C         
C     ----------                                                      
C         
      LUM = 0D0
      IF (PDG_TYPE_D(NFKSPROCESS,1).EQ.22.AND.
     $    PDG_TYPE_D(NFKSPROCESS,2).EQ.22.AND.
     $    ABS(LPP(1)).EQ.2.AND.ABS(LPP(2)).EQ.2.AND.
     $    (PDLABEL(1:4).EQ.'edff'.OR.PDLABEL(1:4).EQ.'chff')) THEN
      FKS_PDF1=DSQRT(PHOTONPDFSQUARE(XBK(1),XBK(2)))
      FKS_PDF2=FKS_PDF1
      ENDIF
      IF (.NOT.(PDG_TYPE_D(NFKSPROCESS,1).EQ.22.AND.
     $    PDG_TYPE_D(NFKSPROCESS,2).EQ.22.AND.
     $    ABS(LPP(1)).EQ.2.AND.ABS(LPP(2)).EQ.2.AND.
     $    (PDLABEL(1:4).EQ.'edff'.OR.PDLABEL(1:4).EQ.'chff'))) THEN
      FKS_PDF_PDG1=PDG_TYPE_D(NFKSPROCESS,1)
      IF (FKS_PDF_PDG1.EQ.21) THEN
        FKS_PDF_PDG1=0
      ELSEIF (FKS_PDF_PDG1.EQ.22) THEN
        FKS_PDF_PDG1=7
      ELSEIF (FKS_PDF_PDG1.EQ.-11) THEN
        FKS_PDF_PDG1=-8
      ELSEIF (FKS_PDF_PDG1.EQ.11) THEN
        FKS_PDF_PDG1=8
      ELSEIF (FKS_PDF_PDG1.EQ.-13) THEN
        FKS_PDF_PDG1=-9
      ELSEIF (FKS_PDF_PDG1.EQ.13) THEN
        FKS_PDF_PDG1=9
      ELSEIF (FKS_PDF_PDG1.EQ.-15) THEN
        FKS_PDF_PDG1=-10
      ELSEIF (FKS_PDF_PDG1.EQ.15) THEN
        FKS_PDF_PDG1=10
      ENDIF
      FKS_PDF1=1D0
      FKS_PDF1_COMPONENTS(1:N_EE)=0D0
      IF (ABS(LPP(1)).GE.1) THEN
        IF (ABS(FKS_PDF_PDG1).LE.10) THEN
          FKS_PDF1=PDG2PDF(LPP(1),
     $      FKS_PDF_PDG1,1,
     $      XBK(1),DSQRT(Q2FACT(1)))
          IF ((ABS(LPP(1)).EQ.4.OR.
     $         ABS(LPP(1)).EQ.3)
     $        .AND.PDLABEL.NE.'none')
     $      FKS_PDF1_COMPONENTS(1:N_EE)=EE_COMPONENTS(1:N_EE)
        ELSE
          FKS_PDF1=0D0
        ENDIF
      ENDIF
      FKS_PDF_PDG2=PDG_TYPE_D(NFKSPROCESS,2)
      IF (FKS_PDF_PDG2.EQ.21) THEN
        FKS_PDF_PDG2=0
      ELSEIF (FKS_PDF_PDG2.EQ.22) THEN
        FKS_PDF_PDG2=7
      ELSEIF (FKS_PDF_PDG2.EQ.-11) THEN
        FKS_PDF_PDG2=-8
      ELSEIF (FKS_PDF_PDG2.EQ.11) THEN
        FKS_PDF_PDG2=8
      ELSEIF (FKS_PDF_PDG2.EQ.-13) THEN
        FKS_PDF_PDG2=-9
      ELSEIF (FKS_PDF_PDG2.EQ.13) THEN
        FKS_PDF_PDG2=9
      ELSEIF (FKS_PDF_PDG2.EQ.-15) THEN
        FKS_PDF_PDG2=-10
      ELSEIF (FKS_PDF_PDG2.EQ.15) THEN
        FKS_PDF_PDG2=10
      ENDIF
      FKS_PDF2=1D0
      FKS_PDF2_COMPONENTS(1:N_EE)=0D0
      IF (ABS(LPP(2)).GE.1) THEN
        IF (ABS(FKS_PDF_PDG2).LE.10) THEN
          FKS_PDF2=PDG2PDF(LPP(2),
     $      FKS_PDF_PDG2,2,
     $      XBK(2),DSQRT(Q2FACT(2)))
          IF ((ABS(LPP(2)).EQ.4.OR.
     $         ABS(LPP(2)).EQ.3)
     $        .AND.PDLABEL.NE.'none')
     $      FKS_PDF2_COMPONENTS(1:N_EE)=EE_COMPONENTS(1:N_EE)
        ELSE
          FKS_PDF2=0D0
        ENDIF
      ENDIF
      ENDIF
      PD(0)=0D0
      IPROC=1
      PD(IPROC)=FKS_PDF1*FKS_PDF2
      IF (ABS(LPP(1)).EQ.ABS(LPP(2)).AND.
     $   (ABS(LPP(1)).EQ.3.OR.ABS(LPP(1)).EQ.4).AND.
     $    PDLABEL.NE.'none')
     $  PD(IPROC)=EE_COMP_PROD(FKS_PDF1_COMPONENTS,
     $                         FKS_PDF2_COMPONENTS)
      DO I=1,IPROC
        IF (NINCOMING.EQ.2) THEN
          LUM = LUM + PD(I) * CONV
        ELSE
          LUM = LUM + PD(I)
        ENDIF
      ENDDO
      RETURN
      END

