"""Generate one Sphinx page per madspace class, for the C++ and Python APIs.

Run from conf.py after the Doxygen XML is produced. Writes
``<source>/madspace/cpp/<Class>.rst`` (breathe ``doxygenclass`` /
``doxygenstruct``) and ``<source>/madspace/python/<Class>.rst``
(``autoclass``), then rewrites the ``cpp-api.rst`` / ``python-api.rst`` landing
pages as a grouped overview (mappings, function generators, compute graph, ...).
Both output directories are wiped first so a removed class does not leave a
stale page behind.
"""

import argparse
import inspect
import re
import shutil
import xml.etree.ElementTree as ET
from dataclasses import dataclass, field
from pathlib import Path

# Top-level classes in the madspace namespace only; nested types (Foo::Bar)
# are documented within their parent's page via :members:.
_TOPLEVEL = re.compile(r"^madspace::[A-Za-z_][A-Za-z0-9_]*$")

_CPP_OPTIONS = (":members:", ":undoc-members:")
_PY_OPTIONS = (":members:", ":undoc-members:", ":show-inheritance:")

# Implementation detail types that should not get their own page. Every
# ``*Instruction`` subclass is excluded too (see ``_denied``); the base
# ``Instruction`` is kept.
_DENY_EXACT = {
    "ShapeExpr",
    "Opcode",
    "InstructionDependencies",
    "LastUseOfLocals",
}


def _denied(short: str) -> bool:
    if short in _DENY_EXACT:
        return True
    return short.endswith("Instruction") and short != "Instruction"


@dataclass
class _Compound:
    short: str
    full: str
    kind: str
    loc: str = ""
    bases: set = field(default_factory=set)


# (heading, one-line intro, predicate). First match wins; the predicate sees a
# ``_Compound`` for the C++ side and a class object for the Python side.
_CPP_GROUPS = [
    (
        "Phase-space mappings",
        "Invertible maps between the unit hypercube and physical phase space; "
        "each also returns its Jacobian weight.",
        lambda c: "madspace::Mapping" in c.bases or c.short == "Mapping",
    ),
    (
        "Function generators",
        "Builders that assemble compute-graph functions for channel weights, "
        "energy scales and network outputs.",
        lambda c: "madspace::FunctionGenerator" in c.bases
        or c.short == "FunctionGenerator",
    ),
    (
        "Phase-space building blocks",
        "Supporting types shared by the mappings: topologies, cuts, observables "
        "and density grids.",
        lambda c: "/phasespace/" in c.loc,
    ),
    (
        "Compute graph",
        "The typed value model and the builder API used to record and compile "
        "functions from instructions.",
        lambda c: "/compgraphs/" in c.loc,
    ),
    (
        "Driver and runtime",
        "The high-level driver plus the tensor and device layer it runs on: "
        "integration, unweighting, event output and execution.",
        lambda c: "/driver/" in c.loc,
    ),
]
_OTHER_GROUP = ("Utilities", "Lower-level helpers and containers.")


def _py_groups(mod):
    mapping = getattr(mod, "Mapping", ())
    generator = getattr(mod, "FunctionGenerator", ())
    compgraph = {
        "Type",
        "Value",
        "BatchSize",
        "DataType",
        "Function",
        "FunctionBuilder",
        "InstructionCall",
        "Instruction",
    }
    return [
        (
            _CPP_GROUPS[0][0],
            _CPP_GROUPS[0][1],
            lambda obj: isinstance(mapping, type) and issubclass(obj, mapping),
        ),
        (
            _CPP_GROUPS[1][0],
            _CPP_GROUPS[1][1],
            lambda obj: isinstance(generator, type) and issubclass(obj, generator),
        ),
        (
            _CPP_GROUPS[3][0],
            _CPP_GROUPS[3][1],
            lambda obj: obj.__name__ in compgraph,
        ),
    ]


def _page(title: str, directive: str, target: str, options) -> str:
    body = "".join(f"   {opt}\n" for opt in options)
    return f"{title}\n{'=' * len(title)}\n\n.. {directive}:: {target}\n{body}"


_EDIT_WARNING = ".. Generated by docs/generate_api_pages.py - do not edit by hand."


def _landing(title: str, intro: str, subdir: str, groups) -> str:
    """``groups`` is a list of (heading, intro, [page names])."""
    out = [_EDIT_WARNING, "", title, "=" * len(title), "", intro, ""]
    for heading, gintro, names in groups:
        if not names:
            continue
        out += [
            heading,
            "-" * len(heading),
            "",
            gintro,
            "",
            ".. toctree::",
            "   :maxdepth: 1",
            "",
        ]
        out += [f"   {subdir}/{name}" for name in sorted(names)]
        out += [""]
    return "\n".join(out)


def _landing_fallback(title: str, intro: str, subdir: str) -> str:
    """Used when there is no Doxygen XML / no importable module (e.g. a plain
    Read the Docs build): a globbed toctree so the page never dangles."""
    return "\n".join(
        [
            _EDIT_WARNING,
            "",
            title,
            "=" * len(title),
            "",
            intro,
            "",
            ".. toctree::",
            "   :glob:",
            "   :maxdepth: 1",
            "",
            f"   {subdir}/*",
            "",
        ]
    )


def _replace_dir(path: Path, pages: dict) -> None:
    if path.exists():
        shutil.rmtree(path)
    path.mkdir(parents=True)
    for name, text in pages.items():
        (path / f"{name}.rst").write_text(text)


def _cpp_compounds(xml_dir: Path):
    index = xml_dir / "index.xml"
    if not index.is_file():
        print(f"generate_api_pages: {index} missing; skipping C++ API")
        return []
    root = ET.parse(index).getroot()
    found = []
    for compound in root.findall("compound"):
        kind = compound.get("kind")
        name = compound.findtext("name", "")
        if kind not in ("class", "struct") or not _TOPLEVEL.match(name):
            continue
        short = name.split("::")[-1]
        if _denied(short):
            continue
        loc, bases = "", set()
        cfile = xml_dir / f"{compound.get('refid')}.xml"
        if cfile.is_file():
            cd = ET.parse(cfile).getroot().find("compounddef")
            if cd is not None:
                node = cd.find("location")
                loc = node.get("file", "") if node is not None else ""
                bases = {b.text or "" for b in cd.findall("basecompoundref")}
        found.append(_Compound(short, name, kind, loc, bases))
    return sorted(found, key=lambda c: c.short)


def _python_classes():
    try:
        import madspace
    except Exception as exc:  # noqa: BLE001 - want the doc build to continue
        print(
            f"generate_api_pages: cannot import madspace ({exc}); skipping Python API"
        )
        return None, []
    members = [
        (name, obj)
        for name, obj in inspect.getmembers(madspace, inspect.isclass)
        if getattr(obj, "__module__", "").startswith("madspace")
        and not name.startswith("_")
        and not _denied(name)
    ]
    return madspace, sorted(members)


def _assign(items, groups, key):
    """Bucket ``items`` into ``groups`` by first matching predicate; the rest
    go to ``_OTHER_GROUP``. Returns [(heading, intro, [names])]."""
    buckets = {heading: [] for heading, _, _ in groups}
    other = []
    for item in items:
        for heading, _, pred in groups:
            if pred(item):
                buckets[heading].append(key(item))
                break
        else:
            other.append(key(item))
    result = [(h, i, buckets[h]) for h, i, _ in groups]
    result.append((_OTHER_GROUP[0], _OTHER_GROUP[1], other))
    return result


def generate_api_pages(source_dir, xml_dir) -> None:
    base = Path(source_dir) / "madspace"

    compounds = _cpp_compounds(Path(xml_dir))
    cpp_pages = {
        c.short: _page(
            c.short,
            "doxygenstruct" if c.kind == "struct" else "doxygenclass",
            c.full,
            _CPP_OPTIONS,
        )
        for c in compounds
    }
    _replace_dir(base / "cpp", cpp_pages)
    cpp_title = "C++ API"
    cpp_intro = (
        "Reference for the ``madspace`` C++ classes, extracted from the header "
        "comments, one page per class."
    )
    (base / "cpp-api.rst").write_text(
        _landing(
            cpp_title,
            cpp_intro,
            "cpp",
            _assign(compounds, _CPP_GROUPS, lambda c: c.short),
        )
        if compounds
        else _landing_fallback(cpp_title, cpp_intro, "cpp")
    )

    mod, members = _python_classes()
    py_pages = {
        name: _page(name, "autoclass", f"madspace.{name}", _PY_OPTIONS)
        for name, _ in members
    }
    _replace_dir(base / "python", py_pages)
    py_title = "Python API"
    py_intro = (
        "Reference for the classes exposed by the :mod:`madspace` Python module, "
        "one page per class."
    )
    (base / "python-api.rst").write_text(
        _landing(
            py_title,
            py_intro,
            "python",
            _assign(
                [obj for _, obj in members],
                _py_groups(mod),
                lambda obj: obj.__name__,
            ),
        )
        if members
        else _landing_fallback(py_title, py_intro, "python")
    )

    print(
        f"generate_api_pages: wrote {len(cpp_pages)} C++ and "
        f"{len(py_pages)} Python class pages"
    )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-dir", default="source", type=Path)
    parser.add_argument("--xml-dir", default="build/doxygenxml", type=Path)
    args = parser.parse_args()
    generate_api_pages(args.source_dir, args.xml_dir)
